### ISSUE TITLE
producer.watch has strange behaviour with complex regexps

### ISSUE THREAD

**Issue by ccapndave** [fuse-box/fuse-box#1028]
I came across this when trying to make my fuse dev configuration watch multiple top level directories.

1. `.watch` adds an implicit `$` at the end of the regular expression if there is a single term, but if there are multiple terms (e.g. `dirA|dirB`) then only a single `$` is added, making the first term wrong.  This can be worked around by explicitly writing `dirA$|dirB$`.  In general there seems to be some magic happening in https://github.com/fuse-box/fuse-box/blob/3fb7176bac3e51287785db3359c7e17372e8934b/src/Utils.ts#L142-L154 which is a bit confusing.

2. `.watch` parameters are not relative to the home directory and can match stuff in `.fusebox`, `.git`, etc.

3. Chokidar throws loads of random events.  Happily this seems to be completely fixed by giving it the `{ ignoreInitial: true }` option, after which it does what you would expect.

My suggestion is to either allow `.watch` to take an array (or to make a new `.watchDirs` method?), plus to make `{ ignoreInitial: true }` the default Chokidar option.

In the meantime, the workaround for watching multiple dirs is:

```ts
// This watches everything in the app and src dirs
fuse
      .bundle("app")
      .watch(`${path.join(__dirname, "app", "**")}$|${path.join(__dirname, "src", "**")}$`)

fuse.run({ chokidar: { ignoreInitial: true } });
```

**Comment by ccapndave** [comment]
A neater workaround (for two directories and a file):

```json
.watch([
          path.join(__dirname, "app", "**"),
          path.join(__dirname, "src", "**"),
          path.join(__dirname, "elm-package.json")
      ].join("$|") + "$")
```

**Comment by nchanged** [comment]
@ccapndave watch doesn't accept an arrays atm, but we can introduce it easily! I like your suggestion, maybe you could make a PR?

**Comment by devmondo** [comment]
yes we need array for watch, it is really important.

**Comment by patrickmichalina** [comment]
This `.watch` is super confusing to me. It doesn't respect globs. I am trying to ignore a certain file extension, but not able to...

**Comment by nchanged** [comment]
### FuseBox v4 Major Upgrade

As of today, the latest major version of FuseBox `v4` is available in `fuse-box@next`. FuseBox has undergone a full re-write from scratch, learning from its mistakes in the previous versions.

There are a lot of improvements, speed and config wise.

Get started [here](https://github.com/fuse-box/fuse-box/blob/master/docs/getting-started/get-started.md)

We are still working on the documentation and polishing before the major release. We are getting very close. And we need help testing.

```bash
npm install fuse-box@next
```

Most of the issues that I am closing have been resolved, however, if you find that your issue is still relevant in `v4` don't hesitate to re-open or (better) create a new one with `v4` configuration.
