### ISSUE TITLE
Some modules which read `main` from package.json cannot be imported

### ISSUE THREAD

**Issue by TimePath** [fuse-box/fuse-box#1031]
Some modules (such as joi) expect to be able to `require()` their root directory containing only a `package.json` and follow the value of `main`, as in node and webpack.

Fuse-box emits `~/index.js` instead of `~/lib/index.js` or `./index.js`.

joi/lib/schema.js:
```js
...
const Joi = require('../'); // expects ./index.js, gets ~/index.js
...
```

joi/package.json
```json
{
  ...
  "main": "lib/index.js",
  ...
}
```

**Comment by TimePath** [comment]
`alias` here: https://github.com/fuse-box/fuse-box/blob/625c2d9c65f18652a646469b2535402ae6d81e46/src/core/PathMaster.ts#L217-L224

is being treated as absolute here:
https://github.com/fuse-box/fuse-box/blob/625c2d9c65f18652a646469b2535402ae6d81e46/src/core/PathMaster.ts#L164-L171

when it might be relative.

`resolved` is (correctly) set to `"$PROJECT_DIR/node_modules/joi/lib/index.js"`
`alias` is (correctly for getAbsolutePath?) set to `"index.js"`, it would need to be `"lib/index.js"` to import joi correctly

**Comment by TimePath** [comment]
If I hackishly insert this guard before `getAbsolutePath`, it works as expected

```js
if (name === "../" && root === "$PROJECT_DIR/node_modules/joi/lib") {
    root = "$PROJECT_DIR/node_modules/joi"
}
```

**Comment by nchanged** [comment]
but we are converting a relative URL to a fusebox url, which starts from project root. Are you saying that PathMaster failed to detect correct path?

**Comment by vraptor75011** [comment]
I got the same issue

Using hapi : joi dependency is breaking everything

**Comment by nchanged** [comment]
### FuseBox v4 Major Upgrade

As of today, the latest major version of FuseBox `v4` is available in `fuse-box@next`. FuseBox has undergone a full re-write from scratch, learning from its mistakes in the previous versions.

There are a lot of improvements, speed and config wise.

Get started [here](https://github.com/fuse-box/fuse-box/blob/master/docs/getting-started/get-started.md)

We are still working on the documentation and polishing before the major release. We are getting very close. And we need help testing.

```bash
npm install fuse-box@next
```

Most of the issues that I am closing have been resolved, however, if you find that your issue is still relevant in `v4` don't hesitate to re-open or (better) create a new one with `v4` configuration.
