### ISSUE TITLE
[Docs] Explain it more clearly what does the useTypescriptCompiler do

### ISSUE THREAD

**Issue by wujekbogdan** [fuse-box/fuse-box#1067]
Hi. I'm new to fuse-box. I've discovered it yesterday when trying to set up TypeScript support for a Vue.js project.

I didn't set up any project yet, I'm reading through the docs at the moment. I've just reached the [useTypescriptCompiler](https://fuse-box.org/page/configuration#usetypescriptcompiler) section and I'm a bit confused.

One of the first things you mention in the docs is that instead of Babel, by default, you use TypeScript to transpile JS. So what for the `useTypescriptCompiler` option is? The docs are not clear about what would happen if this option is set to `false`.

Consider the following example:
- `target` is set to `browser@es5`.
- `useTypescriptCompiler` is set to `false`.

I guess that JS files won't be transpiled at all. Am I right? ... but If I am right, then this is a bit confusing. If `target` is set to `browser@es5` then I would expect that the target code is ES5 code.
But probably I misunderstood something ;)

---
PS I'm not sure is it a right place for questions, but I didn't find any community forum for fuse-box

**Comment by nchanged** [comment]
Hi @wujekbogdan 
You can join our Gitter channel 
https://gitter.im/fusebox-bundler/Lobby

As for your question, if you are working with JS (not ts) you need to enable the option regardless of your target because FuseBox uses it to transpile your source code as well as NPM modules

**Comment by wujekbogdan** [comment]
> As for your question, if you are working with JS (not ts) you need to enable the option regardless of your target because FuseBox uses it to transpile your source code as well as NPM modules

Thanks for the answer but I'm still confused. I did a test: 
- I named my root file `index.js`
- I didn't set `useTypescriptCompiler` to `true` (so it was `false` - by default)
- I set `target` to `browser@es5`.
- I wrote some ES6 code

But the output code was transpiled to ES5 anyway. Based on what you said (and based on docs as well) I would expect the code not to be transpiled. 

> You can join our Gitter channel
Thanks. Already joined.

---
Please tell me is Github a proper place to report issues related to docs? I think I'll be able to contribute a lot as a new user. I found several confusing areas there that can be improved.

**Comment by nchanged** [comment]
### FuseBox v4 Major Upgrade

As of today, the latest major version of FuseBox `v4` is available in `fuse-box@next`. FuseBox has undergone a full re-write from scratch, learning from its mistakes in the previous versions.

There are a lot of improvements, speed and config wise.

Get started [here](https://github.com/fuse-box/fuse-box/blob/master/docs/getting-started/get-started.md)

We are still working on the documentation and polishing before the major release. We are getting very close. And we need help testing.

```bash
npm install fuse-box@next
```

Most of the issues that I am closing have been resolved, however, if you find that your issue is still relevant in `v4` don't hesitate to re-open or (better) create a new one with `v4` configuration.
