### ISSUE TITLE
Add support for ReactCSSModules

### ISSUE THREAD

**Issue by oayres** [fuse-box/fuse-box#1078]
On our previous projects in Webpack, we used `react-css-modules`. More specifically we used the `babel-plugin-react-css-modules`. Unfortunately this does not work as expected in Fuse for some reason or another.

The proposed solution is to build a Fuse-specific plugin to achieve optimal performance. Here's the initial requirements from the plugin:

- Transform `styleName='hello'` into `hello_myScopedNamesace_optionalHash`. This may be a multi-part process, converting `styleName='hello'` into `className={styles.hello}` first.
- Read an anonymous stylesheet import for use in styleName. So, if there's only one stylesheet import, like this `import './test.scss'`, it will use this automatically.
- Support multiple named import stylesheets in styleName. So, if you have two imports, we would want them both useable in a scoped fashion:
```
import one from './one.css'
import two from './two.css'
```
Usage:
```
styleName='one.my-style'
styleName='two.example'
```
- Support custom scoped name, as per `babel-plugin-react-css-modules`'s generateScopedName
- Support `.scss` extension

For further reading, this is the plugin we are referring to: https://github.com/gajus/babel-plugin-react-css-modules

Feel free to comment with additional feature requests

Cheers,
Owen

**Comment by nchanged** [comment]
* How about converting `className={styles.hello}` into `className="hello_myScopedNamesace_optionalHash"` that would be simpler and will save some space (we won't store the entire object)

* Regarding scss. The usage would look like:

```
[
 SassPlugin(), ReactCSSModules(), CSSPlugin()
]
```

So, long story shorty, you can replace SassPlugin with anything else.

**Comment by oayres** [comment]
That's cool. Doing that convert is fine @nchanged, however, converting `styleName='hello'` into `className={styles.hello}` would still be a requirement, since it makes the components look a lot cleaner (and is already used across a lot of React projects).

**Comment by nchanged** [comment]
### FuseBox v4 Major Upgrade

As of today, the latest major version of FuseBox `v4` is available in `fuse-box@next`. FuseBox has undergone a full re-write from scratch, learning from its mistakes in the previous versions.

There are a lot of improvements, speed and config wise.

Get started [here](https://github.com/fuse-box/fuse-box/blob/master/docs/getting-started/get-started.md)

We are still working on the documentation and polishing before the major release. We are getting very close. And we need help testing.

```bash
npm install fuse-box@next
```

Most of the issues that I am closing have been resolved, however, if you find that your issue is still relevant in `v4` don't hesitate to re-open or (better) create a new one with `v4` configuration.
