### ISSUE TITLE
Trigger an update on .tsx files

### ISSUE THREAD

**Issue by deamme** [fuse-box/fuse-box#1081]
I want to be able to trigger an update on a specific file - in a similar way as:
Current setup where I have cache off, no HMR and need to use `fuse.sendPageReload`. 
```javascript
  await Sparky.watch('src/**/**.scss', undefined, (event, file) => {
    fuse.sendPageReload();
  }).exec()
```
This works fine but it's triggering a whole page reload and it doesn't make use of the cache.
It could be great if I can get my setup to work with HMR, so when I edit my .styl files I can get it to trigger an update on corresponding .tsx file so my custom transformer runs.

My current setup:
https://github.com/deamme/ts-transform-css-modules-next/tree/master/examples/react/fuse-box

**Comment by nchanged** [comment]
@deamme does that `tsx` module requires the `styl`file?  Because it might happen that your CSS file is processed after the `TSX` module has been processed, in this case, it's hard to imagine a scenario where we would re-trigger it.

**Comment by deamme** [comment]
It does require/import the `.styl` file (my transformer uses this to update the final CSS file). Isn't there some way to make an update event to fusebox like `fuse.sendPageReload();` but just for forcing an update on a specific file such as `index.tsx`? That would pretty much fulfill my setup completely.

**Comment by deamme** [comment]
Is this possible? I would like to make a PR for this but I don't know where to start..

**Comment by nchanged** [comment]
### FuseBox v4 Major Upgrade

As of today, the latest major version of FuseBox `v4` is available in `fuse-box@next`. FuseBox has undergone a full re-write from scratch, learning from its mistakes in the previous versions.

There are a lot of improvements, speed and config wise.

Get started [here](https://github.com/fuse-box/fuse-box/blob/master/docs/getting-started/get-started.md)

We are still working on the documentation and polishing before the major release. We are getting very close. And we need help testing.

```bash
npm install fuse-box@next
```

Most of the issues that I am closing have been resolved, however, if you find that your issue is still relevant in `v4` don't hesitate to re-open or (better) create a new one with `v4` configuration.
