### ISSUE TITLE
PostCSS plugin ignores the postcss.config.js config file

### ISSUE THREAD

**Issue by wujekbogdan** [fuse-box/fuse-box#1091]
This is a good practice to store postcss settings in the `postcss.config.js` file instead of putting them in the build scripts code. 

This is my `postcss.config.js` config:

``` javascript
const autoprefixer = require('autoprefixer');
const objectFitImages = require('postcss-object-fit-images');

module.exports = {
  plugins: [
    autoprefixer({
      browsers: [
        'last 2 versions',
        '> 2%',
      ],
    }),
    objectFitImages(),
  ],
};
```

In fusebox config file I initialize the postcss plugin with no arguments:

``` javascript
[
  'src/scss/app.scss',
  SassPlugin({
    indentedSyntax: false,
    outputStyle: 'expanded',
  }),
  CSSResourcePlugin({
    dist: 'dist/resources',
    resolve: f => `../resources/${f}`,
  }),
  PostCSSPlugin(),
  CSSPlugin({
    inject: false,
    outFile: file => `./dist/css/${path.basename(file)}`,
    minify: this.isProduction,
  }),
],
````

The `PostCSSPlugin` plugin seems to ignore the config file. In the output CSS file I can't see any changes being made.

But when I include PostCSS plugins in the fuse.js config then it works fine:

``` javascript
[
  'src/scss/app.scss',
  SassPlugin({
    indentedSyntax: false,
    outputStyle: 'expanded',
  }),
  CSSResourcePlugin({
    dist: 'dist/resources',
    resolve: f => `../resources/${f}`,
  }),
  PostCSSPlugin([
    autoprefixer({
      browsers: [
        'last 2 versions',
        '> 2%',
      ],
    }),
    objectFitImages(),
  ]),
  CSSPlugin({
    inject: false,
    outFile: file => `./dist/css/${path.basename(file)}`,
    minify: this.isProduction,
  }),
],
```

**Comment by nchanged** [comment]
@wujekbogdan I think that could a nice addition!
Could you make a PR? I think we can also enable `package.json` configuration.

**Comment by nchanged** [comment]
### FuseBox v4 Major Upgrade

As of today, the latest major version of FuseBox `v4` is available in `fuse-box@next`. FuseBox has undergone a full re-write from scratch, learning from its mistakes in the previous versions.

There are a lot of improvements, speed and config wise.

Get started [here](https://github.com/fuse-box/fuse-box/blob/master/docs/getting-started/get-started.md)

We are still working on the documentation and polishing before the major release. We are getting very close. And we need help testing.

```bash
npm install fuse-box@next
```

Most of the issues that I am closing have been resolved, however, if you find that your issue is still relevant in `v4` don't hesitate to re-open or (better) create a new one with `v4` configuration.
