### ISSUE TITLE
Allow real aliasing

### ISSUE THREAD

**Issue by tyrsius** [fuse-box/fuse-box#111]
jspm and Webpack both offer the ability to create aliases (called maps in jspm). This feature is useful for accessing file in the current app without resorting to relative paths. Fuxebox offers the root path `~/feature/code.js`, but this is not interoperable and it also only works on one folder. One of the benefits of defining your own aliases is that you can have multiples, and they can point to arbitrary locations.

[This issue](https://github.com/fuse-box/fuse-box/issues/96) originally requested the feature, but was satisfied with a module require. This does not work if the aliases is intended to be a path into the current code. It will recurse infinitely if the required module will contain aliases to itself.

**Comment by nchanged** [comment]
Fair enough, let's define the specs.

**Comment by devmondo** [comment]
@tyrsius this is really on the road map, stay tuned it will be there :)

**Comment by xdave** [comment]
Really do need aliasing for using things like `preact-compat` with modules that normally depend on `react` and `react-dom`.

The other thing is, there's a crapload of packages that have this `browser` property in their `package.json` that has an alias mapping (which I think is either a `browserify` or `webpack` convention) to provide a different module when bundling for the browser.

An example of a package that uses this is `asap`:

```json
...
"browser": {
  "./asap": "./browser-asap.js",
  "./asap.js": "./browser-asap.js",
  "./raw": "./browser-raw.js",
  "./raw.js": "./browser-raw.js",
  "./test/domain.js": "./test/browser-domain.js"
},
...
```

Because `fuse-box` doesn't support this, I cannot use packages such as `aphrodite`, which depend on `asap`.

**Comment by nchanged** [comment]
I understand.
Can you require them explicitly ?

**Comment by xdave** [comment]
Not that I know of.  I'm attempting to import and use `aphrodite` (for creating inline styles for react components), which depends internally on `asap`.  `asap` is relying upon the bundler to know about the `browser` field on whether to make `aphrodite` import `asap.js` or `browser-asap.js` file when it calls `require('asap')` -- the non-browser version gets imported, which throws a runtime TypeError error because of a missing function that asap is trying to use from `raw.js` (not `browser-raw.js`, etc).

**Comment by nchanged** [comment]
Hm, [that](https://github.com/fuse-box/fuse-box/blob/master/src/PathMaster.ts#L294) does not help?

**Comment by xdave** [comment]
no, because in the `package.json` of `asap`, "main" === "./asap.js".

```js
typeof json.browser === "object" && json.browser[json.main]
```

**Comment by xdave** [comment]
Sorry, I misread... yeah this _should_ work

**Comment by xdave** [comment]
Essentially, the runtime error I get is:

```
Uncaught TypeError: rawAsap.makeRequestCallFromTimer is not a function
```

After investigation, `aphrodite` (in `lib/inject.js`) calls:

```js
var _asap = require('asap');
```

Both `asap/asap.js` and `asap/browser-asap.js` call:

```js
var rawAsap = require("./raw");
```

However, `makeRequestCallFromTimer` is only defined in `browser-raw.js`.  The fact that it's not being found is because the `raw.js` file is being loaded instead.

**Comment by nchanged** [comment]
Do you think you can propose a fix for the PathMaster.ts ?

**Comment by xdave** [comment]
I actually don't know.  `browser-asap.js` is in fact getting loaded, but it's dependent, `browser-raw.js` (from `require('./raw')`), is not.  I'm not sure how to deal with this, because the `'./raw'` module is internal to `asap`, it's not an entry point.

**Comment by xdave** [comment]
Essentially, you'd need to generalize `readMainFile()` for any `require()`, not just `json.main`.  This may actually involve resolving module names because of relative paths, and so-on.

**Comment by nchanged** [comment]
Right, yeah... I see the problem. So when you do `require('./raw')` it should require `browser-raw.js` instead? Cuz package.json said so, right?

**Comment by xdave** [comment]
I suppose that's how it's supposed to work.

**Comment by nchanged** [comment]
But what about server version then?

**Comment by xdave** [comment]
Well, if we're bundling for the server, it would not read the `browser` field in the package json to resolve the module.

**Comment by nchanged** [comment]
So would specify a target for bundling then?

**Comment by xdave** [comment]
I think this may be better fixed in the upstream package.  There's this issue here: https://github.com/kriskowal/asap/issues/50 in which they brought it into it's current state; however, it seems pretty flaky to me.  It seems the pkg author doesn't even quite understand why it works for webpack.

**Comment by nchanged** [comment]
Yep, but we are not Webpack. We need to solve it elegantly ;-)

**Comment by xdave** [comment]
Lol I know.  I will never use webpack again

**Comment by alloy** [comment]
Here’s some details about how the `browser` field is supposed to be interpreted https://github.com/defunctzombie/package-browser-field-spec

**Comment by nchanged** [comment]
Aliases are coming in the next release as an experimental feature for you guys to play with it

```
alias: {
      utils: "~/hello/foo/"
 }
```

**Comment by alloy** [comment]
@nchanged do you want a separate ticket for the `browser` directive of the package?

**Comment by nchanged** [comment]
@alloy oh yes please!

**Comment by alloy** [comment]
👍 Added #258

**Comment by guillaume86** [comment]
@xdave I just hit the same issue you describe in https://github.com/fuse-box/fuse-box/issues/111#issuecomment-281015956
Do you remember how you solved it? I'm not even sure how I triggered it.

**Comment by nchanged** [comment]
@guillaume86 `target : "browser"`
