### ISSUE TITLE
Resolve relative paths in url() statements in sass files

### ISSUE THREAD

**Issue by henry0sue** [fuse-box/fuse-box#1135]
[resolve-url-loader](https://github.com/bholloway/resolve-url-loader) allows relative paths in urls in sass files such as:
```
.my-button {
   background-image: url('../../images/arrow.png');
}
```
In this example, the path to the image is relative to the location of the sass file. **resolve-url-loader** rewrites these urls to a webpack friendly path. Such support is lacking in **SassPlugin**.

**Comment by henry0sue** [comment]
I don't think **CSSResourcePlugin** will solve this problem. By the time the url gets to the CSSResourcePlugin, the context of where the sass file is is already lost. In my project, I have dependencies in sass files under 'node_modules' but as far as I can tell, CSSResourcePlugin tries to resolve images based on the current directory so it can't find the '../../images/arrow.png' in the example above. What is more, it doesn't log any error message either.

**Comment by nchanged** [comment]
### FuseBox v4 Major Upgrade

As of today, the latest major version of FuseBox `v4` is available in `fuse-box@next`. FuseBox has undergone a full re-write from scratch, learning from its mistakes in the previous versions.

There are a lot of improvements, speed and config wise.

Get started [here](https://github.com/fuse-box/fuse-box/blob/master/docs/getting-started/get-started.md)

We are still working on the documentation and polishing before the major release. We are getting very close. And we need help testing.

```bash
npm install fuse-box@next
```

Most of the issues that I am closing have been resolved, however, if you find that your issue is still relevant in `v4` don't hesitate to re-open or (better) create a new one with `v4` configuration.
