### ISSUE TITLE
Sparky src dont handle absolute base path correctly

### ISSUE THREAD

**Issue by CzBuCHi** [fuse-box/fuse-box#1145]
**Sampe code:**
```ts
const rootDir = "c:/some/absolute/path/not/related/to/__dirname";

// this one will not find single file ...
await Sparky.src("*", { base: rootDir })
    .file("*", file => {
      console.log(file);
    })
    .exec();

// this one finds all files correctly
await Sparky.src("*", { base: path.relative(__dirname, rootDir) })
    .file("*", file => {
      console.log(file);
    })
    .exec();
```

After some code reading i found, that this can be fixed by modifying `parse` method in `src\sparky\SparkyFilePattern.ts` - basically dont join `Config.PROJECT_ROOT` into path if `base` is absolute path ...

PS: In my forked repo after these:
```
npm i
gulp installDevDeps
npm run test
```
im gettings errors in ` tests/cli/Cli.test.js` (all except first one throws "Cannot read property 'CLI' of null") so i cannot create PR right now :(

**Comment by nchanged** [comment]
@CzBuCHi There are no errors anymore. Please feel free to make a PR.

**Comment by nchanged** [comment]
### FuseBox v4 Major Upgrade

As of today, the latest major version of FuseBox `v4` is available in `fuse-box@next`. FuseBox has undergone a full re-write from scratch, learning from its mistakes in the previous versions.

There are a lot of improvements, speed and config wise.

Get started [here](https://github.com/fuse-box/fuse-box/blob/master/docs/getting-started/get-started.md)

We are still working on the documentation and polishing before the major release. We are getting very close. And we need help testing.

```bash
npm install fuse-box@next
```

Most of the issues that I am closing have been resolved, however, if you find that your issue is still relevant in `v4` don't hesitate to re-open or (better) create a new one with `v4` configuration.
