### ISSUE TITLE
scoped scss in vue

### ISSUE THREAD

**Issue by RobbertWolfs** [fuse-box/fuse-box#1146]
Any idea why scoped scss in vue does not work?? 

it should be working according to https://github.com/fuse-box/fuse-box/blob/master/docs/plugins/transpilers/VueComponentPlugin.md#scoped-styling

**Comment by RobbertWolfs** [comment]
any ideas?

**Comment by nchanged** [comment]
Hi
I am on vacation ATM with a very limited access to the Internet 

If you could check the source code and see what’s wrong there that would be great. A guy who created this plugin disappeared, I can’t help you right now. Only after 1 week

**Comment by RobbertWolfs** [comment]
At the moment I changed to a lower version of fuse-box, which works 👍 

changed from `^3.0.0-next.44` to `2.3.1`

maybe if I have time this week I will look at it

**Comment by Poimen** [comment]
I have a similar problem with vuejs component - however non `scss` doesn't appear to work for me either.

I used the seed project:
https://github.com/fuse-box/fuse-box-vue-seed

On a vue component file (e.g. Navigation.vue) I change the styling, the change is detected but the style does not update. F5 causes the style to appear.

I attempted to move from `2.4.0` back to `2.3.1` but it has the same effect. I attempted to remove the `scoped` attribute but no luck there.

**Comment by nchanged** [comment]
Guys, we need help with VuePlugin, please feel free to dig in and make a  PR.

**Comment by nchanged** [comment]
### FuseBox v4 Major Upgrade

As of today, the latest major version of FuseBox `v4` is available in `fuse-box@next`. FuseBox has undergone a full re-write from scratch, learning from its mistakes in the previous versions.

There are a lot of improvements, speed and config wise.

Get started [here](https://github.com/fuse-box/fuse-box/blob/master/docs/getting-started/get-started.md)

We are still working on the documentation and polishing before the major release. We are getting very close. And we need help testing.

```bash
npm install fuse-box@next
```

Most of the issues that I am closing have been resolved, however, if you find that your issue is still relevant in `v4` don't hesitate to re-open or (better) create a new one with `v4` configuration.
