### ISSUE TITLE
if CSSModules has a syntax error hmr will stop working

### ISSUE THREAD

**Issue by andrew-w-ross** [fuse-box/fuse-box#1153]
Hey so as the issue says as soon as postcss hits a syntax error hmr stops functioning.

Steps to reproduce

- Clone andrew-w-ross/fuse-hmr-issue
- Confirm hmr works by changing style.css or App.tsx
- Add a nonsense symbol in the style.css like `asdf`

You should get an error from postcss saying Unknown word. At this point you can correct the code or edit the app but HMR will fail. You have to restart fuse-box to get hmr to work.

@nchanged  I'm happy to make a PR if you can confirm the issue.

**Comment by nchanged** [comment]
I am on vacation ATM but I will check as soon as possible

**Comment by andrew-w-ross** [comment]
@Kompwu Cool I'll get on it.

**Comment by nchanged** [comment]
### FuseBox v4 Major Upgrade

As of today, the latest major version of FuseBox `v4` is available in `fuse-box@next`. FuseBox has undergone a full re-write from scratch, learning from its mistakes in the previous versions.

There are a lot of improvements, speed and config wise.

Get started [here](https://github.com/fuse-box/fuse-box/blob/master/docs/getting-started/get-started.md)

We are still working on the documentation and polishing before the major release. We are getting very close. And we need help testing.

```bash
npm install fuse-box@next
```

Most of the issues that I am closing have been resolved, however, if you find that your issue is still relevant in `v4` don't hesitate to re-open or (better) create a new one with `v4` configuration.
