### ISSUE TITLE
Allow Dynamic Named Split Bundles

### ISSUE THREAD

**Issue by mattoni** [fuse-box/fuse-box#1166]
It would be fantastic to have the ability to build dynamic bundles off of a config file. While I understand there are technical issues with truly dynamic split bundles, I think having the ability to manually build up a list of split bundles that I can load with a dynamic `import()` would be very valuable.

Currently, you're able to name split bundles in the config, however trying to load those dynamically results in fuse attempting to load it exactly, i.e. if i have a bundle named `test` pointing to `/files/testItem.js`, and I do `const t = "test"; await import(t)`, fuse attempts to load the file at `/test`. The only real change here would be making named bundles respected in dynamic imports.

**Comment by nchanged** [comment]
Great idea, I've been thinking about it for a while.

We can partially evaluate a variable

```js
const a = "test";
import(a + "/foo")
```

That's easy, but what is more complicated is iteration
```
const arr = ["foo", "bar"]
arr.map(name => import(name) )
```

Do you have an example in mind how you config would work?

**Comment by mattoni** [comment]
Well honestly, just making a list in the fuse config like you do with name bundles would be fine for me. In my fuse.js file I'll read in a config.json file that I use during runtime as well, iterate over it and list the bundle I want to use for each entry, then pass it to fuse like `id -> path` so that way when I do `import("id")` it'll use that internal list first to see if it matches, if so it'll load that bundle.

**Comment by smitt04** [comment]
Is this being worked on?  I would like to contribute if I can get pointed in the right direction.  This is the last thing that is stopping me from migrating an existing `webpack` project over to `fuse-box`.

A simple example of how i use this.

```
function loadComponent(name) {
  return () => import('~/components/' + name + '.vue');
}

loadComponent('home');
loadComponent('about');
```

Currently this does not work, because it tries to fetch the file by direct url on load instead of on compile time.

Another way I am using it is by loading `text` files that I would like to be inserted directly into code. I am not sure if there is already a plugin for this.

An Example:

```
function runGraphQL(query, variables) {
  if (!/\s/.test(query)) {
      query = require(`~/graphql/queries/${query}.graphql`);
    }

    return this.send(query, variables);
}
```

In this example I would like the query variable to contain the content of the `graphql` file.

**Comment by nchanged** [comment]
@smitt04 Hi
I didn't have time yet. 
Basically, it should be computed somewhere [here](https://github.com/fuse-box/fuse-box/blob/master/src/quantum/core/FileAbstraction.ts#L435) with Quantum. Because there is no problems during development.

We need somehow detect if a require statement has computed properties, then traverse the AST scope and find the target variable then concatenate it.

**Comment by nchanged** [comment]
Another, relatively easy solution, but more manual, is to tell quantum which file and which variable should be associated with the context. Because partial evaluation is a tricky business, and it's pron to errors.
For example your case

```js
function runGraphQL(query, variables) {
  if (!/\s/.test(query)) {
      query = require(`~/graphql/queries/${query}.graphql`);
    }

    return this.send(query, variables);
}
```

Will be denormalized


```js
function runGraphQL(query, variables) {
  if (!compiledCondition1) {
      query = $fsx.r(1)
    }
if (!compiledCondition2) {
      query = $fsx.r(2)
    }

    return this.send(query, variables);
}
```

Which is awfully complicated.

So I would suggest configuring it.

```
QuantumPlugin({
    computed : {
      "path/to/module" : {
          query : ["value1", "value2" ]
      }
   }
})
```

In this case, Quantum will know all the possible values of the variable `query` inside a file, which will lead to automatic mapping by string (we have it implemented) and split bundles

**Comment by smitt04** [comment]
@nchanged Maybe I am missing something, but it doesn't work in development for me.  It tries to load those files over url and fails with a 404.

**Comment by nchanged** [comment]
@smitt04 you need to bundle the files explicitly 
```
instructions(">index.js +graphql/queries/**")
```

**Comment by smitt04** [comment]
That worked, thanks.

**Comment by nchanged** [comment]
### FuseBox v4 Major Upgrade

As of today, the latest major version of FuseBox `v4` is available in `fuse-box@next`. FuseBox has undergone a full re-write from scratch, learning from its mistakes in the previous versions.

There are a lot of improvements, speed and config wise.

Get started [here](https://github.com/fuse-box/fuse-box/blob/master/docs/getting-started/get-started.md)

We are still working on the documentation and polishing before the major release. We are getting very close. And we need help testing.

```bash
npm install fuse-box@next
```

Most of the issues that I am closing have been resolved, however, if you find that your issue is still relevant in `v4` don't hesitate to re-open or (better) create a new one with `v4` configuration.
