### ISSUE TITLE
CSSResourcePlugin incorrectly uses backslashes on Windows

### ISSUE THREAD

**Issue by Ciantic** [fuse-box/fuse-box#1191]
fuse-box, 3.2.1
Windows 10

When one uses the CSSResourcePlugin it generates following:

```
@font-face{
  font-family:"Icons16";
  font-weight:normal;
  font-style:normal;
  src:url("\css-resources\1947093779.eot") format("embedded-opentype"), url("\css-resources\230900911.woff") format("woff"), url("\css-resources\1947108335.ttf") format("truetype"); }

@font-face{
  font-family:"Icons20";
  font-weight:normal;
  font-style:normal;
  src:url("\css-resources\1970181804.eot") format("embedded-opentype"), url("\css-resources\946629686.woff") format("woff"), url("\css-resources\1970196360.ttf") format("truetype"); }
```

Which causes an issue because URLs should not be backslashed, it should always use forward slashes.

**Comment by Ciantic** [comment]
Apparently fixed in `3.2.2-next.1`

**Comment by Ciantic** [comment]
Looks like this bug appears to be also in Quantum plugin (3.2.2-next.3):

![image](https://user-images.githubusercontent.com/64731/39088150-ace680fc-45b5-11e8-98e6-868999233438.png)

```
QuantumPlugin({
  css: true,
})
```

**Comment by nchanged** [comment]
### FuseBox v4 Major Upgrade

As of today, the latest major version of FuseBox `v4` is available in `fuse-box@next`. FuseBox has undergone a full re-write from scratch, learning from its mistakes in the previous versions.

There are a lot of improvements, speed and config wise.

Get started [here](https://github.com/fuse-box/fuse-box/blob/master/docs/getting-started/get-started.md)

We are still working on the documentation and polishing before the major release. We are getting very close. And we need help testing.

```bash
npm install fuse-box@next
```

Most of the issues that I am closing have been resolved, however, if you find that your issue is still relevant in `v4` don't hesitate to re-open or (better) create a new one with `v4` configuration.
