### ISSUE TITLE
Watcher enable own regex

### ISSUE THREAD

**Issue by dynasource** [fuse-box/fuse-box#1193]
Im trying to get a custom watcher working, but it seems that it gets broken by a Util method:
`string2RegExp`

Cant we do a check if one is already using a Regex?

**Comment by nchanged** [comment]
Hi, I think it's doable

**Comment by nchanged** [comment]
### FuseBox v4 Major Upgrade

As of today, the latest major version of FuseBox `v4` is available in `fuse-box@next`. FuseBox has undergone a full re-write from scratch, learning from its mistakes in the previous versions.

There are a lot of improvements, speed and config wise.

Get started [here](https://github.com/fuse-box/fuse-box/blob/master/docs/getting-started/get-started.md)

We are still working on the documentation and polishing before the major release. We are getting very close. And we need help testing.

```bash
npm install fuse-box@next
```

Most of the issues that I am closing have been resolved, however, if you find that your issue is still relevant in `v4` don't hesitate to re-open or (better) create a new one with `v4` configuration.
