### ISSUE TITLE
VueComponent: Conflict when several .vue files are in the same folder

### ISSUE THREAD

**Issue by eddow** [fuse-box/fuse-box#1194]
Hello,

A conflict occurs when several `.vue` files are in the same folder.

I could solve this issue by making one folder per `.vue` file but it is still uncomfortable to have dozens of folders with one file in it.

The conflicts (I noticed - there might be others) are :
- The `<style>`s produced end up with the same "id": `[folder]-style-css"`. Therefore, only one out of all the .vue files in the same folder have their css produced and added in the `<head>`
- In the source-map, the "javascript sources" produced have the same filename : `[folder]/script.js`

To reproduce, have 2 `.vue` files in a folder defining their own styles : one will be absent.
The solution I think is to have the `.vue` file filename in the generated names (for style and for script)

**Comment by nchanged** [comment]
### FuseBox v4 Major Upgrade

As of today, the latest major version of FuseBox `v4` is available in `fuse-box@next`. FuseBox has undergone a full re-write from scratch, learning from its mistakes in the previous versions.

There are a lot of improvements, speed and config wise.

Get started [here](https://github.com/fuse-box/fuse-box/blob/master/docs/getting-started/get-started.md)

We are still working on the documentation and polishing before the major release. We are getting very close. And we need help testing.

```bash
npm install fuse-box@next
```

Most of the issues that I am closing have been resolved, however, if you find that your issue is still relevant in `v4` don't hesitate to re-open or (better) create a new one with `v4` configuration.
