### ISSUE TITLE
Add multiple language support in VueComponentPlugin

### ISSUE THREAD

**Issue by smitt04** [fuse-box/fuse-box#1198]
It would be nice to be able to supply multiple languages in the VueComponentPlugin.

Currently you can specify plugin chains like:
```
VueComponentPlugin({
          script: BabelPlugin({ ... }),
          template: ConsolidatePlugin({ ... })
          style: [
              SassPlugin({ ... }),
              CSSResourcePlugin({ ... }),
              PostCSSPlugin( ... ),
              CSSPlugin({ ... })
          ]
      })
    ]
```

But once you add a plugin chain it overwrites the `lang`attribute. So for style and other types if you want to use multiple languages you can't.  If i am converting a project to use `stylus` from `scss` I might have both languages and it works if you use default but not if you customize it.

**Comment by nchanged** [comment]
### FuseBox v4 Major Upgrade

As of today, the latest major version of FuseBox `v4` is available in `fuse-box@next`. FuseBox has undergone a full re-write from scratch, learning from its mistakes in the previous versions.

There are a lot of improvements, speed and config wise.

Get started [here](https://github.com/fuse-box/fuse-box/blob/master/docs/getting-started/get-started.md)

We are still working on the documentation and polishing before the major release. We are getting very close. And we need help testing.

```bash
npm install fuse-box@next
```

Most of the issues that I am closing have been resolved, however, if you find that your issue is still relevant in `v4` don't hesitate to re-open or (better) create a new one with `v4` configuration.
