### ISSUE TITLE
Mention fuse-box-typechecker in documentation

### ISSUE THREAD

**Issue by jpike88** [fuse-box/fuse-box#1211]
Had to do some serious googling to find that project... would be useful to include in docs. Happy to do when I confirm it works.

**Comment by pmonty** [comment]
Yeh I feel the documentation needs to be a little more in-depth as well. Hopefully once I get Fuse-Box working can take some of that burden from @nchanged and other contributors and contribute to the documentation.

**Comment by Kompwu** [comment]
@jpike88 Can you make a PR please ?

**Comment by jpike88** [comment]
I stalled on this because I have no idea how to locally host the documentation so it all lines up correctly.

@nchanged I know it's all markdown, but what is _doc.json describing? Not sure what tool I need to work with this.

**Comment by nchanged** [comment]
@jpike88 just edit an `.md` file there ;-)

**Comment by jpike88** [comment]
I have no way of previewing the full site though. I'm editing a .json file and just adding another .md file? Feel like I'm working a little blind

**Comment by nchanged** [comment]
why would you want to add an extra section? But sure, just add it there, and point to an md file similarly to the others. Other than then it should be a valid MD, that you can preview on github or any other editor with md preview feature. Just make sure to use only one `#` and `##` as subsections

**Comment by Kompwu** [comment]
@jpike88 How's going ?

**Comment by jpike88** [comment]
poop hit the fan over the last week with my projects, still busy as hell. I do have this as a todo, will probably achieve this on friday

**Comment by nchanged** [comment]
### FuseBox v4 Major Upgrade

As of today, the latest major version of FuseBox `v4` is available in `fuse-box@next`. FuseBox has undergone a full re-write from scratch, learning from its mistakes in the previous versions.

There are a lot of improvements, speed and config wise.

Get started [here](https://github.com/fuse-box/fuse-box/blob/master/docs/getting-started/get-started.md)

We are still working on the documentation and polishing before the major release. We are getting very close. And we need help testing.

```bash
npm install fuse-box@next
```

Most of the issues that I am closing have been resolved, however, if you find that your issue is still relevant in `v4` don't hesitate to re-open or (better) create a new one with `v4` configuration.
