### ISSUE TITLE
log has to be enabled for `showBundledFiles` to work

### ISSUE THREAD

**Issue by stubar** [fuse-box/fuse-box#1226]
For me it's not clear from the docs that for the following to work
```
const fuse = FuseBox.init({
  log: {
      showBundledFiles: false, // Don't list all the bundled files every time we bundle
      clearTerminalOnBundle: true, // Clear the terminal window every time we bundle
  }
})
```
You have to set `enabled: true` in the log key.   Also `clearTerminalOnBundle` doesn't seem to make a difference for me, but this maybe my IDE's console (PHPStorm)?.

Finally It would be good to be able to suppress the vendor files report ie the `echoCollection` function in Log.js.  Maybe a separate flag?

**Comment by jpike88** [comment]
PRs are welcome, we're all hands on here...

**Comment by stubar** [comment]
```showBundledFiles: false``` Should prevent the grey output displaying **after** the initial build.  Grey output being your project files as opposed to vendor files.  I can have a go at a PR soon.  Do we agree that the default log key should be:   
```
{
      enabled: true,
      showBundledFiles: true, // list all the project bundled files every time we bundle
      showVendorBundledFiles: true // list all the vendor bundled files every time we bundle
      clearTerminalOnBundle: true, // Clear the terminal window every time we bundle
}
```
So we'd only use a log key to turn things off.

@eddyw Does ```clearTerminalOnBundle``` do anything for you?

**Comment by stubar** [comment]
I'm proposing a new key for the vendors ```showVendorBundledFiles```

**Comment by nchanged** [comment]
### FuseBox v4 Major Upgrade

As of today, the latest major version of FuseBox `v4` is available in `fuse-box@next`. FuseBox has undergone a full re-write from scratch, learning from its mistakes in the previous versions.

There are a lot of improvements, speed and config wise.

Get started [here](https://github.com/fuse-box/fuse-box/blob/master/docs/getting-started/get-started.md)

We are still working on the documentation and polishing before the major release. We are getting very close. And we need help testing.

```bash
npm install fuse-box@next
```

Most of the issues that I am closing have been resolved, however, if you find that your issue is still relevant in `v4` don't hesitate to re-open or (better) create a new one with `v4` configuration.
