### ISSUE TITLE
Integrate with tsickle for more powerful minification

### ISSUE THREAD

**Issue by phamtm** [fuse-box/fuse-box#1247]
This tool is to transforming typescripts code into google closure code (see https://github.com/angular/tsickle ).

Since fusebox is written in Typescript I was thinking how can fuse-box integrate with this tool so that typescript project can benefit from better minification.

Any recommendation or pointer is much appreciated.

**Comment by nchanged** [comment]
Sounds interesting, now do they have a typescript transform plugin? Fusebox supports them

**Comment by phamtm** [comment]
I don't think they have typescript transform plugin, according to the doc

> Tsickle works by wrapping tsc. To use it, you must set up your project such that it builds correctly when you run tsc from the command line, by configuring the settings in tsconfig.json.

So they just monkey patch the typescript compiler I guess

**Comment by nchanged** [comment]
Then why not just configuring `tsconfig.json` FuseBox loads it first

**Comment by phamtm** [comment]
I think configuring `tsconfig.json` is the easy part. But the point is that we must replace typescript compiler (`tsc`) with `tsickle`. Everything needs to be compiled by tsickle, even the fusebox runtime. I'm not sure how big of a change this is.

**Comment by Kompwu** [comment]
@phamtm Sounds easy, just use a `bool` and switch `tsickle` or `tsc` :wink:

**Comment by nchanged** [comment]
### FuseBox v4 Major Upgrade

As of today, the latest major version of FuseBox `v4` is available in `fuse-box@next`. FuseBox has undergone a full re-write from scratch, learning from its mistakes in the previous versions.

There are a lot of improvements, speed and config wise.

Get started [here](https://github.com/fuse-box/fuse-box/blob/master/docs/getting-started/get-started.md)

We are still working on the documentation and polishing before the major release. We are getting very close. And we need help testing.

```bash
npm install fuse-box@next
```

Most of the issues that I am closing have been resolved, however, if you find that your issue is still relevant in `v4` don't hesitate to re-open or (better) create a new one with `v4` configuration.
