### ISSUE TITLE
Consider migrate/inspire to PM2

### ISSUE THREAD

**Issue by Kompwu** [fuse-box/fuse-box#1256]
It seems really suitable, the process manager is really nice.
It's robust too.
There is also a lot of goods things:
* Behavior configuration
* Source map support
* Container Integration
* Watch & Reload
* Log management
* Monitoring
* Module System
* Max memory reload
* Cluster Mode
* Hot reload
* Development workflow
* Startup Scripts
* Deployment workflow
* PaaS Compatible
* Keymetrics monitoring
* API

It also solves memory overuse problems, And it has an "API" logic just like FuseBox with modules.
Of course, it's a lot of work.
But I think it's worth, comparing to how much it'll bring!
Anyway, there are some good ideas to consider.

**Comment by nchanged** [comment]
### FuseBox v4 Major Upgrade

As of today, the latest major version of FuseBox `v4` is available in `fuse-box@next`. FuseBox has undergone a full re-write from scratch, learning from its mistakes in the previous versions.

There are a lot of improvements, speed and config wise.

Get started [here](https://github.com/fuse-box/fuse-box/blob/master/docs/getting-started/get-started.md)

We are still working on the documentation and polishing before the major release. We are getting very close. And we need help testing.

```bash
npm install fuse-box@next
```

Most of the issues that I am closing have been resolved, however, if you find that your issue is still relevant in `v4` don't hesitate to re-open or (better) create a new one with `v4` configuration.
