### ISSUE TITLE
Adding a option to CSSResourcesPlugin to know generated file names

### ISSUE THREAD

**Issue by zouloux** [fuse-box/fuse-box#1282]
Hi all,
We need an option in our projects on CSSResourcesPlugin to allow the JS side to know about  generated CSS resources file names (things like `_8454354234.png`).
I created a pull request to show a possible implementation of this option.
We use it already here and it's configured to create a `resources.ts` file which describe file mapping. It also can easily create a JSON file for example.

👉 https://github.com/fuse-box/fuse-box/pull/1281

I hope this is enough and i'm ready to talk about it, maybe it will be useful for somebody else !

Thanks,
Alex

**Comment by nchanged** [comment]
### FuseBox v4 Major Upgrade

As of today, the latest major version of FuseBox `v4` is available in `fuse-box@next`. FuseBox has undergone a full re-write from scratch, learning from its mistakes in the previous versions.

There are a lot of improvements, speed and config wise.

Get started [here](https://github.com/fuse-box/fuse-box/blob/master/docs/getting-started/get-started.md)

We are still working on the documentation and polishing before the major release. We are getting very close. And we need help testing.

```bash
npm install fuse-box@next
```

Most of the issues that I am closing have been resolved, however, if you find that your issue is still relevant in `v4` don't hesitate to re-open or (better) create a new one with `v4` configuration.
