### ISSUE TITLE
Importing es modules

### ISSUE THREAD

**Issue by merlinnot** [fuse-box/fuse-box#1298]
Despite a `module` field being specified in a `package.json` of a dependency, FuseBox defaults to `main`. We should default to `module` if possible for better tree shaking, do you agree?

**Comment by nchanged** [comment]
@merlinnot enable [this](https://fuse-box.org/page/configuration#usejsnext) option ;-)

**Comment by merlinnot** [comment]
Thank you, works great!

**Comment by 0xorial** [comment]
> @merlinnot enable [this](https://fuse-box.org/page/configuration#usejsnext) option ;-)

Link seems broken. Could you please update, or copy info here?

**Comment by nchanged** [comment]
useJsNext option type in the search

**Comment by bkniffler** [comment]
I can't effectively use fuse-box due to useJsNext requiring the modules field in package.json. Here is a very simple example: https://github.com/bkniffler/fuse-box-rn

Package `/node_modules/react-native-status-bar-height/index.js` for example uses es modules and only defines a `main` field. This will work nicely in react-native metro bundler, but not with fusebox.

**Comment by nchanged** [comment]
@bkniffler could you submit a separate issue with more details? I will make sure it's fixed in `v4`. And `useJsNext` will be removed, as it will be enabled by default

**Comment by bkniffler** [comment]
Okay, I opened a new issue (https://github.com/fuse-box/fuse-box/issues/1498). I figured it is not only an es-modules issue, but an issue of uncompiled dependencies.
