### ISSUE TITLE
Suggestion use terser instead of uglify-es

### ISSUE THREAD

**Issue by andrew-w-ross** [fuse-box/fuse-box#1378]
Uglify-es is [no longer maintained](https://github.com/mishoo/UglifyJS2/issues/3156#issuecomment-392943058) so change to [terser](https://github.com/fabiosantoscode/terser) instead.

**Comment by nchanged** [comment]
can you PR it please?

**Comment by andrew-w-ross** [comment]
@nchanged  I can only get to it next week, if you're ok with that sure.

**Comment by nchanged** [comment]
That would be great, I am travelling myself ATM

**Comment by nchanged** [comment]
@andrew-w-ross any updated on that? Could you make a PR? We don't want to have any outdated and/or unmaintained packages.

**Comment by andrew-w-ross** [comment]
@nchanged  I absolutely forgot about this, really sorry about that let me get something out.

**Comment by Gustorn** [comment]
I would send a PR for this, my only questions is: how do I handle the transation between `uglify-es` and `terser`:

1. Add a new plugin (`TerserPlugin`) and when uglifying in Quantum, try requiring `terser` first. If that fails, fall back to `uglify-es`. The advantage is that it does not break compatiblity.
2. Same as 1. but also delete `UglifyESPlugin` and no fallback. Needs a major version bump
3. Keep the old plugin names `UglifyESPlugin` but use `terser` in them instead. Still needs a major version bump but `fuse.js` is source-compatible with the current release

I can do any of the above. If there is a decision I'll send a PR as soon as possible since I also need the functionality ;)

**Comment by nchanged** [comment]
@Gustorn let's spit out a warning that UglifyEs is not longer supported and will be remove in the next major release. 
* Make a warning if UglifyES is used.
* Add new plugin based on UglifyES (to keep it synced)
* Updated the docs with cross references 

Be aware of that too:

https://github.com/fuse-box/fuse-box/blob/92ccfa701ad12b48e470cb5cdf18a33f4f70a51a/src/quantum/plugin/BundleWriter.ts#L64

This needs to be handled gracefully (without breaking changes)
https://github.com/fuse-box/fuse-box/blob/92ccfa701ad12b48e470cb5cdf18a33f4f70a51a/src/Utils.ts#L75-L77

https://github.com/fuse-box/fuse-box/blob/92ccfa701ad12b48e470cb5cdf18a33f4f70a51a/src/quantum/plugin/QuantumPlugin.ts#L32-L35
