### ISSUE TITLE
Dynamic require not bundled

### ISSUE THREAD

**Issue by asdftd** [fuse-box/fuse-box#1402]
So coming from webpack, I just love fuse-box.
Still one thing I struggled already is bundling mongoose. In webpack it works.

There is this section (https://github.com/Automattic/mongoose/blob/master/lib/index.js#L595):
```/*!
 * Driver dependent APIs
 */

const driver = global.MONGOOSE_DRIVER_PATH || './drivers/node-mongodb-native';

/*!
 * Connection
 */

const Connection = require(driver + '/connection');
```
As it seems the ./drivers/node-mongodb-native/connection.js file won't be bundled.

Am I missing something?

To Reproduce:

Take https://github.com/fuse-box/fuse-box-examples/tree/master/examples/simple-bundle
add mongoose (npm i -S mongoose)
add to index.js
`import mongoose from 'mongoose;'`

Thanks

**Comment by nchanged** [comment]
@asdftd I wouldn't bundle dependencies for server. Try it with `instructions("> [server.ts]")`
Dynamic require statements on the list!

**Comment by nchanged** [comment]
@asdftd you do make a valid point here. However, some dependencies cannot be bundled, e.g the ones that are compiled from sources (C++) or rely on the file system, where a bundle just breaks the structure and nothing you can do here.

In order to reduce the size, you can try [prune](https://docs.npmjs.com/cli/prune) I personally use it. 
In regards to your original question, Quantum cannot solve it (Just yet), I am constantly improving the quality of production builds, but unfortunately, at this very moment there is no partial evaluation.

If you really want to make it work, use the ReplacePlugin and replace `require(driver + '/connection');` to `require( './drivers/node-mongodb-native');`. It's a hack, I know but it will work. 

And if you like FuseBox, don't be shy and please help us ;-)

**Comment by Pencroff** [comment]
I solved this issue by aliases:
The code I wanted to bundle contained something like:
`Dialect = require('./dialects/' + (aliases[clientName] || clientName) + '/index.js');` 
This is knex lib for sql queries. It supports a few dbs, but in reality I am using just PostrgreSQL.

### Solution:
In my application I imported required data:
```typescript
import * as Knex from 'knex';
import 'knex/lib/dialects/postgres/index'; // it required to solve an issue, not for application
``` 
in context I added:
```typescript
alias: {
  './dialects/postgres/index': 'knex/lib/dialects/postgres/index',
},
 ```
How it works:
On bundling time all required logic was imported by `import 'knex/lib/dialects/postgres/index';`. In run time `require('./dialects/postgres/index')` resolved as a `require('knex/lib/dialects/postgres/index')` which is already bundled.

In other project by this trick I replaced `promise` npm package by `bluebird`  :)

**Comment by nchanged** [comment]
Closing this one for now ;-)
