### ISSUE TITLE
QuantumPlugin with replaceProcessEnv generates invalid JS for prototype methods

### ISSUE THREAD

**Issue by orourkek** [fuse-box/fuse-box#1486]
When using `QuantumPlugin` with `replaceProcessEnv: true` (which is the default), `process.env` prototype method calls are incorrectly replaced with a string representation of the function which results in invalid JS being emitted. A simple and realistic example is `process.env.hasOwnProperty(...)`. This code is detected as a `process.env` property access and will be replaced with its "value" (via `toString()`) which produces invalid JS in the output.

```js
const fooDefined = process.env.hasOwnProperty('FOO');
// is converted to:
var fooDefined = function hasOwnProperty() { [native code] }('FOO');
```

I've created a minimal repo that can be used to reproduce the issue:
https://github.com/orourkek/fuse-box-replace-process-env-bug-demo

I've already done some digging in the source code to confirm some particulars of the bug, and hope to take a crack at a PR soon.

**Comment by nchanged** [comment]
@orourkek that's right! 
Here is the code responsible
https://github.com/fuse-box/fuse-box/blob/2d71ad9c045cf20ee22015cd8a2cf8bef63a00d7/src/quantum/core/FileAbstraction.ts#L377-L392

Would be great if you helped us out!

**Comment by Zaitsev** [comment]
the same issue with `node_modules/debug/src/node.js`
with env as `EnvPlugin({ DEBUG: '*' }),`
```javascript
function save(namespaces) {
	if (namespaces) {
		process.env.DEBUG = namespaces;
	} else {
		// If you set a process.env field to null or undefined, it gets cast to the
		// string 'null' or 'undefined'. Just delete instead.
		delete process.env.DEBUG;
	}
}
```
transpiled to 
```javascript
function save(namespaces) {
    if (namespaces) {
        '*' = namespaces;
    } else {
        delete '*';
    }
}
```

**Comment by nchanged** [comment]
### FuseBox v4 Major Upgrade

As of today, the latest major version of FuseBox `v4` is available in `fuse-box@next`. FuseBox has undergone a full re-write from scratch, learning from its mistakes in the previous versions.

There are a lot of improvements, speed and config wise.

Get started [here](https://github.com/fuse-box/fuse-box/blob/master/docs/getting-started/get-started.md)

We are still working on the documentation and polishing before the major release. We are getting very close. And we need help testing.

```bash
npm install fuse-box@next
```

Most of the issues that I am closing have been resolved, however, if you find that your issue is still relevant in `v4` don't hesitate to re-open or (better) create a new one with `v4` configuration.
