### ISSUE TITLE
Source maps issues with npm packages and dynamic loaded bundles

### ISSUE THREAD

**Issue by andychiare** [fuse-box/fuse-box#1506]
Hi all,
I have a few issues with source maps in a bit complex scenario. I tried to explain the scenario in the README of this [example project](https://github.com/andychiare/fuse-box-sourcemaps-issues).
In a nutshell, I'm experiencing a lack of source maps loading and source maps misalignments.
I hope the described scenario is clear enough. Please, ask if it isn't.

**Comment by nchanged** [comment]
### FuseBox v4 Major Upgrade

As of today, the latest major version of FuseBox `v4` is available in `fuse-box@next`. FuseBox has undergone a full re-write from scratch, learning from its mistakes in the previous versions.

There are a lot of improvements, speed and config wise.

Get started [here](https://github.com/fuse-box/fuse-box/blob/master/docs/getting-started/get-started.md)

We are still working on the documentation and polishing before the major release. We are getting very close. And we need help testing.

```bash
npm install fuse-box@next
```

Most of the issues that I am closing have been resolved, however, if you find that your issue is still relevant in `v4` don't hesitate to re-open or (better) create a new one with `v4` configuration.
