### ISSUE TITLE
Wrong sourceMappingURL in css-file when using sass

### ISSUE THREAD

**Issue by jschill** [fuse-box/fuse-box#1581]
My css output file: `main.css`
My sourceMap file: `main.css.map`
My sourceMappingURL in main.css:
`/*# sourceMappingURL=main.scss.map */`

Note the reference is wrong, it says scss instead of css. Can I manually override it somehow?

Fuse-box version 3.7.1

**Comment by nchanged** [comment]
hi @jschill 
please use `v4`, docs for stylesheet are [here](https://github.com/fuse-box/fuse-box/blob/v4/docs/stylesheet.md)

A configuration sample is available [here](https://github.com/fuse-box/react-example/tree/v4) Soon we are going to have a migration guide. I will close this for now, since `v3` is no longer supported.

**Comment by jschill** [comment]
@nchanged OK, thank you.
