### ISSUE TITLE
ts:main doesn't account for paths set in tsconfig.json

### ISSUE THREAD

**Issue by squidfunk** [fuse-box/fuse-box#1599]
I'm working in a monorepo and split my code into a library-centric structure, e.g.:

```
repo/
  packages/
    1a/
    1b/
    ...
```

The `ts:main` enables me to compile all packages as `commonjs` modules but still provide the TypeScript source for better tree-shaking along the way. As those libraries may grow big and deep in hierarchy, I use the `paths` variable in `tsconfig.json`:

``` json
{
  "extends": "../../tsconfig.package.json",
  "compilerOptions": {
    "rootDir": "src",
    "baseUrl": "src",
    "outDir": "dist",
    "paths": {
      "utilities/*": ["utilities/*"]
    }
  },
  "include": [
    "src",
    "typings"
  ],
  "exclude": [
    "node_modules"
  ]
}

```

Now, when I include package `1b` in package `1a`, the defined paths are ignored as the `tsconfig` of `1b` is not respected:

```
Uncaught Package not found utilities
```

Also note that `tsconfig.json` files might be extended which is a common approach for monorepos, so the `tsconfig.json` of the package may not exist without the parent `tsconfig.json` of the mono repo. 

Is there some way to use `paths` alongside `ts:main`?

**Comment by nchanged** [comment]
@squidfunk it feels like it's a hot topic now.
Here is a new [documentation](https://github.com/fuse-box/fuse-box/blob/master/docs/monorepo.md) for a monorepo in `fuse-box@next` And here is an [example](https://github.com/fuse-box/fuse-box/tree/master/playground/monorepo) in the playground.

[fuse.ts](https://github.com/fuse-box/fuse-box/blob/master/playground/monorepo/project/fuse.ts) and and [tsconfig](https://github.com/fuse-box/fuse-box/blob/master/playground/monorepo/project/tsconfig.json) 

I will close this issue, since i've tested it myself and some users are already working with monorepo and `v4`. If you have questions, don't join Gitter!

**Comment by squidfunk** [comment]
Thanks for the quick response. I just discovered the hint for `fusebox@next` in #1277 and keep digging into the new API. BTW: FuseBox is awesome! Much better than Webpack for TypeScript!

**Comment by nchanged** [comment]
@squidfunk thanks!! nice to hear that! Please do read the new documentation carefully. Especially this [part](https://github.com/fuse-box/fuse-box/blob/master/docs/monorepo.md)

If you have questions, join Gitter, we're happy to help. There 2 active users who work with monorepo already with `@next`
