### ISSUE TITLE
alias resolution does not match typescript 

### ISSUE THREAD

**Issue by jeremy-coleman** [fuse-box/fuse-box#1625]
(this is a breaking change from v3 behavior)
the resolution depth seems to be limited to 1 folder in, whereas typescript's is absolute. 

before, if i set baseUrl in tsconfig to ./src , any folder would get resolved no problem. This behavior makes aliasing super easy, for example:
```bash
-src
--@monorepo
---common
----models
----services
---ui
----components
---server
```
something like this, doing:
```js
import x from '@monorepo/common/services'
```
would always work, but now it seems the depth is limited to 1, so only @monorepo/common will resolve correctly. any clue on what caused the change?

**Comment by nchanged** [comment]
@jeremy-coleman here you go

First example - [a full fledged lerna repository](https://github.com/squidfunk/fusebox-lerna-multi-monorepo/)

Second example a simple [monorepo](https://github.com/fuse-box/fuse-box/tree/master/playground/monorepo)

A very [comprehensive guide](https://github.com/fuse-box/fuse-box/blob/master/docs/monorepo.md) how to set it up with `tsconfig.json`


I am 100% that's more than enough for you to figure it out. Since a lot of users are already using it. There are no breaking changes. There is a massive upgrade. v4 supports typescript `paths` 100%

**Comment by vegarringdal** [comment]
@jeremy-coleman 
I have my own little weird mono repo for typescript/fusebox 4 here.
https://github.com/simple-html/simple-html

I didnt want to use lerna, so I made simple scripts to build all packages and sync the package versions. + publish.

If I do edits in any of the pcakes when I run any of the development sample fusebox update and typecheck :-)

Im sure there are some who would hate the way I do it, but for me it works very good.

**Comment by jeremy-coleman** [comment]
removing the tsConfig entry in my fuse-box config fixed the problem. (just removed tsConfig: {allowJs: true}).
