### ISSUE TITLE
Templating languages

### ISSUE THREAD

**Issue by tonimain** [fuse-box/fuse-box#163]
Is there a guide how to integrate twig.js or handlebars into fusebox?

**Comment by devmondo** [comment]
@tonimain thanks for the input, i think we need to improve the Docs on that :) hang in there

**Comment by tonimain** [comment]
COuld you give some short advise? It's important we're starting dev next week and need this to implement. Don't want to use webpack anymore... :p

**Comment by nchanged** [comment]
I think @DoumanAsh has planned something terrific there.

**Comment by tonimain** [comment]
Would be great if @DoumanAsh could contribute a small workaround here :) would kiss your feets

**Comment by DoumanAsh** [comment]
Well, i only plan to implement for my needs Stylus and Jade/Pug static compilation plugins.
I'm still studying plugin API, but first of what kind of integration do you need?

If you would like to parse your templates into JS code, then you could use this plugin as reference https://github.com/fuse-box/fuse-box/blob/master/src/plugins/StylusPlugin.ts

If you prefer, as i am, static compilation then we could work together on it :) you can go over [gitter](https://gitter.im/fusebox-bundler/Lobby) so that we could talk real time :)

**Comment by tonimain** [comment]
@DoumanAsh we talk later in gitter thanks for your advice :) and yep that's the way compiling hbs to  html and so on

**Comment by tonimain** [comment]
i think we could integrate assemble.io for the heavy lifting of template assembling. Will prevent a lot of headaches around this topic

**Comment by DoumanAsh** [comment]
You should note that personally i feel that stuff like that should be mostly as part of external plugins.

**Comment by tonimain** [comment]
Yep i think so too

**Comment by devmondo** [comment]
i think too :)

**Comment by devmondo** [comment]
as mentioned above, this should be part of an external plugin.

by the way, check our new Sparky task runner, you can manipulate files with any templating engine you want.

we will close it, but feel free to open it otherwise :)
