### ISSUE TITLE
Renaming a file extension requires clearing cache to fix

### ISSUE THREAD

**Issue by samdesota** [fuse-box/fuse-box#1630]
With fusebox 4.0.0, renaming a file extension from .js -> .ts requires clearing cache, otherwise I recieve a module missing error until I delete "node_modules/.fusebox"

**Comment by nchanged** [comment]
Thanks @mrapogee I will take a look

**Comment by Coglite** [comment]
i also suggest instead of ignoring node modules on the watch options, set it to only watch the fusebox homeDir as the default , it should prevent excessively watching stuff. 

Also, the native fs.watch is pretty good these days. You could just call fs.watch on fusebox's home dir(the dir, not files) and never have to worry about cache invalidation, it will always give you a signal when anything in the dir changes.

**Comment by charsleysa** [comment]
Closed due to inactivity.
