### ISSUE TITLE
v4 Bundle output, webIndex irritations

### ISSUE THREAD

**Issue by nolawnchairs** [fuse-box/fuse-box#1694]
^4.0.0-next.156

I really would like to keep using version 3, but because of #1522 , and the fact this issue was not (and presumably won't be) patched, I feel strong-armed into using v4.

Very frustrated because apparently support is being dropped for v3, yet there is no usable documentation on v4 yet. What links I did find in various issue threads were 404.

I've created a bundle for the electron renderer like this:
```
{
      output: `${generatePath}/renderer.js`,
      target: 'electron',
      homeDir: './src/renderer',
      entry: 'renderer.tsx',
      useSingleBundle: true,
      dependencies: { include: ['tslib'] },
      logging: { level: 'succinct' },
      webIndex: {
        publicPath: './',
        template: `${assetsPath}/index.html`
      },
      cache: {
        enabled: false,
        root: '.cache/renderer'
      },
      env,
      devServer: {
        httpServer: false,
        hmrServer: { port: devPort }
      }
```
When I run, I get this strange directory:
```
- output
    - main.js [dir, not a file]
        - 4ab3d22e_app.js
        - 4ab3d22e_app.js.map
    - renderer.js [dir, not a file]
        - 3187aed4_app
        - 3187aed4_app.map
        - index.html
```
What I want is more like this:
```
- output
    - main.js
    - renderer.js
    - index.html
```
And what about the webIndex options?

```
export interface IWebIndexConfig {
    enabled?: boolean;
    target?: string;
    template?: string; // is this a path relative to `homeDir`, project root? absolute?
    distFileName?: string;
    publicPath?: string; // what is this?
    embedIndexedBundles?: boolean;
}
```
I don't want this hashes, I don't want separate directories for renderer/main, so the names of the scripts can be referenced properly in the index.html file. I don't want an automatically generated index.html file either. Basically, I'd like it to generate bundles in the same way v3 did.

If this is not possible with v4, and you're not going to patch the issue stated above in v3, I'll probably have to use Webpack or Rollup, because I really dislike opinionated software :)

Ta.

**Comment by nchanged** [comment]
@mweiczorek I can understand that I can be frustrated. FuseBox takes over the bundle configuration in order to achieve maximum speed.

This is open-source, you're free to choose whatever you like. Saying "Do this unless I get back to WebPack" sounds rude and inappropriate here. Seriously. 

Your `output` should always be a folder since FuseBox needs to know where to put assets and source maps. I hope that's clear]

So `output : "./renderer"`

Those hashes are added to avoid name collisions. 

I understand your point here and that you want to take full control over the bundles. I could technically introduce a configuration field that would make it possible. 

I am not going to patch v3 version (it's no longer maintained) As for v4 we can make this happen. 

```js
output : {
 bundle : "renderer.js"
}
```

**Comment by SephReed** [comment]
Hey.  I've been working with the docs quite a bit lately.  You can find them here:

https://github.com/fuse-box/fuse-box/tree/seph-docs/docs

@nchanged Adding the configuration seems like a good idea.  Smart defaults and in depth configuration options are usually a good combo.

**Comment by mweiczorek** [comment]
Sorry if I came off rude, it wasn't my intention - just loads of frustration. I apologize.

How I used v3 was that I had an /output directory in my project root (this is an Electron application) with two html files (index.html that holds the application's renderer code, and static splash.html). Inside /output is a directory I name /assets, which is where the generated main.js and renderer.js (as well as generated CSS from Sass) go. I set the v3 bundler to output the main and renderer code into their respective files in /assets, and the /output/index.html file references the renderer.js file.

It would be nice if I could generate the bundle (as you stated) without the hashes, because I have no need for them (unless there is something internal that relies on the hashes).

Don't get me wrong, I'm happy to use v4 if I had documentation to reference (thanks @SephReed ), it worked much quicker, but the problems above kept the JS from being loaded because I could not figure out the bundles (could not find documentation), If there could be a definitive filename for the generated .js files, it should work smoothly.

Another question - I noticed that unlike older versions, changes to the main bundle refreshes the application - does this kill the main process, or hot-reload it? I ask because I have lots of listeners in the main process (like Electron's IPC and file watchers) that I never bother to close because it's not necessary since they die with the main process... but if the main process is being hot-swapped, I would need to properly close them as I do renderer listeners.

Thanks!

**Comment by nchanged** [comment]
@mweiczorek the main process is being restarted indeed. If you have better options - please suggest.  
I will introduce a similar API

```
output : {
 bundle : "renderer.js"
}
```

So basically you'd configure the bundle output yourself. In this case, we can lose `useSingleBundle`

**Comment by nchanged** [comment]
Relevant please join the discussion 
https://github.com/fuse-box/fuse-box/issues/1756

**Comment by charsleysa** [comment]
Closed due to inactivity.
