### ISSUE TITLE
[v4] HTML template img tags with src attribute ignored

### ISSUE THREAD

**Issue by Teoxoy** [fuse-box/fuse-box#1718]
I have an HTML template that contains a few `img` tags with a relative `src` path set and they are being ignored. I have tried to use the copy plugin to copy those to the dist folder but they are not linked to the output HTML file in any way (i.e. the paths remain the same - no hashes were added).

Is there a way for `fuse-box` to discover those files, add a hash to them in the html file and then copy them to dist?

Forgot to mention, favicons are also ignored.

Example HTML template:
```html
<!DOCTYPE html>
<html>
    <head>
        <title>Example</title>
        <link rel="icon" href="assets/favicon.png" />
        $css
    </head>
    <body>
        <img src="assets/just_an_image.png" />
        <img src="assets/some_graphics.svg" />
        $bundles
    </body>
</html>
```

**Comment by nchanged** [comment]
@Teoxoy that's a great feature to have! It's not implemented atm, do you think you can take a look at it? We're currently busy with production builds in alpha, so that isn't a priority ATM. But if you decide to help I can guide you there

**Comment by Teoxoy** [comment]
Sure, I can give it a shot.

How should it work?
Seamless i.e. the bundler will find those automatically.
Or the user will have to specify a tag like the already implemented ones (`$css`, `$bundles`) - for example: `<img src="$import('assets/just_an_image.png')" />`

**Comment by nchanged** [comment]
The logic of webIndex is located [here](https://github.com/fuse-box/fuse-box/blob/master/src/web-index/webIndex.ts)
Currently, it's very primitive and doesn't really parse HTML. If we find a very fast and efficient parser, we could make it happen. (But not cheerio)

**Comment by Teoxoy** [comment]
So you think the seamless way is the way to go?
The 2nd approach would not require an html parser.

**Comment by nchanged** [comment]
the regex function approach seems to be a lesser evil ;-)

**Comment by Teoxoy** [comment]
I think so too :)
It's also more flexible - it can be used anywhere in the template.

**Comment by bergkvist** [comment]
@nchanged Why is cheerio not a viable alternative? Is it too slow?

**Comment by Teoxoy** [comment]
IMO, cheerio with htmlparser2 should be fast enough. The question is more or less about the API. Should we explicitly import or make it seamless and let the bundler take care of it? Both approaches have their pros and cons.

**Comment by nchanged** [comment]
`cheerio` is a very heavy dependency, it's slow and memory leaking. 99% of their API we don't really need. We need something very very simple to parse the attributes.

**Comment by patrickmichalina** [comment]
I was thinking about re-writting the web index plugin to support a broad set of use-cases. @nchanged have an issue with that?

**Comment by Teoxoy** [comment]
@patrickmichalina - that would be great.
Should I still put up a PR to fix this issue then?
Also, what would be the ETA for the web index improvements?

**Comment by patrickmichalina** [comment]
@Teoxoy realistically the end of January. So you should definitely make a PR for what you need before then. I commented here because I have run into similar limitations for WebIndex and have written a custom plugin in a project to solve it. It uses JSDOM - which is way overkill for this but at the time was a quick and easy solution. I think 95% of use-cases can be achieved without any dependencies, just some solid functional programming and maybe some Regex magic.

**Comment by nchanged** [comment]
@patrickmichalina @Teoxoy I am down for re-writing the webIndex, besides the implementation is really simple there, I've implemented it in less than an hour. 

So we need:

## Simple HTML parser
Find a simplistic parser (or write our own) that would efficiently parse attributes and re-write the resources. We have the functions for resolving resources,  it's a part of the core - and all configurable.

I wonder if we just get an XML tokenizer - zero deps lib for that. (It actually will work just fine)

We should really keep it simple since we have `pluginConsolidate` that adds an extra layer of complexity by parsing the HTML again. 

## Support functions

Since a user might want to have some other HTML engine, we'd need to account for that too:
```
html
   body
     style link="$import(}"
```

So having internal independent functions would help too.

**Comment by bergkvist** [comment]
This seems to be what the parcel bundler is using from looking through their code:
https://github.com/posthtml/posthtml

Allowing a html-file to be used as an entrypoint would also be quite nice (possibly making the fusebox-configuration even simpler!)

**Comment by bergkvist** [comment]
Basic example of transforming html with posthtml in node.js:
```js
const posthtml = require('posthtml')

function replaceScripts (tree) {
  for (const i in tree) {
    if (typeof tree[i] !== 'object') continue
    if (tree[i].content) replaceScripts(tree[i].content)
    if (tree[i].tag === 'script') {
      const src = tree[i].attrs.src
      tree[i] = `script with src=${src} used to be here`
    }
  }
}

const parsed = posthtml().process(
`<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
    <link rel="stylesheet" href="style.css"></link>
  </head>
  <body>
    <script src="index.js"></script>
  </body>
</html>`, 
{ sync: true }
)    

replaceScripts(parsed.tree)
console.log(parsed.html)
```

### Output
```html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
    <link rel="stylesheet" href="style.css">
  </head>
  <body>
    script with src=index.js used to be here
  </body>
</html>
```
