### ISSUE TITLE
v4 feature request: support lerna packages and yarn workspaces

### ISSUE THREAD

**Issue by martaver** [fuse-box/fuse-box#1793]
So the new approach to using typescript's paths property for monorepo works nicely.

The truth is, though, that for a real world monorepo setup, I wouldn't use typescript paths at all. My monorepos are set up with lerna and yarn workspaces, which symlinks the source code from child package to a parent's node_modules directory. The parent references the child package in their package.json as 'just another dependency'.

This allows each dependency to be treated as an independent package and has many benefits, including being able to automatically calculate change logs and semver and navigate dependency trees. In fact, yarn workspaces already keeps the dependency tree for us.

The downside to this, is that to fuse-box, the child packages look like 'just another dependency', and fuse-box can't tell the difference between our monorepo packages and those installed in node_modules through npm.

The result of this is that fuse-box builds everything correctly, but we get no watch or hmr on our local monorepo dependencies.

Ideally, we would update usages of ´resolver.ts´ to allow for yarn workspace and lerna workspace information to be read, so that we can detect when dependencies are local, and treat them the same as though they were included in tsconfig paths.

**Comment by Martaver** [comment]
To clarify, if I combine yarn workspaces with paths in tsconfig, everything seems to work fine.

**Comment by mekwall** [comment]
Is this with yarn v1 or v2? Afaik paths in tsconfig doesn't work with Yarn v2.

**Comment by Martaver** [comment]
Hmm, I'm still on yarn 1... I'm not familiar with yarn 2 and how it might change the monorepo game.

Basically, I think yarn workspaces are the correct way to do deps between packages in monorepos. It opens up lots of cool stuff like automatic dependency walking when generating semver from commits etc.

The thing is that fuse-box won't listen to changes inside packages linked via yarn workspaces because they just look like any other node_module. So I have to add paths in tsconfig as well to get fuse-box to work.

The drawback then, is that I no longer actually need to add the referred package as a dependency to my code. I want to maintain that need for explicit declaration of deps, so that semver can be calculated, and if we need to split up the monorepo, any package can be pulled out and replaced with npm or verdaccio on a whim.

**Comment by Martaver** [comment]
To achieve this, basically all fuse-box would have to do is look up the workspaces properties for lerna/yarn from package.json or lerna.json, then iterate the package names from each of them - and it'd have a list of packages that it should watch when encountered. Seems like small potatoes. I'd take a look myself if I could get some guidance on where to start.

**Comment by nchanged** [comment]
@Martaver sounds like a good idea. `baseUrl` already does that btw. Let's have a chat about it on slack.

**Comment by warrenfalk** [comment]
I've been working a lot on this.  I have a branch where I think I have these problems resolved, and I'm just testing this now.  I thought I'd give some information on how some of this is solved.

> My monorepos are set up with lerna and yarn workspaces, which symlinks the source code from child package to a parent's node_modules directory. The parent references the child package in their package.json as 'just another dependency'.

The biggest reason that this wasn't working before was fuse-box's module resolution not looking above the app root.  With #1820 (merged in `@next`), this part is resolved.  Or almost...

>The thing is that fuse-box won't listen to changes inside packages linked via yarn workspaces because they just look like any other node_module

Yes and no... since these are symlinks in those workspaces strategies.  And since node always dereferences symlinks, node does not actually see their paths as containing a `node_modules`.  So we just need to make fuse-box dereference these like node does.  But currently it does not - that's the "almost" part.  I have a fix for that coming.

This solves the watcher issue for me because even though workspaces are imported "through" `node_modules`, fuse-box can tell they are not actually "in" `node_modules` and they can trigger the watch.

> This allows each dependency to be treated as an independent package and has many benefits, including being able to automatically calculate change logs and semver and navigate dependency trees. In fact, yarn workspaces already keeps the dependency tree for us.

Yes, this is one of the main goals, but it isn't enough of its own.  If these were simple JavaScript with no transformation step, then this would be enough.  But with TypeScript you'll run into all kinds of compatibility issues because conventional tools expect packages to export `.js` not `.ts`.  Things like the `"main"` entry point, or separating `src` from `dist` cause problems.  E.g. `dist/file.js` is expected to be built and exist and so you're expected to `import x from "greatpkg/dist/file"` not `import x from "greatpkg/src/file"`.

TypeScript paths can sort of rescue you here by rewriting some of these things, but it runs into its own problems.

So TypeScript's own solution to this problem is to have `tsconfig.json` files reference other `tsconfig.json` files.  That's described here: https://www.typescriptlang.org/docs/handbook/project-references.html.

When you `import` `greatpkg/dist/file` it uses Node.js's resolution algorithm to find the `greatpkg` part.  And then it uses the `tsconfig.json` to translate the `dist/file` part into `src/file.ts`.

Furthermore, `tsc --build` from the top-level package will automatically incrementally build child packages.  And Visual Studio Code also knows about this and so it also doesn't complain about `dist` not existing.

You can see an example of a monorepo setup using tsconfig references here: https://github.com/andrewthauer/ts-monorepo .  But this one is using Webpack.  I want to do that with fuse-box.  I have this working in my branch right now.

> The drawback then, is that I no longer actually need to add the referred package as a dependency to my code. I want to maintain that need for explicit declaration of deps

Yes, this!  This is a big problem.

Unfortunately, though, what you'll find is that fuse-box isn't causing this problem and in fact can't do much about it.  This is a fundamental flaw in how Node.js's `node_modules` resolution has always worked, combined with how those workspace strategies are designed to use it.

Specifically, Node.js's module resolution algorithm _does not look at declarations (package.json) at all_!  It only looks at what is in `node_modules`.  So when the workspaces hoist all "declared" dependencies into a shared `node_modules` it makes it so that as soon as _one_ workspace "declares" a dependency, _all_ workspaces can "import" it.  This flaw in Node.js's resolution algorithm is one of the worst flaws of Node.js.

Yarn 2 solves this by replacing `node_modules` entirely with Plug'n'Play (PnP) (which is just genius and awesome, btw).  PnP will not let you import a dependency you have not declared in your package.json.  The great news is that fuse-box does support PnP in `@next`.  But PnP is still hard to recommend using at this moment now because TypeScript still doesn't support it natively and requires some hacks to work.  I'm using it, though, and have made sure that it works with my ts references changes in fuse-box.  Hopefully the TypeScript team adds support soon.

**Comment by Martaver** [comment]
Appreciate the detailed break-down! It's really useful to hear how other people are tackling this.

PnP is probably the future and with a bit more adoption, it should be a use case we can safely pour time and energy into. Personally, I haven't played with it yet, and I don't know whether it's going to actually make life easier for the monorepo scene... 

With regards to the non-PnP, though, I don't understand why we can't just update resolver.ts to read yarn or lerna workspaces... yarn is already doing all the hard work for us. 

I don't think it's wise to make fuse-box do any special treatment of symlinks. That sounds like it's opening pandora's box.

**Comment by warrenfalk** [comment]
The reason workspaces work in the node ecosystem isn't because everyone went out and added support, it's because workspaces were designed to take advantage of the way the node ecosystem already works.

Node doesn't know anything about workspaces, and neither does much of anything else.  The whole point is that they don't have to.  They just have to keep doing what they were doing.  To make workspaces work, you just have to ask "how is everyone else doing it" and the answer is "they just do what node does" because that is what the workspaces expect - it's how they were designed.

> I don't think it's wise to make fuse-box do any special treatment of symlinks. That sounds like it's opening pandora's box.

Exactly.  Node and everything else dereferences symlinks.  Fuse-box doesn't.  So fuse-box is already doing special treatment.  And this special treatment actually breaks things<sup>1</sup>.  And so I am agreeing with you here and saying that fuse-box should start dereferencing symlinks like everyone else.

> With regards to the non-PnP, though, I don't understand why we can't just update resolver.ts to read yarn or lerna workspaces from their config files...

Because the config files are instructions for the _installer_ not the _resolver_.  Resolvers don't read workspaces from the config file.

>  ...yarn is already doing all the hard work for us.

Exactly, yarn is already doing all of the hard work.  That's why resolvers don't read workspaces from their config files.  The "hard work" that yarn does is to set up node_modules for the resolvers so that they can just work like they always have worked.  Resolvers don't need to know anything about workspaces.  They just have to read node_modules like everyone else.

The "like everyone else" part is important.  This is what fuse-box was not doing before #1820 and why it didn't work with monorepos.  To do it "like everyone else" here just means "like node does it" because they all copy node.

So it isn't that we can't update resolver.ts to read yarn or lerna workspaces.  It's that it doesn't help anything.  There's no new information to be found in the workspace config that is useful for a _resolver_.

___
<sup>1</sup> Not dereferencing makes local things look non-local because it leaves "node_modules" in the path.  Making things look non-local breaks typescript project references and also makes fuse-box's watcher ignore them.

**Comment by warrenfalk** [comment]
I should clarify that I'm not saying that fuse-box shouldn't know anything about workspaces.  Just the resolver shouldn't need to.  I would like to see fuse-box be zero config as much as possible, and this means that if it could detect a workspace, it could set up somethings automatically that today you have to manually reconfigure (such as the watcher, for example).  So workspace info isn't useless... it just isn't a resolver thing.

**Comment by Martaver** [comment]
So essentially what you're saying is that fuse-box should watch those folders anyway, because if it dereferences those symlinks it will see that they're not actually in node_modules (by inspecting their path), and start to watch them?

So then in the case of typescript paths, TS is letting our folders look like node_modules, but they don't exist in node_modules. Fuse-box fails at trying to resolve them, which is why it needs the information about paths from tsconfig.

This all makes perfect sense.

I think one benefit that project references + tsc has over other configurations is that each 'project' can have its own tsconfig. However I'm pretty sure fuse-box reads only a single, root tsconfig. To 'perfect' the monorepo scenario, we would really need fuse-box to handle nested tsconfigs. What do you think? Pinging @nchanged too...

**Comment by Martaver** [comment]
I think that's a great solution by the way!

**Comment by nchanged** [comment]
@Martaver fuse isn't just reading one tsconfig, if a package contains one and it points to a typescript source it will respect the paths defined, However it won't try too hard to find the config, the resolver just checks a tsconfig next to the package.json file

I was hoping we could improve on that without perf losses

**Comment by Martaver** [comment]
You could check the package.json for entries and also check for tsconfigs in the folders between the entry point back up to the root.

**Comment by charsleysa** [comment]
Closed due to inactivity.
