### ISSUE TITLE
HMR doesn't correctly restart application (4.0.0-next.400)

### ISSUE THREAD

**Issue by martaver** [fuse-box/fuse-box#1848]
Between 4.0.0-next.165 and next.400, something has broken HMR. Code that worked previously now fails demonstrated in repro: https://github.com/Martaver/react-example

Warnings and errors suggest that the react app is not fully destroyed prior to the new app context initialising.

You can see the effects when triggering an HMR update, and observing console in chrome. A second HMR update will restart the app correctly (because the last update broke it). Subsequent updates will break and restart alternately.

**Comment by charsleysa** [comment]
@nchanged looked into this, it appears to be that even though fusebox destroys it's references to the modules, there are HTML elements with listeners with references that keep those modules alive in memory.

Solution is to either do full page reload, or create a hook system so that the HMR system can be extended for specific use cases (e.g. for react, it removes all the HTML elements that were added by the app).

**Comment by Martaver** [comment]
@charsleysa that doesn't sound right... next.165 worked fine without needing any special attention to html elements and their references.

**Comment by charsleysa** [comment]
Closed due to inactivity.
