### ISSUE TITLE
HMR seems to have problems connecting to FuseBox via HTTPS

### ISSUE THREAD

**Issue by nchanged** [fuse-box/fuse-box#208]
subj

**Comment by wearevilla** [comment]
It looks like something to do with websockets and this may be the answer here:
http://stackoverflow.com/questions/30902547/websocket-ssl-connection

I dont know exactly where to apply that fix within fuse-box though... 

I hope that helps! :)

**Comment by nchanged** [comment]
Thanks!

It's this [file](https://github.com/fuse-box/fuse-box/blob/master/src/modules/fusebox-websocket/index.ts#L11) and it gets compiled into `modules/` folder!

**Comment by wearevilla** [comment]
hmmm I updated the following line as per the Stack Overflow suggestion: 
this.client = new WebSocket(this.url_, {rejectUnauthorized: false}_);

Doesnt seem to do the trick though... :(

**Comment by nchanged** [comment]
I just leave it here 
https://github.com/fuse-box/fuse-box/pull/209

**Comment by nchanged** [comment]
Are you using localhost?

**Comment by wearevilla** [comment]
@nchanged yes im using localhost

**Comment by wearevilla** [comment]
It looks like the fact that im using localhost and a self signed cert _is_ why websocket is rejecting... 
http://stackoverflow.com/questions/30902547/websocket-ssl-connection

**Comment by basarat** [comment]
Possible suggestion just connect with `ws` (instead of `wss`) irrespective of the protocol : http://stackoverflow.com/a/23404161/390330 :rose:

**Comment by nchanged** [comment]
Thanks! Then we need to pass that string as an option to devServer

**Comment by nchanged** [comment]
```
app.devServer(">index.ts", {
    socketURI: "wss://anythingyoulike"
});
```

**Comment by wearevilla** [comment]
Hi @nchanged Thanks for all the hard work! 

Unfortunately, HMR still isnt working with this configuration. I am still getting the following error:
_failed: Connection closed before receiving a handshake response_

Here is my setup:

FUSEBOX.JS:
...
devServer('>app.jsx', {
    port: 4446,
    httpServer: false,
    socketURI: "wss://localhost:3446"
});

SERVER.JS
...
var httpsServer = https.createServer(credentials, server);

httpsServer.listen(3446);

console.log("listening on 3446")

-- 

I tried fiddling with the port numbers as well to no avail... 

Also, I noticed there was some talk about just having an HTTPS: TRUE option. Is that still on the table? I feel like that would allow us to use the fusebox devserver instead of tinkering with a separate express.js setup, and hopefully it would just set the proper sockets configuration. 

Also, just FYI, this is important for me because I am developing apps that rely strongly on the Google Maps API and the html5 geolocation stuff – and Safari blocks that stuff if the request isnt coming over https, which makes it hard for multi-browser compatibility checks locally. 

Thanks again for all your help!! You guys are awesome and fusebox is the bees knees! :)

**Comment by wearevilla** [comment]
Also, the error above was from chromes console. Here is the error coming from the safari console, in case it helps:
_WebSocket network error: OSStatus Error -9807: Invalid certificate chain_

**Comment by nchanged** [comment]
Well, it's related to your HTTPS setup. Fusebox just trying to connect ;-)

**Comment by wearevilla** [comment]
hi @nchanged thanks for the quick response, but I dont fully understand what I should do to fix it...

**Comment by devmondo** [comment]
@wearevilla maybe you need to set up your SSL certificate correctly on server ?

**Comment by wearevilla** [comment]
Hi @devmondo 

Well, the problem isnt on the server. Everything works fine on the server... 

The problem is on localhost using a self-signed certificate – which is why i originally referenced this article: http://stackoverflow.com/questions/30902547/websocket-ssl-connection 

It seems like they were experiencing the same problems using websockets locally with https...

I hope that helps!

**Comment by devmondo** [comment]
@nchanged ?

**Comment by nchanged** [comment]
@wearevilla what would you want to have? Be able to pass properties to the client?

**Comment by wearevilla** [comment]
@nchanged well it seems, if the [stackoverflow](http://stackoverflow.com/questions/30902547/websocket-ssl-connection) article above is correct, then just the ability to add {rejectUnauthorized: false} to the websockets configuration might be all we need...

The best scenario though, in my eyes, would be an HTTPS:TRUE flag added to the fusebox devserver options. Of course the user would then be responsible for [generating the cert.pem and key.pem files](http://stackoverflow.com/questions/10175812/how-to-create-a-self-signed-certificate-with-openssl) and putting them in an 'ssl' folder inside the root project directory. (I would be more than happy to help update the documentation on that 😄 )

I imagine that would then set the express settings to use https, look for the cert.pem and key.pem files in the ssl folder, and would utilize the corresponding websockets configuration to support that. 

It seems to me a logical way to go, unless I am missing something... Let me know if I am! and thanks again! you guys are killing it! :)

**Comment by wearevilla** [comment]
@nchanged @devmondo hey guys! just checking on the status of this. Thanks! :)
