### ISSUE TITLE
Handle original vendor sourcemaps

### ISSUE THREAD

**Issue by stoffeastrom** [fuse-box/fuse-box#348]
Try to match the `sourceMappingUrl`
If it's inline source just use it
Else parse the map and try to find the sources and add them
Fallback to Fuse own source map generation

For reference [this](https://github.com/webpack-contrib/source-map-loader/blob/master/index.js) is how webpack handles it.

**Comment by Shepless** [comment]
@devmondo @nchanged v3 roadmap?

**Comment by nchanged** [comment]
I think we should polish source maps, right

**Comment by nchanged** [comment]
### FuseBox v4 Major Upgrade

As of today, the latest major version of FuseBox `v4` is available in `fuse-box@next`. FuseBox has undergone a full re-write from scratch, learning from its mistakes in the previous versions.

There are a lot of improvements, speed and config wise.

Get started [here](https://github.com/fuse-box/fuse-box/blob/master/docs/getting-started/get-started.md)

We are still working on the documentation and polishing before the major release. We are getting very close. And we need help testing.

```bash
npm install fuse-box@next
```

Most of the issues that I am closing have been resolved, however, if you find that your issue is still relevant in `v4` don't hesitate to re-open or (better) create a new one with `v4` configuration.
