### ISSUE TITLE
support chainable creation

### ISSUE THREAD

**Issue by aretecode** [fuse-box/fuse-box#365]
example:
```js
fuse
.homeDir('./')
.pkg('eh')
.globals({eh: '*'})
.debug()
.log()

.plugins()
  .json()
  .babel()
  .sourceMaps()
    .set('vendors', false)
    .set('project', true)
  .html({default: true})

.env()
  .on('production')
  .define('process.env.NODE_ENV', 'production') 
  .plugins()
    .uglify()
    .sourceMaps()
      .set('project', false)

.startBundle('./dist/noflo.js')
.excludeDeps() 
.execute("src/lib/NoFlo.coffee")
.exclude('fs')
.include('process')
.noApi()
.cache(true)
.target('node')
.outFile('./dist/out.js')
.finishBundle()

.bundle()
.devServer()
```

## presets
`.presets('verbose-router')` or `.presets('inferno')` or  just as a normal property on the config without chaining `presets: 'react',`

https://github.com/mozilla-neutrino/webpack-chain

## current 
```js
fuse
  .cache()
  .log()
  .debug()
  .package('canadaEh')
  .globals({canadaEh: '*'})
  .target('node')
  .homeDir('./')
  .sourceMaps().vendor(true).project(true)

  .alias.from({
    'igloo': '~/igloo',
    'moose': '~/moose',
    'babel-utils': 'babel/dist/something/here/utils',
    'faraway': '~/somewhere/far/away/',
  })
  .shim.from({
    'react-native-web': {exports: 'require(\'react-native\')'},
  })
  .autoImport.use({
    Inferno: 'inferno',
  })

  .instruct()
    .entry('eh')
      .noDeps()
      .noCache()
      .execute('./eh')
      .exclude('dis')
      .include(['path', 'fs'])
      .add('eh')
    .entry('canada')
      .cache()
      .noApi()
      .vendor()
      .execute('/src/eh.js')
      .add('webworkerfile.js')
      .exclude('fs')
  .finish()

  .plugins
    .plugin('json')
    .plugin('html').use({default: true})
    .plugin('babel').from({
      'sourceMaps': true,
      'presets': [['env', {
        'targets': {
          'chrome': 56,
        },
      }]],
      'plugins': [
        'transform-react-jsx',
        'transform-object-rest-spread',
        'transform-decorators-legacy',
        'transform-class-properties',
        'add-module-exports',
      ],
    })

    .ops.bundle()
```

**Comment by leon-andria** [comment]
I'm really confuse here, it looks like having the config but fully code. 
For me, this is too much hard to many in long term, but it's not only that, also about the documentation.
People will be confused about "What is the best practices ?" Configuration or Javascript like ?
It's really a question of taste, but the main question is how can we make people feel confortable that FuseBox is easy to use ?
The fact is that, people are lazy to read doc, and you guys can confirm that with all the questions you get on the gitter. I would say that it's sad but the human nature is that 👎 

Having a good API from FuseBox is important but putting all concepts in the same basket, it's not right.

I see this request more personal use and can be an advanced mode of FuseBox that is outside of FuseBox.

My personal taste is more configuration based à la MSBuild idea because the trends today changes to DevOps 🥇 To get some inspiration https://www.finalbuilder.com/finalBuilder

A configuration is easy to understand and can be reusable. Sure, there are many way to implement such things.

Just to share my opinion that I'm not a fan on this suggestion but open for discussion.
Writing code is easy, making it simple to use and adopted is harder.

**Comment by nchanged** [comment]
Closing this one for now.
