### ISSUE TITLE
Arithmetics discussion! Attention Wanted!

### ISSUE THREAD

**Issue by nchanged** [fuse-box/fuse-box#382]
As we are moving closer to `1.4.1`, We would like to propose "some" changes, that would involve #170  (i remember the number by heart - @vegarringdal )

Arithmetics should represent a low-level `fuselang`, that would allow people to build solutions on top of it, like fluent APIs e.t.c.

## Plugin shortcuts
All FuseBox plugins will be included by default (`html`, `json`, `css`, `sass`) so in most user cases you would skip this step. It should make it very appealing, as nothing has to be imported.

```js
FuseBox.init(/* shared config */)
 .plugins({
    "babel1" : BabelPlugin(/* heavy json here*/),
    "babel2" : BabelPlugin(/* heavy json here*/)
}).exec(/* string below */)
```

## FuseLang
```
:devServer
// Application bundle
>> app.js
   > [index.ts] + somethingCool
   :import = cool-lib-before-execution
   :watch = *.ts
   :pkg = myLib
   :main = index.js
   :plugins = html, json, babel1

   :register somethingCool = (
         > modules/mylib/index.js
            + **/*.html 
            + /**/*.js
            + /**/*.css
      plugins : babel2
    )

>> vendor.js
   > ~ index.ts 
    
```

*  Comments are allows
*  Two bundles are created
*  app.js (without deps) + custom library called `somethingCool`
*  vendor.js - vendor bundle (everything that's related to index.ts 

| Symbols  | Desc |
| ------------- | ------------- |
| `>>`  | Output file name  |
| `:option` | options (for example devServer) = true |
| `:option = value` | options (for example cache =false |
| `// ` | Comment till the line break |

Again, that's a low level `fuselang`.

**Comment by vegarringdal** [comment]
@nchanged 

* How do I define the entry here ?
    * Important this can work as a module, so we dont force execution on load if not needed)
```
+ somethingCool = (
         > node_modules/somethingCool/dist/commonjs
            + **/*.html 
            + /**/*.js
            + /**/*.css
     )
```
* we can use typescript too '? incase you are developing a module/ modules ?
* we can use [**/*ts] so it does not add external modules ?
* what about sourcemaps, very important if you want to use the src while developing a module/modules, (and plugins with aurelia)

**Comment by nchanged** [comment]
@vegarringdal 
* Typescript yes
* Yes (like is is now) -> [**/*.ts]
* We will have as set of options `:sourcemaps=true`
* FuseBox.init will contain a list of plugins, I think we will be able to exclude plugins,
Or, have a plugin list defined with names, and then adding them using those keys
* I mentioned it's there `:watch=lib/*.ts` (watching)

**Comment by vegarringdal** [comment]
@nchanged

Tried to do something fancy

```
//sample app
:devServer
>> app.js
  : onload: fuse-box-aurelia-loader + aurelia-boostrapper  <- imports before main.js
   > [main.ts]
   :watch = *.ts
   :pkg = myLib
   :main = index.js
   :cache = false
   :exclude-plugin = html + cssRaw
   :sourcemaps:true

   + someAureliaPlugin = (
         > node_modules/somethingCool/dist/commonjs
            + [**/*.html]
            + [**/*.js]
            + [**/*.css]
            :main = someAureliaPlugin.js
            :exclude-plugin = html + cssRaw
            :cache = true
            :sourcemaps:true
     )
   + someAureliaOtherPluginImDeveloping = (
         > ../src
            + [**/*.html]
            + [**/*.ts]
            + [**/*.css]
            :watch = *.ts
            :main = index.ts
            :cache = false
            :sourcemaps:true
            :exclude-plugin = html + cssRaw
     )
:bundle
>> vendor.js
   + aurelia-bootstrapper
   + aurelia-framework
   + aurelia-pal
   + aurelia-metadata
   + aurelia-polyfills
   :vendorSourcemaps:true
```

**Comment by vegarringdal** [comment]
@nchanged  so you will have a prototype tomorrow then ? 👍

**Comment by nchanged** [comment]
Lol yeah in 5 mins :)))

**Comment by vegarringdal** [comment]
ohh, nice, even better 🥇 👍 

😂

**Comment by cellog** [comment]
If you're writing a new language, why not go the jsx/tsx route and make a syntax parser which can be done with babel or a plugin to other systems for parsing. This way we get first class support for debugging syntax errors. This should compile to a fluent API. Otherwise, it's too complicated to do in strings, in my opinion. I hate debugging gigantic strings.

**Comment by devmondo** [comment]
@cellog  great point and it is part of the plan hopefully :)

**Comment by nchanged** [comment]
@cellog which language would you suggest?

**Comment by cellog** [comment]
@nchanged I was referring to "fuselang" which is still mythical atm :)

**Comment by nchanged** [comment]
@cellog they way I thought about debugging is visualising the instructions in the console. So each symbol would be explained, and errors spit.

**Comment by Thanood** [comment]
I'm really indifferent but as @vegarringdal asked me to leave a comment, I will do that. 😃 

My first thought was, maybe better keep the options out of `fuselang` and focus on the bundle syntax (what's in a bundle, what's not in, sub bundles, etc.). I think it might quickly look overburdened with a lot of options.

Then I remembered that this should become a low-level language which fuse-box operates on top of (kinda). So you would have f.i. a fluent api plugin which "transpiles" instructions to arithmetic expressions. Or a json plugin which spits out arithmetic expressions.

Actually, if this is the idea, it's brilliant because you's be able to provide a more readable (debuggable) format but you can always fall back to pure arithmetic when you need more flexibility.

I'm still not sure about all the options, though.
The thing is, in my opinion if you have a lot of "magic" characters to handle, it quickly looks like assembler.

```asm
:devServer
>> app.js
   + fuse-box-aurelia-loader + aurelia-boostrapper + my-lib
   > [main.ts]
   :watch = *.{ts,html,scss}
   :pkg = myLib
   :main = index.js
   :cache = false
   :exclude-plugin = html + cssRaw
   :sourcemaps = true
```

IMO the options break the elegance of the solution as they can mix simple arithmetics with any side-effects (depending on plugins used).

On the other hand, I can easily see how flexible this is. Different options for different sub-modules seem no problem.

**Comment by cellog** [comment]
@nchanged the advantage of a new syntax which is transpiled is in code hinting in developer tools. For example webstorm highlights jsx errors as I type. 

I do find magic characters to be a dangerous thing generally, but that's because I still wake up in cold sweats from nightmares where I am debugging Perl ;)

**Comment by nchanged** [comment]
We had an idea of making a web page, where you would drag bubbles or squares and see the output =)

**Comment by leon-andria** [comment]
This is not building an abstraction, we call that over engineer.
FuseBox should just expose the foundation of its Api and this done already in javascript, that we dont need to learn.
Also, by provinding a high level Api allows to build what we would like to create by its own taste.
Building this language means a lot of effort to sync between foundation and your new language or what ever it is.
Just focus on the core Foundation Api, leave the community to build and share their project.
The time you spend to implement this is more valuable for stabilities and strengths of FuseBox.
A good Software Foundation implies qualities and long term vision. As long as the foundation is solid, it is unbreakable from outside.
Believe me or not, some oss failed because too much opinionated on the wrong way.
This is my 2 cents advice for 20 years experiences of building software for 500 fortunes company.

**Comment by nchanged** [comment]
@leon-andria thanks for your input. FuseBox seemed impossible 3 month ago. And many people would have laughed at the idea of even thinking about creating another bundler.

**Comment by nchanged** [comment]
Some other idea. To make it look like `key` : `value`
```
devServer : true

bundle: app.js
   	> [index.ts] + somethingCool

   import : cool-lib-before-execution
   watch :  *.ts
   pkg : myLib
   main : index.js
   plugins : html, json, babel1

   register:
       somethingCool {
         > modules/mylib/index.js
            + **/*.html 
            + /**/*.js
            + /**/*.css
         plugins : babel2
       }
       
  

bundle : vendor.js
   > ~ index.ts
   watch :  *.ts
```

**Comment by nchanged** [comment]
![screenshot 2017-03-10 23 20 51](https://cloud.githubusercontent.com/assets/1629088/23815375/39e9009c-05e8-11e7-8cb4-8ce97387d692.png)

**Comment by leon-andria** [comment]
I fully agree with you on 3 months ago.
Key/value is good idea, i was thinking like this by doing it by yaml, i did it but i was not happy of the result. Yaml is easy to convert...
My final output was api on javascript because FuseBox can provide it with strong argument, i need to debug it, so javascript is right for that.
Also, think about it about support and documentation, it's about balance. It's not an easy choice but keep in mind about simplicity and adoption.
Remember the syntax i did about the fluent api! 
Verbs means a lot for understanding and logic.
And it hides completely about ~ ! > because its internal.
Hope it helps.

**Comment by vegarringdal** [comment]
@nchanged 

```
devServer : true

bundle: app.js
   	> [index.ts] + somethingCool

   import : cool-lib-before-execution
   watch :  *.ts
   pkg : myLib
   main : index.js
   plugins : html, json, babel1

   register:
       somethingCool {
         > modules/mylib/index.js
            + **/*.html 
            + /**/*.js
            + /**/*.css
         plugins : babel2
       }
```

maybe add ```src:``` to this as well then ?

**Comment by devmondo** [comment]
regarding @leon-andria  argument, why this won't be debuggable?

**Comment by leon-andria** [comment]
```js
interface IOptions {
}

interface IFuseBoxFactory {
  options<T extends IOptions>(options: T): IFuseBox;
}

type bundlerFactory = IFuseBoxBundler | IFuseBoxBundlerDeps

interface IFuseBox {
  createBundle(): bundlerFactory;
}

interface IFuseBoxBundler {
  with(entry: string, withDeps: boolean);
}

type bundlerParams = string | Array<string>;

interface IFuseBoxBundlerDeps {
  include(bundlerParams);
  exclude(bundlerParams);
}

class FuseBox implements IFuseBoxFactory {
  static options<T extends IOptions>(options: T): IFuseBox {
    //we can do a magic mixin here from different options
    //the idea here is that we allow custom options to enhance FuseBox internal stuff
    //like, we can provide diagnotics, logs, ... à la .NET Core concepts, pretty extensible here...
    return null;
  }
}

let options = {
  homeDir: './src',
  output: './build'
}; 

let fuse = FuseBox.options( options );
let plugins = fuse.plugins();
// plugins.add()
// plugins.add()
// plugins.add()

let bundle = fuse.createBundle( );

bundle
  .options({ 
    standalone: false,
    sourceMaps: false
  })
  .with( 'entry.ts', true )
  .include( [ '**/*.html', '**/*.sass' ] )
  .include( 'config/*.json' )
  .exclude( [ 'lodash', 'moment' ] )
  .exclude( 'jquery' )
  .packAs('app-bundle.js')

bundle
  .include( [ 'lodash', 'moment' ] )
  .packAs('libs.js')

bundle
  .include( [ 'aurelia-framework', 'aurelia-binding' ] )
  .packAs('aurelia.js')
```

**Comment by nchanged** [comment]
@leon-andria that would be possible as an additional API to construct arithmetics. But we can't take it full use to make multi-bundles.

1) Options override
```
bundle
  .options({ 
    standalone: false,
    sourceMaps: false
  })
  .with( 'entry.ts', true )
  .packAs('app-bundle.js')

bundle
    .options({ 
       sourceMaps: false
   })
  .include( [ 'lodash', 'moment' ] )
  .packAs('libs.js')
```

Does it mean that `standalone: false` stays there or not? If it's a new chain, that how is it being reset? by `packAs` ? I find it inconsistent as it defeats the purpose of chaining. 

2) Favourite #170 
It's a required feature that would allow registering a package in the scope. Meaning that it's not a bundle, it's a package that will be resolved with a certain rule. 
```
chain.
   .addPackage("blabla")
   .include("blabla")
   .packAs("sdf")
bundle.
   include("blaba") 
```
Again inconsistent. By doing `addPackage` are you making it available for a certain bundle all across all of them? If it's a shared package, then why `register` method happens within the first chain.

it will bloat up the config, and it's not very readable IMHO. Why I suggest is:

```
const fuse = FuseBox.init({
    output : "dist/$name.js"
});

fuse.register("customPackage", `
   > modules/index.ts
   **/**.html
`)

fuse.exec("a.ts >> out1", { /* override any options here*/ })
fuse.exec("b.ts +customPackage >> out2", { /* override any options here*/ })
fuse.exec("b.ts >> out3", { watch : true })
fuse.exec("c.ts >> out4")
```

Whereas `>>` is the only addition to arithmetics that we make. So we are going to make only ONE change, that will require a mandatory `>>` symbol to define the output, (which will be  filtered through the `output` options (with hashing and stuff)

**Comment by leon-andria** [comment]
The principle of the options is cascading mixin in 3 levels:
1. FuseBox
2. Bundler
3. Packager

It's good that you mention the #170 because the way how i suggested unify all of this.
Based on the doc, http://fuse-box.org/#package-name, package is like an options from the init.
But here you can turn it with the name and put it in the global context of execution.
As exemple you highlight, you notice that for the package, you say register and after you exec, this is not consistent.
On mine suggestion, it keeps the same philosophy, package or not and including files or resources are the same based on #170.

In simple words, what I try to provide as an API is just an abstract of yours (internal or existing). It's just that I don't want people to know all the trick of arithmetic.

**Comment by leon-andria** [comment]
@nchanged Making the naming more friendly, i change slightly the first proposal:
@vegarringdal This API design would attempt solve your regular issue with Aurelia
```js
interface IOptions {
}

interface IFuseBoxFactory {
  options<T extends IOptions>(options: T): IFuseBox;
}

type bundlerFactory = IFuseBoxBundler | IFuseBoxBundlerDeps

interface IFuseBox {
  createBundlerFactory(): bundlerFactory;
}

interface IFuseBoxBundler {
  with(entry: string, withDeps: boolean);
}

type bundlerParams = string | Array<string>;

interface IFuseBoxBundlerDeps {
  include(bundlerParams) : IFuseBoxBundlerDeps,
  exclude(bundlerParams) : IFuseBoxBundlerDeps,
  packageAs(name: string): void,
  bundle(filename: string): void
}

class FuseBox implements IFuseBoxFactory {
  static options<T extends IOptions>(options: T): IFuseBox {
    //we can do a magic mixin here from different options
    //the idea here is that we allow custom options to enhance FuseBox internal stuff
    //like, we can provide diagnotics, logs, ... à la .NET Core concepts, pretty extensible here...
    return null;
  }
}

let options = {
  homeDir: './src',
  output: './build'
}; 

let fuse = FuseBox.options( options );
let plugins = fuse.plugins();

let bundler = fuse.createBundlerFactory( );

bundler
  .options({ 
    standalone: false,
    sourceMaps: false
  })
  .with( 'entry.ts', true )
  .include( [ '**/*.html', '**/*.sass' ] )
  .include( 'config/*.json' )
  .exclude( [ 'lodash', 'moment' ] )
  .exclude( 'jquery' )
  .bundle('app-bundle.js');

bundler
  .include( [ 'lodash', 'moment' ] )
  .bundle('libs.js');

bundler
  .include( [ 'aurelia-framework', 'aurelia-binding' ] )
  .bundle('aurelia.js');
```
@nchanged The API doesn't aim to do a chaining or fluent, it does just an execution flow of what you would do with inline arithmetic.

This API is just a conceptual draft design that focus more on bundling, but it's also on the path how would be the code splitting that we had brainstormed in other issues.
If you guys want also the code splitting, let me know and we continue to describe it.

**Comment by vegarringdal** [comment]
I dont see in last post how I define resources for 1 package/module in that sample, but Ill have a new look later tonight when I got more time :-)

**Comment by leon-andria** [comment]
@vegarringdal Changed per your example:
```js
interface IOptions {
}

interface IFuseBoxFactory {
  options<T extends IOptions>(options: T): IFuseBox;
}

type bundlerFactory = IFuseBoxBundler | IFuseBoxBundlerDeps

interface IFuseBox {
  createBundlerFactory(): bundlerFactory;
}

interface IFuseBoxBundler {
  with(entry: string, withDeps: boolean);
}

type bundlerParams = string | Array<string>;

interface IFuseBoxBundlerDeps {
  include(bundlerParams) : IFuseBoxBundlerDeps,
  exclude(bundlerParams) : IFuseBoxBundlerDeps,
  packageAs(name: string): void,
  bundle(filename: string): void
}

class FuseBox implements IFuseBoxFactory {
  static options<T extends IOptions>(options: T): IFuseBox {
    //we can do a magic mixin here from different options
    //the idea here is that we allow custom options to enhance FuseBox internal stuff
    //like, we can provide diagnotics, logs, ... à la .NET Core concepts, pretty extensible here...
    return null;
  }
}

let options = {
  homeDir: './src',
  output: './build'
}; 

let fuse = FuseBox.options( options );
let plugins = fuse.plugins();

let bundler = fuse.createBundlerFactory( );

bundler
  .options({ 
    standalone: false,
    sourceMaps: false
  })
  .with( 'entry.ts', true )
  .include( [ '**/*.html', '**/*.sass' ] )
  .include( 'config/*.json' )
  .exclude( [ 'lodash', 'moment' ] )
  .exclude( 'jquery' )
  .bundle('app-bundle.js');

bundler
  .include( [ 'lodash', 'moment' ] )
  .bundle('libs.js');

bundler
  .include( [ 'aurelia-framework', 'aurelia-binding' ] )
  .bundle('aurelia.js');

bundler
  .options( {
    homeDir: './node_modules/evenCooler/src'
  })
  .with( 'index.ts' )
  .include( [ '**/*/html', '**/*.js', '**/*.css' ] )
  .packageAs( 'evenCooler' )
```

**Comment by leon-andria** [comment]
@nchanged Keep this way, my suggestion can be an external API that use this.
```js
const fuse = FuseBox.init({
    output : "dist/$name.js"
});

fuse.register("customPackage", `
   > modules/index.ts
   **/**.html
`)

fuse.exec("a.ts >> out1", { /* override any options here*/ })
fuse.exec("b.ts +customPackage >> out2", { /* override any options here*/ })
fuse.exec("b.ts >> out3", { watch : true })
fuse.exec("c.ts >> out4")
```

**Comment by vegarringdal** [comment]
@leon-andria 
That works better :+1:

**Comment by nchanged** [comment]
Thank you all for your contribution guys. I've thoroughly studied all the proposals and concerns, and I think this case will satisfy everyone.

```
const fuse = FuseBox.init()
fuse.devServer();

fuse.bundle("app")
    .watch("**/**.ts")
    .exec("> [index.ts]")

fuse.bundle("vendor")
    .exec("~ index.ts");
```
Whereas `fuse` is a factory that produces bundles. 

I have been thinking about it for almost a week. `Fuselang` is a cool idea tho, but it is a far fetched one. When we grow bigger, we'll definitely go for a language that is designed to do bundles. 

For now we will keep the arithmetics as they are now.

**Comment by nchanged** [comment]
https://github.com/fuse-box/fuse-box/issues/400
