### ISSUE TITLE
1.4.1 Preview!!!

### ISSUE THREAD

**Issue by nchanged** [fuse-box/fuse-box#416]
Give it a spin!
https://github.com/fuse-box/preview-1.4.1

Feel free to ask questions, propose changes. After it's all clear let's cook some docs ;-)

**Comment by vegarringdal** [comment]
Yay :-)

**Comment by arabsight** [comment]
Hi, thank you so much for this. you're the best :sparkles: 
so I was trying the register option (awesome work), and I noticed that it doesn't bundle the code unless I import it, I was hoping it forces the code in the bundle whether its imported or not, and the reason why is that aurelia has other ways of importing modules, like this:

```js
aurelia.use.plugin('aurelia-notify');
// this won't work unless I have import 'aurelia-notify' 
```
or this:

```js
<require from="bootstrap/css/bootstrap.css"></require>
// this won't work unless I have import 'bootstrap' 
```
it would be great to remove those imports because aurelia will import them with the loader.

thanks.

**Comment by nchanged** [comment]
Thanks :) can't u just add it to the arithmetic section? If we force it will come to all bundles in the producer, which shouldn't happen

**Comment by arabsight** [comment]
wow, adding it to the arithmetic section did it, works like a charm, thank you.

**Comment by Thanood** [comment]
> just add it to the arithmetic section

Does this work for css/html files, too? 😃

**Comment by arabsight** [comment]
@Thanood it does, those go in the register method, in the arithmetic section you just put the name of the package.

```js
fuse.register('aurelia-notify', {
    homeDir: 'node_modules/aurelia-notify/dist/commonjs',
    main: 'aurelia-notify.js',
    instructions: '**/*.{html,css}',
});

fuse.bundle('bundle')
    .instructions(`
        > main.js
        + **/*.{js,html,css}
        + aurelia-pal-browser
        + aurelia-framework
        ...
        + aurelia-notify
    `);
```

**Comment by Thanood** [comment]
This is awesome! 👍

**Comment by vegarringdal** [comment]
![image](https://cloud.githubusercontent.com/assets/2901416/24073257/06d645d0-0bf5-11e7-8e81-862e8772470a.png)

Anyone else get this ?

**Comment by arabsight** [comment]
Hi, it would be nice if we the instructions option (in the register method) is optional .
helpful when bundling css only libraries (like font-awesome...) right now I'm doing this:
```js
fuse.register('font-awesome', {
    homeDir: 'node_modules/font-awesome/css',
    instructions: 'font-awesome.css',
});
```
that works fine but it adds this to the bundle: 
```
return ___scope___.entry = "index.js"; 
```

if I do this:
```js
fuse.register('font-awesome', {
    homeDir: 'node_modules/font-awesome/css',
    main: 'font-awesome.css',
    instructions: 'font-awesome.css',
});
```
then the css file gets duplicated in the bundle, and I can't remove the instructions option since its mandatory.
but providing a fake instruction works, and writes the proper entry:
```js
fuse.register('font-awesome', {
    homeDir: 'node_modules/font-awesome/css',
    main: 'font-awesome.css',
    instructions: 'foo', // or even a space
});
```
so it makes sense to just make it optional :smile: for cases like this.

**Comment by nchanged** [comment]
I see, yes. It makes sense, along with the code splitting, that is cooooommmiiing ;-)
