### ISSUE TITLE
clear cache when .rc files change

### ISSUE THREAD

**Issue by aretecode** [fuse-box/fuse-box#421]
when rc files change, automatically clear cache 

- [ ] babelrc
- [ ] typescript

**Comment by mizchi** [comment]
I encountered runtime error after switching `.babelrc` resolver https://github.com/mizchi-sandbox/inferno-matter-sandbox/blob/master/.babelrc#L11-L19

```
rm -r .fusebox 
node fuse-build.js
```

@aretecode This issue resolve it?

**Comment by nchanged** [comment]
### FuseBox v4 Major Upgrade

As of today, the latest major version of FuseBox `v4` is available in `fuse-box@next`. FuseBox has undergone a full re-write from scratch, learning from its mistakes in the previous versions.

There are a lot of improvements, speed and config wise.

Get started [here](https://github.com/fuse-box/fuse-box/blob/master/docs/getting-started/get-started.md)

We are still working on the documentation and polishing before the major release. We are getting very close. And we need help testing.

```bash
npm install fuse-box@next
```

Most of the issues that I am closing have been resolved, however, if you find that your issue is still relevant in `v4` don't hesitate to re-open or (better) create a new one with `v4` configuration.
