### ISSUE TITLE
How to output AMD define() modules?

### ISSUE THREAD

**Issue by trusktr** [fuse-box/fuse-box#431]
I'd like to output my bundles in AMD `define()` format to load them in a legacy RequireJS environment. Can that be done?

**Comment by trusktr** [comment]
I guess I need to make a plugin to wrap output in define, just to run it as a entry point (it doesn't need any dependencies).

f.e.

```js
define([], function() {
  // inject fuse output here just to run it, doesn't need to load any external deps.
})
```

**Comment by nchanged** [comment]
hm... so just a wrapper? Does this function need to return anything?

**Comment by trusktr** [comment]
@nchanged Yes, the wrapper needs to return whatever is exported from the module, both named and default export. f.e.

```js
return {
  default: foo, // export default foo
  blah, // export blah
}
```

The compiled entry points are loaded by RequireJS, and sometimes their export is used. I think this is an important feature for running modern code in legacy environments (there's plenty of legacy environments around).

The equivalent of this in Webpack is to use `output.libraryName` and `output.library`.

**Comment by Thanood** [comment]
I'm also interested to see such an option.
I need to use RequireJS in my app but I'd like the plugins to be bundled with fuse. 😃

**Comment by nchanged** [comment]
@Thanood I think it might come to Quantum, It makes sense there. We are talking about the final bundle output, to register a name in AMD, right?

**Comment by Thanood** [comment]
That seems correct - while it's also possible to create anonymous modules with AMD, it will need a name to be loaded properly. The (fuse-virtual) path may be a good default but I'd guess this would be configurable (like everything with fuse-box is).

**Comment by nchanged** [comment]
@Thanood just to be clear, we are talking about 1 bundle and with this option
http://fuse-box.org/page/quantum#containedapi

**Comment by vegarringdal** [comment]
@Thanood its a aurelia app? if so quantum, rollup etc wont work
.. not yet atleast

**Comment by Thanood** [comment]
@nchanged TBH I didn't understand everything of it and I haven't tried Quantum so far so take this with a grain of salt.

Im my use-case I'd like to load the plugin bundles at dev time, too. While I can steer around that (configuring the AMD loader appropriately), it would be convenient if I could just load the fuse bundle(s).

Also there is one bundle for each plugin. So let's say, I want to load a "metainfo" plugin to enable the host app to display meta infos (obviously 😏 ). The app will load the bundle with the AMD loader and since all modules are defined internally in that bundle, everything is okay.

But that's more than one bundle overall. Does that answer the question?
What I'm thinking of is something like (abbreviated):

```js
fuse.bundle('plugin-main-file.ts')
  .instructions('index.js')
  .moduleFormat('amd'); // or anything else, f.i. 'fuse-box', 'umd', 'commonjs'
```

Which would output 'plugin-main-file.js` as a bundled AMD module. This is like bundling a library, no starting point, no loader api (could have used `.instructions('!index.js')`). I'd be responsible for providing a loader for that api.

I could understand if you consider this use-case to be too specific for a general solution. 😃 
But I guess this would be a benefit so I could produce multiple module formats for any library.

@vegarringdal Quantum doesn't work with Aurelia? Even when rollup or tree-shaking is not used?
As I understand it, the tree is just nur shaken when I don't use compatible imports/requires/module.exports, right? I could live with that. 😃

**Comment by nchanged** [comment]
@Thanood Quantum outputs highly performant bundles, think of it's as a binary. It's it's a matter of just wrapping the script with `define` we could do that. In the meantime, I would recommend getting acquainted with Quantum.
We are thinking with @vegarringdal how to make Aurelia Quantum friendly (without tree shaking)

**Comment by rdemetrescu** [comment]
@nchanged  @vegarringdal  yes, please !!  give Aurelia some love...   :)

**Comment by nchanged** [comment]
### FuseBox v4 Major Upgrade

As of today, the latest major version of FuseBox `v4` is available in `fuse-box@next`. FuseBox has undergone a full re-write from scratch, learning from its mistakes in the previous versions.

There are a lot of improvements, speed and config wise.

Get started [here](https://github.com/fuse-box/fuse-box/blob/master/docs/getting-started/get-started.md)

We are still working on the documentation and polishing before the major release. We are getting very close. And we need help testing.

```bash
npm install fuse-box@next
```

Most of the issues that I am closing have been resolved, however, if you find that your issue is still relevant in `v4` don't hesitate to re-open or (better) create a new one with `v4` configuration.
