### ISSUE TITLE
Empty files?

### ISSUE THREAD

**Issue by trusktr** [fuse-box/fuse-box#432]
I see some files look like this:

```js
(function(FuseBox){FuseBox.$fuse$=FuseBox;
FuseBox.pkg("default", {}, function(___scope___){
});

FuseBox.import("default/src/modes/EditorApp.js");
FuseBox.main("default/src/modes/EditorApp.js");
})
(function(e){if(e.FuseBox)return e.FuseBox;var r="undefined"!=typeof window&&window.navigator;r&&(window.global=window),e=r&&"undefined"==typeof __fbx__dnm__?e:module.exports;var n=r?window.__fsbx__=window.__fsbx__||{}:global.$fsbx=global.$fsbx||{};r||(global.req
```

There doesn't seem to be any of my code in them?

**Comment by nchanged** [comment]
Yeah, it's a know issue. When you do vendor, `default`is still created

**Comment by Shepless** [comment]
@devmondo @nchanged for v3 roadmap?

**Comment by nchanged** [comment]
well, we can't produce empty files, a simple structure must be created. An API

**Comment by nchanged** [comment]
### FuseBox v4 Major Upgrade

As of today, the latest major version of FuseBox `v4` is available in `fuse-box@next`. FuseBox has undergone a full re-write from scratch, learning from its mistakes in the previous versions.

There are a lot of improvements, speed and config wise.

Get started [here](https://github.com/fuse-box/fuse-box/blob/master/docs/getting-started/get-started.md)

We are still working on the documentation and polishing before the major release. We are getting very close. And we need help testing.

```bash
npm install fuse-box@next
```

Most of the issues that I am closing have been resolved, however, if you find that your issue is still relevant in `v4` don't hesitate to re-open or (better) create a new one with `v4` configuration.
