### ISSUE TITLE
output is in wrong directory, not-changeable, no warnings

### ISSUE THREAD

**Issue by aretecode** [fuse-box/fuse-box#436]
config:
```
{ entry: '> [src/index.js]',
        output: 'test/dist/buildSync.js',
        log: true,
        debug: true,
        plugins:
         [ FuseBoxHTMLPlugin { useDefault: true, test: { /\.html$/ [lastIndex]: 0 } },
           FuseBoxJSONPlugin { test: { /\.json$/ [lastIndex]: 0 } },
           [length]: 2 ],
```

actually winds up going to 
```
 output:
            UserOutput {
              context: [Circular],
              original: 'test/dist/$name',
              filename: 'buildSync.js',
              useHash: false,
              template: '$name',
              dir: '/Users/.../node_modules/ava/lib/test/dist' } } },
```

and this configuration is not changeable, and there is no debugging for it

**Comment by nchanged** [comment]
### FuseBox v4 Major Upgrade

As of today, the latest major version of FuseBox `v4` is available in `fuse-box@next`. FuseBox has undergone a full re-write from scratch, learning from its mistakes in the previous versions.

There are a lot of improvements, speed and config wise.

Get started [here](https://github.com/fuse-box/fuse-box/blob/master/docs/getting-started/get-started.md)

We are still working on the documentation and polishing before the major release. We are getting very close. And we need help testing.

```bash
npm install fuse-box@next
```

Most of the issues that I am closing have been resolved, however, if you find that your issue is still relevant in `v4` don't hesitate to re-open or (better) create a new one with `v4` configuration.
