### ISSUE TITLE
Many `any` types in the FuseBox constructor options

### ISSUE THREAD

**Issue by ma2ciek** [fuse-box/fuse-box#449]
Playing recently with Fusebox I encountered the problem with available types in the FuseBox constructor 
Especially the [sourceMaps](https://github.com/fuse-box/fuse-box/blob/9506950c85196a2e061d7bdd4a603d41b0f8436e/src/core/FuseBox.ts#L33) part is at least confusing and I had to read a few tickets to get everything in my project working. 

The proper type definitions may help people to work with this bundle meanwhile the `any` type steps us back to the normal JavaScript world.

**Comment by aretecode** [comment]
Maybe it should be converted to vanilla JavaScript!

**Comment by nchanged** [comment]
Yeah we have this problem, but we are solving it step by step. 1.4.1 has many fixes already

**Comment by nchanged** [comment]
### FuseBox v4 Major Upgrade

As of today, the latest major version of FuseBox `v4` is available in `fuse-box@next`. FuseBox has undergone a full re-write from scratch, learning from its mistakes in the previous versions.

There are a lot of improvements, speed and config wise.

Get started [here](https://github.com/fuse-box/fuse-box/blob/master/docs/getting-started/get-started.md)

We are still working on the documentation and polishing before the major release. We are getting very close. And we need help testing.

```bash
npm install fuse-box@next
```

Most of the issues that I am closing have been resolved, however, if you find that your issue is still relevant in `v4` don't hesitate to re-open or (better) create a new one with `v4` configuration.
