### ISSUE TITLE
better .watch

### ISSUE THREAD

**Issue by aretecode** [fuse-box/fuse-box#488]
problem:
- using `.watch()` will include your `dist` folder by default if it is inside the homedir - which it usually is if you have a homeDir that is not `src`. this behaviour is not very smart, and is confusing when there is an infinite loop of rebuilding.

solutions:
- either throw if no glob is passed in
- or be smarter about which dirs to watch by default, if it is supposed to be easy
- cannot `warn` because rebuilding infinitely doesn't allow for a red debug log to be of much use

**Comment by aretecode** [comment]
![infinity](https://cloud.githubusercontent.com/assets/4022631/25767777/43cc3e22-31b1-11e7-9617-7ddd174b3778.gif)

**Comment by nchanged** [comment]
You think you can check it [here](https://github.com/fuse-box/fuse-box/blob/master/src/core/BundleProducer.ts#L108)? 

We can compare it with [this](https://github.com/fuse-box/fuse-box/blob/master/src/core/UserOutput.ts#L15) piece

**Comment by devmondo** [comment]
i like second suggestion from @aretecode

**Comment by whitecolor** [comment]
are we there yet?

**Comment by nchanged** [comment]
### FuseBox v4 Major Upgrade

As of today, the latest major version of FuseBox `v4` is available in `fuse-box@next`. FuseBox has undergone a full re-write from scratch, learning from its mistakes in the previous versions.

There are a lot of improvements, speed and config wise.

Get started [here](https://github.com/fuse-box/fuse-box/blob/master/docs/getting-started/get-started.md)

We are still working on the documentation and polishing before the major release. We are getting very close. And we need help testing.

```bash
npm install fuse-box@next
```

Most of the issues that I am closing have been resolved, however, if you find that your issue is still relevant in `v4` don't hesitate to re-open or (better) create a new one with `v4` configuration.
