### ISSUE TITLE
plugins should be required only when used

### ISSUE THREAD

**Issue by aretecode** [fuse-box/fuse-box#510]
the plugins should be exported with `object define` and only required when used, here is an example:

```js
const {resolve, isAbsolute} = require('path')
function objDefine() {}

objDefine.value = function objectDefineValue(
  obj,
  name,
  value,
  configurable = true,
  enumerable = false
) {
  Object.defineProperty(obj, name, {
    configurable,
    enumerable,
    value,
  })
  return objDefine
}

objDefine.req = function objectDefineDynamicRequire(
  obj,
  name,
  value = null,
  configurable = true,
  enumerable = true
) {
  const req = value
  if (value === null) req = name
  Object.defineProperty(obj, name, {
    configurable,
    enumerable,
    get() {
      return require(req)
    },
  })
  return objDefine
}

objDefine.reqs = function objectDefineDynamicRequires(obj, dir, properties) {
  properties.forEach(req => {
    const name = Object.keys(req).shift()
    let val = req[name]

    if (val.includes('./') === true) {
      val = resolve(dir, req[name])
    }
    else {
      val = require.resolve(val)
    }

    objDefine.req(obj, name, val)
  })
}

module.exports = objDefine
```

```js
const {reqs} = require('./obj-def')
reqs(module.exports, __dirname, [
  {JSONPlugin: './plugins/JSONPlugin'},
  {BabelPlugin: './plugins/transpilers/BabelPlugin'},
  // ...
])
```

**Comment by nchanged** [comment]
### FuseBox v4 Major Upgrade

As of today, the latest major version of FuseBox `v4` is available in `fuse-box@next`. FuseBox has undergone a full re-write from scratch, learning from its mistakes in the previous versions.

There are a lot of improvements, speed and config wise.

Get started [here](https://github.com/fuse-box/fuse-box/blob/master/docs/getting-started/get-started.md)

We are still working on the documentation and polishing before the major release. We are getting very close. And we need help testing.

```bash
npm install fuse-box@next
```

Most of the issues that I am closing have been resolved, however, if you find that your issue is still relevant in `v4` don't hesitate to re-open or (better) create a new one with `v4` configuration.
