### ISSUE TITLE
Using UglifyJS with sourceMap is not handled by the browser

### ISSUE THREAD

**Issue by RPDeshaies** [fuse-box/fuse-box#543]
Here's the fusebox Config : 

```
const fuse = fsbx.FuseBox.init({
  homeDir: './client/src',
  output: './client/build_dev/static/$name.js',
  tsConfig: './tsconfig.json',
  sourceMaps: true,
  shim: shims,
  plugins: [
    fsbx.EnvPlugin({
      NODE_ENV: process.env.NODE_ENV
    }), [fsbx.SassPlugin({
      outputStyle: dev ? 'nested' : 'compressed'
    }), fsbx.PostCSS([autoprefixer({ remove: false, browsers: ['last 6 version'] })]), fsbx.CSSPlugin()],
    fsbx.BabelPlugin({
      comments: false,
      presets: ['es2015']
    }),
    fsbx.TypeScriptHelpers(),
    fsbx.JSONPlugin(),
    fsbx.CSSPlugin(),
    fsbx.RawPlugin(['*.svg']),
    fsbx.HTMLPlugin({
      useDefault: false
    }), fsbx.UglifyJSPlugin({
      compress: {
        unused: false
      },
      output: {
        'max_line_len': 1000000
      }
    }),
  ],
  debug: false,
  log: true
})
```

The `app.js` and `app.map.js` files are generated but my browser (Chrome) doesn't detect the source

![image](https://cloud.githubusercontent.com/assets/6224111/26167290/63878bac-3b04-11e7-87e3-ef9b3528a214.png)

**Comment by nchanged** [comment]
We never handled it. It's possible but requires an update to the UglifyJS Plugin.

**Comment by nchanged** [comment]
### FuseBox v4 Major Upgrade

As of today, the latest major version of FuseBox `v4` is available in `fuse-box@next`. FuseBox has undergone a full re-write from scratch, learning from its mistakes in the previous versions.

There are a lot of improvements, speed and config wise.

Get started [here](https://github.com/fuse-box/fuse-box/blob/master/docs/getting-started/get-started.md)

We are still working on the documentation and polishing before the major release. We are getting very close. And we need help testing.

```bash
npm install fuse-box@next
```

Most of the issues that I am closing have been resolved, however, if you find that your issue is still relevant in `v4` don't hesitate to re-open or (better) create a new one with `v4` configuration.
