### ISSUE TITLE
Impossible package out of `default` client-side

### ISSUE THREAD

**Issue by eddow** [fuse-box/fuse-box#550]
I noticed a problem that is easier explained than made a repository for.

Client-side, loading a dynamic file is done after XHR through `FuseBox.dynamic`. The third argument is the `options` argument that allows to specify a package.
```javascript
    public static dynamic(path: string, str: string, opts?: {
        /** The name of the package */
        pkg: string
    }) {
        this.pkg(opts && opts.pkg || "default",
```
This function is never (beside in tests) called with `options` set, Following is the call from `xmlhttp.onreadystatechange`
```javascript
FuseBox.dynamic(normalized, content);
```
I checked and saw a file `pkg/file.name` dynamically loaded is indeed registered in package `default` with `pkg/file.name` as its path.

**Comment by nchanged** [comment]
So this [part](https://github.com/fuse-box/fuse-box/blob/master/src/loader/LoaderAPI.ts#L569) doesn't make any difference?

**Comment by eddow** [comment]
well, as `opts` is never given, these two lines miss each another: (350-351)
https://github.com/fuse-box/fuse-box/blob/master/src/loader/LoaderAPI.ts#L350

`FuseBox.dynamic` register the path `pkg/file.js` in package `default`
`FuseBox.import` looks for the path `file.js` in package `pkg`

**Comment by nchanged** [comment]
@eddow because you are not setting it

```
require("pkg/target.js") /// or
FuseBox.import("pkg/target.js")
```

It's all simple.

**Comment by eddow** [comment]
I was getting to this conclusion in parallel indeed - I guess then the user has to load the packages "manually" if he wants to do it with ajax, execute it and then import it.

**Comment by nchanged** [comment]
### FuseBox v4 Major Upgrade

As of today, the latest major version of FuseBox `v4` is available in `fuse-box@next`. FuseBox has undergone a full re-write from scratch, learning from its mistakes in the previous versions.

There are a lot of improvements, speed and config wise.

Get started [here](https://github.com/fuse-box/fuse-box/blob/master/docs/getting-started/get-started.md)

We are still working on the documentation and polishing before the major release. We are getting very close. And we need help testing.

```bash
npm install fuse-box@next
```

Most of the issues that I am closing have been resolved, however, if you find that your issue is still relevant in `v4` don't hesitate to re-open or (better) create a new one with `v4` configuration.
