### ISSUE TITLE
Dynamic imports support

### ISSUE THREAD

**Issue by nchanged** [fuse-box/fuse-box#627]
Subj

* import json
* import CSS
* import ANY other extension (give strings)
* import javascript file (+commonjs)
* import split bundles

Should work in all environments with targets set (server, browser, universal)

```js
import("./main.css")
await import("./external.js")
await import("./config.json")
// bundle name "about"
await import("about")

// bundle name "about"
// automatically mapped to bundle "about" (no comments required)
await import("./components/about/AboutComponent")

```

**Comment by xdave** [comment]
Yes.

**Comment by xdave** [comment]
With the last bit, when automatically mapping to a bundle, it would be nice if perhaps a split bundle config did not have to be declared.

If someone `import()`s `./components/about/AboutComponent`, if am existing split bundle cannot be identified, it should simply put `AboutComponent.tsx` and anything that `AboutComponent.tsx` depends on into a new split bundle with a random or name or some such, ie: `bundle0.js`, `bundle1.js`, etc.

**Comment by faceyspacey** [comment]
I'd like to add that importing js should import the stylesheet as a separate file. So when you import a js chunk, 2 async requests are made: one for js, and one for css. 

I created this Webpack plugin:

https://github.com/faceyspacey/extract-css-chunks-webpack-plugin

as well as the following package for automatically discovering and serving chunks used in the server render:

https://github.com/faceyspacey/webpack-flush-chunks

And basically what I've determined is that the way Webpack has you do one configuration for development (with HMR and css injection within js) and another for production (sheets + js) is incorrect. It makes going from development to production unpredictable. 

So my conclusion is that in both cases you should have separate css and js. Stylesheets have their own HMR. And when serving async requests, you shouldn't have to serve a different js bundle that has js injection (something unique extract-css-chunks-webpack-plugin currently does). The way it currently works is you server js without js injection in initial requests, but for async imports, you get another version of the js chunk that has css injection (via style loader). That's incorrect, especially since it makes builds a lot slower.  

So I've made a babel plugin I'm about to release that does the double async request instead, and therefore allows you to cleanly produce a single js file and a single css file per chunk. 

It would be awesome if Fuse Box skipped a lot of these lessons and got it right from the beginning. [simultaneous SSR + Code Splitting](https://medium.com/@faceyspacey/code-cracked-for-code-splitting-ssr-in-reactlandia-react-loadable-webpack-flush-chunks-and-1a6b0112a8b8) is about to be all that everyone does. It's just finally a solved problem (and without Next.js), so React developers shouldn't be settling for SPAs anymore. Getting this right certainly could be a differentiator for Fusebox over Webpack. I'm honestly fed up with Webpack, hence I'm here. It's impossible to work with that codebase, if for no other reason it's not commented nicely like yours is.

Anyway, that's my 2 cents: dont do css injection within javascript, always plan on serving js + stylesheets, build HMR into it (something extract-text-webpack-plugin does--mine does though); and customize `import()` to request 2 files. It's a dead simple babel plugin, or ts plugin or whatever. To complete the loop you just gotta serve a mapping of css files to chunk names like Webpack currently only does for JS.

**Comment by faceyspacey** [comment]
also, the idea of `await import()` working in all environments, i.e. the server is a good one. Same with no magic comments. 

All the lessons of webpack's failures are urs to pick up and skip the bloat. I'm sure that's your whole thesis.

**Comment by nchanged** [comment]
@faceyspacey thanks for such a nice review! Indeed CSS is difficult one to tackle. They way we do it is - inline for development and make actual files for production. 

All development process happens using the Vanilla API, after that `Quantum` kicks in.  Code splitting doesn't happen during development, I mean it happens but FuseBox fakes it. Therefore removes any kind of source maps bugs, hmr issues e.t.c which I find extremely convenient. 

There is a room for improvement that's for sure. For example splitting without configuration. We aim to make it simple, tranparent and more automatic.

**Comment by faceyspacey** [comment]
Awesome. Where are you guys based? And how long have you been working on this?

I'm no build tool expert, but perhaps its my next challenge--an idea I've been thinking about is *how much babel can do on its own?* It seems to me extremely inefficient the way Webpack traverses the same code Babel does. If it could all happen in one step that would be way faster I assume. 

I know it probably boils down to babel limitations. So the solutions seems to be another babel that does both what babel and webpack does lol. Or, rather, since the current babel plugin api likelyc cant handle it, an *additional* plugin API for the sorta things a bundler needs.

What are your thoughts on this?

**Comment by nchanged** [comment]
@faceyspacey 

I personally dislike Babel, I like typescript compiler better. It's at least 3x faster and lighter. Besides we are using it to transpile es6 to es5 (not just for typescript)

Then we prefer `acorn` AST over babels', and traversing the code in just one loop, that's why it's so darn fast. 

 join [gitter](gitter.im/fusebox-bundler/Lobby) for a chat ;-)
