### ISSUE TITLE
Watch mode for test runner

### ISSUE THREAD

**Issue by a-s-o** [fuse-box/fuse-box#636]
Moving fuse-box/fuse-test-runner/issues/11 from test-runner repo to here as requested:

Hi,

Are there any plans to add a watch mode to the test runner? Currently test runner terminates after all tests are done.

I am doing this but the watch() does nothing. The runner still exists after first run:

```
  fuse
    .bundle('feature')
    .watch()
    .test('[**/**.test.ts]')
```
For others that are interested, I am currently using the following workaround:
```
  "scripts": {
    "test": "chokidar 'src/**/*.ts' -c 'node fuse test' --initial",
  },
```

Chokidar can be installed with `npm install chokidar-cli`. The lag between the change detection + re-running of the tests adds about ~0.5s for each change. Hopefully implementing this natively will be faster.

**Comment by devmondo** [comment]
@a-s-o yep that is cool idea, we shall work on it and it makes sense. 

meanwhile, did u check this https://github.com/fuse-box/fuse-box/issues/477
you can run the test runner with wallaby! and it gets you exactly what you want, and even better :) 

we hope that wallaby guys would make it official soon :)

**Comment by JoeLanglois** [comment]
Still not implemented, any progress so far?

**Comment by Shepless** [comment]
@JoeLanglois @nchanged probably a feature we will look at for v3?

**Comment by nchanged** [comment]
@Shepless yep, we need to start working on the roadmap and collect all these things

**Comment by MrFoxPro** [comment]
+1
It would be great to have watch mode for test-runner

**Comment by nchanged** [comment]
@patrickmichalina it does. I just don't have time for it just yet. For example mocking would be great to have ;-)

**Comment by nchanged** [comment]
### FuseBox v4 Major Upgrade

As of today, the latest major version of FuseBox `v4` is available in `fuse-box@next`. FuseBox has undergone a full re-write from scratch, learning from its mistakes in the previous versions.

There are a lot of improvements, speed and config wise.

Get started [here](https://github.com/fuse-box/fuse-box/blob/master/docs/getting-started/get-started.md)

We are still working on the documentation and polishing before the major release. We are getting very close. And we need help testing.

```bash
npm install fuse-box@next
```

Most of the issues that I am closing have been resolved, however, if you find that your issue is still relevant in `v4` don't hesitate to re-open or (better) create a new one with `v4` configuration.
