### ISSUE TITLE
Sourcemaps

### ISSUE THREAD

**Issue by leon-andria** [fuse-box/fuse-box#651]
We should have sourcemaps merged from custom modules folder.
Today, the array of sourceContent of the sourcemap file contains null for the custom module.

**Comment by nchanged** [comment]
@leon-andria modulesFolder is like a local npm, it's quite complicated to make it work from there, it's not an actual project

**Comment by leon-andria** [comment]
I understand but requiring a sourcemap is so important to able to debug. This is the most basic stuff that any developpers will do, debugging, debugging.

**Comment by nchanged** [comment]
### FuseBox v4 Major Upgrade

As of today, the latest major version of FuseBox `v4` is available in `fuse-box@next`. FuseBox has undergone a full re-write from scratch, learning from its mistakes in the previous versions.

There are a lot of improvements, speed and config wise.

Get started [here](https://github.com/fuse-box/fuse-box/blob/master/docs/getting-started/get-started.md)

We are still working on the documentation and polishing before the major release. We are getting very close. And we need help testing.

```bash
npm install fuse-box@next
```

Most of the issues that I am closing have been resolved, however, if you find that your issue is still relevant in `v4` don't hesitate to re-open or (better) create a new one with `v4` configuration.
