### ISSUE TITLE
hmrUpdate

### ISSUE THREAD

**Issue by vegarringdal** [fuse-box/fuse-box#663]
Hi

Possible to get some option to push events to them when u want?

```javacsript
return fuse.run().then((res) => {
          // somehow get the instance of it here, so I can emit({type:'whatever, something:'cool'}) 
    })
```
If could get something like this then I can have 1 fuse that make packages, when that rebundles I can call my main fuse with dev server and tell it to update, or reload module etc
This would have been very useful

**Comment by nchanged** [comment]
### FuseBox v4 Major Upgrade

As of today, the latest major version of FuseBox `v4` is available in `fuse-box@next`. FuseBox has undergone a full re-write from scratch, learning from its mistakes in the previous versions.

There are a lot of improvements, speed and config wise.

Get started [here](https://github.com/fuse-box/fuse-box/blob/master/docs/getting-started/get-started.md)

We are still working on the documentation and polishing before the major release. We are getting very close. And we need help testing.

```bash
npm install fuse-box@next
```

Most of the issues that I am closing have been resolved, however, if you find that your issue is still relevant in `v4` don't hesitate to re-open or (better) create a new one with `v4` configuration.
