### ISSUE TITLE
Add an option to have custom cache dir (or use os tmpdir)

### ISSUE THREAD

**Issue by whitecolor** [fuse-box/fuse-box#688]
It is just not very clean way to place temporary files in project dir. So some users may want to have
fuse box cache dir not in project dir, but in for example in os tmp dir.

I think It would be useful to add an option for custom cache directory so the user can decide where to place the cache for particular fuse-box instance running.

**Comment by whitecolor** [comment]
Cache folder also messes with file watchers, so it would be really useful to have it out of working scope.

**Comment by nchanged** [comment]
https://github.com/fuse-box/fuse-box/blob/master/src/Config.ts#L14
I think we can close this one

**Comment by whitecolor** [comment]
I think this is a little bit inconvenient because of `process.env.FUSEBOX_TEMP_FOLDER` should exist prior launching `node fuse.js` so you can not define it inside `fuse.js`. 

And it really would be useful could define cache path in `fuse.run` options in single `fuse.js` config.

**Comment by nchanged** [comment]
i don't think it's possible at the very moment, as this config is shared

**Comment by whitecolor** [comment]
Ok, then would you consider reopening the issue till it would be possible? Actually, I think env var `FUSEBOX_TEMP_FOLDER` will work well for a container setup, but still would be nice to have via `run` config.

**Comment by pyros2097** [comment]
I seem to have run into this issue also. I'm trying to create a cli which has a common fusebox configuration and which is used to build my other projects. Its working fine whenever I build any project it ends up creating a .fusebox folder in my cli project and not in the current working dir of my other project.

**Comment by nchanged** [comment]
@pyros2097 process.env.FUSEBOX_TEMP_FOLDER doesn't work for you?

**Comment by pyros2097** [comment]
I just tried it. It works. I just added this before I import fusebox.
```js 
const cwd = process.cwd();
process.env.FUSEBOX_TEMP_FOLDER = cwd
```
and Ohh man I just wiped out my react-example folder. Good thing it has git vcs.

**Comment by calebboyd** [comment]
😶

**Comment by calebboyd** [comment]
I have this use case with nexe as well. Starting fusebox when it isn't being used in the context of the main module (eg as a dependency) is pretty cumbersome right now.

**Comment by nchanged** [comment]
### FuseBox v4 Major Upgrade

As of today, the latest major version of FuseBox `v4` is available in `fuse-box@next`. FuseBox has undergone a full re-write from scratch, learning from its mistakes in the previous versions.

There are a lot of improvements, speed and config wise.

Get started [here](https://github.com/fuse-box/fuse-box/blob/master/docs/getting-started/get-started.md)

We are still working on the documentation and polishing before the major release. We are getting very close. And we need help testing.

```bash
npm install fuse-box@next
```

Most of the issues that I am closing have been resolved, however, if you find that your issue is still relevant in `v4` don't hesitate to re-open or (better) create a new one with `v4` configuration.
