### ISSUE TITLE
SVG Plugin configuration?

### ISSUE THREAD

**Issue by screendriver** [fuse-box/fuse-box#733]
Is it possible to configure the SVG plugin in some way? For example in my old `webpack.config.js` I have following loaders defined:

```js
{
  test: /\.(svg)$/,
  oneOf: [
    {
      resourceQuery: /asSvgCode/,
      use: 'raw-loader',
    },
    {
      resourceQuery: /asPath/,
      use: [
        'file-loader',
        {
          loader: 'image-webpack-loader',
          query: {
            svgo: {
              // Further optimizations possible
            },
          },
        },
      ],
    },
  ],
}
```

And in my code I have following:

```js
import myLogo from './logo.svg?asPath';
```

or

```js
import calendar from './svg/calendar.svg?asSvgCode';
```

How to achieve this with `fuse-box`?

**Comment by nchanged** [comment]
@screendriver fusebox had the related functionality, but it was removed on purpose because It's a very bundler specific thing (webpack) and doesn't tell other people what that actually means. Therefore, it should be solved with chains and a special option (which we don't have just yet)

**Comment by screendriver** [comment]
👍 
I'm looking forward for options support in this plugin ☺️

**Comment by nchanged** [comment]
### FuseBox v4 Major Upgrade

As of today, the latest major version of FuseBox `v4` is available in `fuse-box@next`. FuseBox has undergone a full re-write from scratch, learning from its mistakes in the previous versions.

There are a lot of improvements, speed and config wise.

Get started [here](https://github.com/fuse-box/fuse-box/blob/master/docs/getting-started/get-started.md)

We are still working on the documentation and polishing before the major release. We are getting very close. And we need help testing.

```bash
npm install fuse-box@next
```

Most of the issues that I am closing have been resolved, however, if you find that your issue is still relevant in `v4` don't hesitate to re-open or (better) create a new one with `v4` configuration.

**Comment by remotezygote** [comment]
Is this possible in v4? Can't find docs (especially since the web site is gone).
