### ISSUE TITLE
Quantum and wildcard import

### ISSUE THREAD

**Issue by eddow** [fuse-box/fuse-box#766]
When importing with wildcards (`import * as stuffs from '~/stuffs/*'`), quantum doesn't resolve the file-names as "file numbers". Though, it could do it as it is sure all the files are bundled already.
Instead of letting the `require` statement as is, it could develop the wildcard in the bundle.

So, instead of - at run-time - listing all the files that match the path, having in the quantum-bundle something like :
```js
var stuffs = {'stuffs/blung': $fsx.r(19), 'stuffs/bling': $fsx.r(7), ...};
```

**Comment by nchanged** [comment]
Yeah I though about the same, perhaps in the next iteration

**Comment by sigerello** [comment]
Hi @nchanged
Any progress on this issue?

**Comment by nchanged** [comment]
@sigerello, unfortunately, no, due to a very limited amount of requests on this issue. You can, however, keep using the basic build, nothing wrong with it, there is a very non-significant overhead at runtime tho. Depends on the size of your project.

**Comment by nchanged** [comment]
### FuseBox v4 Major Upgrade

As of today, the latest major version of FuseBox `v4` is available in `fuse-box@next`. FuseBox has undergone a full re-write from scratch, learning from its mistakes in the previous versions.

There are a lot of improvements, speed and config wise.

Get started [here](https://github.com/fuse-box/fuse-box/blob/master/docs/getting-started/get-started.md)

We are still working on the documentation and polishing before the major release. We are getting very close. And we need help testing.

```bash
npm install fuse-box@next
```

Most of the issues that I am closing have been resolved, however, if you find that your issue is still relevant in `v4` don't hesitate to re-open or (better) create a new one with `v4` configuration.
