### ISSUE TITLE
node_modules packages and sourcemaps

### ISSUE THREAD

**Issue by rs3d** [fuse-box/fuse-box#796]
Hi,

if I set 
```
FuseBox.init({
  sourceMaps: { 
  inline: false, 
  sourceRoot: "", 
  project: true, 
  vendor: true }
...})
``` 
all packages from node_modules are referenced from a `vendor` folder in sourcemap files:

![image](https://user-images.githubusercontent.com/1399149/30396263-53f584e6-98c9-11e7-84a7-ce5da61a7405.png)

`vendor` is hardcoded here:
https://github.com/fuse-box/fuse-box/blob/8134ac6d151daf98d409f09389562dc49ecc7e44/src/core/File.ts#L541

It should be `node_modules` by default.

**Comment by zigmo** [comment]
@rs3d I think this only should be used with `ìnline: true` - can you test it with this option.

**Comment by rs3d** [comment]
@zigmo nope, this option is not changing my result.

**Comment by nchanged** [comment]
@zigmo can you help with this issue?

**Comment by zigmo** [comment]
@nchanged trying to understand the issue. `/vendor` is virtual right? the projects I have here are woking fine with `inline:true`. I can see the sources in chrome. @rs3d is trying out some things with httpServer:true/false. Hope we will get more infos.

**Comment by rs3d** [comment]
@nchanged are they somehow delivered by the dev server? 
If i set the config to `inline: true` (what i don't like) **and** enable httpServer again`fuse.dev({ // httpServer: false })` it is working.
Could we change `vendor` to `node_modules` if `inline === false` and `httpServer === false`?

**Comment by nchanged** [comment]
I inline is true and vendor is true we need to expose node_modules in the httpserver

**Comment by rs3d** [comment]
Then only if vendor is true should also be working. Then i can expose node_modules by my existing server and i don't have the overhead of inlined sources, right?

**Comment by nchanged** [comment]
### FuseBox v4 Major Upgrade

As of today, the latest major version of FuseBox `v4` is available in `fuse-box@next`. FuseBox has undergone a full re-write from scratch, learning from its mistakes in the previous versions.

There are a lot of improvements, speed and config wise.

Get started [here](https://github.com/fuse-box/fuse-box/blob/master/docs/getting-started/get-started.md)

We are still working on the documentation and polishing before the major release. We are getting very close. And we need help testing.

```bash
npm install fuse-box@next
```

Most of the issues that I am closing have been resolved, however, if you find that your issue is still relevant in `v4` don't hesitate to re-open or (better) create a new one with `v4` configuration.
