### ISSUE TITLE
[Feature Request] Reset server (possibly with a button in index.html)

### ISSUE THREAD

**Issue by matt-erhart** [fuse-box/fuse-box#799]
I often do something, such as import a new module/resource, and then I have to ctrl-c the dev server, then go into task manager and manually kill the node process. Maybe then I'll delete .fusebox. Start up the server, and then manually reset the browser. 

Importing newly added resources/modules is probably a big issue, so in the short term, it'd be great to have a way to tell the dev server to clear cache, delete .fusebox, and/or load in all imports etc, and refresh the browser. Maybe just like post a 'reset' to the dev server from a little button in index.html?

**Comment by nchanged** [comment]
Why are deleting the process manually? Shouldn't be killed after you pressed CTRL+C?

I was thinking of rather fixing that issue with HMR and new files / dependencies

**Comment by matt-erhart** [comment]
@nchanged Yea, maybe it's windows git-bash thing, but I get a few left over node processes. Sometimes ctrl+c doesn't catch and I have to just close the terminal and that kind of thing. It's kind of random. 

Oh hey, fixing the new files issue would solve a lot of my use case. I think it would still be good to do a clean reset without ctrl-c. Reseting has got to be done, so it's be great to have a cleaner way to do it.

**Comment by nchanged** [comment]
### FuseBox v4 Major Upgrade

As of today, the latest major version of FuseBox `v4` is available in `fuse-box@next`. FuseBox has undergone a full re-write from scratch, learning from its mistakes in the previous versions.

There are a lot of improvements, speed and config wise.

Get started [here](https://github.com/fuse-box/fuse-box/blob/master/docs/getting-started/get-started.md)

We are still working on the documentation and polishing before the major release. We are getting very close. And we need help testing.

```bash
npm install fuse-box@next
```

Most of the issues that I am closing have been resolved, however, if you find that your issue is still relevant in `v4` don't hesitate to re-open or (better) create a new one with `v4` configuration.
