### ISSUE TITLE
[Feature] - Require Expression evaluation

### ISSUE THREAD

**Issue by calebboyd** [fuse-box/fuse-box#804]
What do you think about collecting the ast nodes passed to require (non Literal nodes) and evaluating them to a glob/regex to files acceptable to the current context? They'd then all be added to the file as dependencies.

eg. `require('./lib/' + arg)` => `./lib/**/*.{js,json}` 

For Quantum the current replacement strategy would still apply

**Comment by nchanged** [comment]
And would arg look like? We can evalulate to some extent, but what if you proved a function there? 

Can u provide some use cases?

**Comment by calebboyd** [comment]
In this case it doesn't matter what arg would look like, it would become `.*` in a regex

The most general use case is more compatibility with modules on npm. Eg. Bundling [this](https://gist.github.com/calebboyd/48d62efd1f36d137a9e0492837d81b18#file-index-js)

**Comment by calebboyd** [comment]
Here is a fairly nice view to see all the scenarios that are at least solvable

https://bigquery.cloud.google.com/savedquery/672059091411:33509720da434aabba73dce53e6f9a08

**Comment by nchanged** [comment]
Well yes, but I though people are using es6 imports nowadays more often than `require`

**Comment by calebboyd** [comment]
> The most general use case is more compatibility with modules on npm.

There are thousands of packages that use commonjs dynamic require statements.

**Comment by nchanged** [comment]
you are right, but partial evaluation is an extremely tedious business. If we want to go for something simple - that can be done, but if it's dynamic, functions, and other "pretty" stuff - then it's a mess.
For example, we can cover `__dirname` (we know that variable)

**Comment by calebboyd** [comment]
Hahaha [yeah](https://github.com/webpack/webpack/blob/master/lib/Parser.js#L85)

**Comment by nchanged** [comment]
I wasn't talking about AST parsing, why reinvent the wheel if acorn does it extremely well, it's about partial evaluation.

**Comment by calebboyd** [comment]
That link was me agreeing with you, it's the tedious partial evaluation you were referring to, not parsing.

**Comment by nchanged** [comment]
Oh... right. And all to make this work?
```
var a = "hello/"
require(a + "b.js")
```

Who does that anyway... ;-)

**Comment by nchanged** [comment]
@calebboyd are you planning on elaborating how you think it could work?

**Comment by calebboyd** [comment]
I was going to elaborate with a PR when I had some free time :)

**Comment by calebboyd** [comment]
Linking: https://github.com/nexe/nexe/issues/399

**Comment by nchanged** [comment]
### FuseBox v4 Major Upgrade

As of today, the latest major version of FuseBox `v4` is available in `fuse-box@next`. FuseBox has undergone a full re-write from scratch, learning from its mistakes in the previous versions.

There are a lot of improvements, speed and config wise.

Get started [here](https://github.com/fuse-box/fuse-box/blob/master/docs/getting-started/get-started.md)

We are still working on the documentation and polishing before the major release. We are getting very close. And we need help testing.

```bash
npm install fuse-box@next
```

Most of the issues that I am closing have been resolved, however, if you find that your issue is still relevant in `v4` don't hesitate to re-open or (better) create a new one with `v4` configuration.
