### ISSUE TITLE
Apply output macros on the result of CSSPlugin.outFile

### ISSUE THREAD

**Issue by ypconstante** [fuse-box/fuse-box#813]
The the result of outFile in the CSS plugin currently doesn't replace the usages of $name and $hash. This would be interesting to do it so it behaves just like the output configuration, and allow more generic usages of the plugin.

**Comment by henrinormak** [comment]
The hash part is especially interesting, as it would allow treating the app bundle + css bundle as a versioned release (and thus be served behind a strong cache).

**Comment by nchanged** [comment]
@henrinormak CSSPlugin output will be remove in `4.0` in favour of [Quantum CSS](https://fuse-box.org/docs/getting-started/add-css#production-build)

You can use it already now. Remove all the options from the CSSPlugin and enable `{css : true}` in your Quantum build

**Comment by nchanged** [comment]
### FuseBox v4 Major Upgrade

As of today, the latest major version of FuseBox `v4` is available in `fuse-box@next`. FuseBox has undergone a full re-write from scratch, learning from its mistakes in the previous versions.

There are a lot of improvements, speed and config wise.

Get started [here](https://github.com/fuse-box/fuse-box/blob/master/docs/getting-started/get-started.md)

We are still working on the documentation and polishing before the major release. We are getting very close. And we need help testing.

```bash
npm install fuse-box@next
```

Most of the issues that I am closing have been resolved, however, if you find that your issue is still relevant in `v4` don't hesitate to re-open or (better) create a new one with `v4` configuration.
