### ISSUE TITLE
Inconsistency between plugins macros

### ISSUE THREAD

**Issue by ypconstante** [fuse-box/fuse-box#819]
The sass macros make the replace doing a exactly replace on the key send on the options, but the css macros put a $ in the begging of the replace string. the documentation doesn't make that differentiation very clear, it would be nice to at least document it, and maybe in a future version use the same behavior to the macros.

**Comment by nchanged** [comment]
Not sure i got you, could you make an example please

**Comment by ypconstante** [comment]
https://github.com/fuse-box/fuse-box/blob/master/src/plugins/stylesheet/SassPlugin.ts#L85
https://github.com/fuse-box/fuse-box/blob/master/src/plugins/stylesheet/CSSResourcePlugin.ts#L132

The cssresource plugin is appending an `$` to the key before doing the replace, while the sass plugin makes the replace directly. So if I create a macro named `static` in the cssresource, the string `$static` is replaced by the macro content, but if the same macro is created for the sass plugin, the string `static` will be replaced.

**Comment by nchanged** [comment]
Oh that's right... gotta think how to fix that

**Comment by Shepless** [comment]
Maybe we should pull macros out into their own object that is reused by anything that needs it. That way it's consistent throughout fuse box.

**Comment by paxperscientiam** [comment]
good idea, @Shepless. would like to see it as a top-level property in options object.

**Comment by nchanged** [comment]
### FuseBox v4 Major Upgrade

As of today, the latest major version of FuseBox `v4` is available in `fuse-box@next`. FuseBox has undergone a full re-write from scratch, learning from its mistakes in the previous versions.

There are a lot of improvements, speed and config wise.

Get started [here](https://github.com/fuse-box/fuse-box/blob/master/docs/getting-started/get-started.md)

We are still working on the documentation and polishing before the major release. We are getting very close. And we need help testing.

```bash
npm install fuse-box@next
```

Most of the issues that I am closing have been resolved, however, if you find that your issue is still relevant in `v4` don't hesitate to re-open or (better) create a new one with `v4` configuration.
