### ISSUE TITLE
Cannot import fuse.js library

### ISSUE THREAD

**Issue by mattoni** [fuse-box/fuse-box#838]
Hey guys,

Mentioned it in gitter a couple days ago, still haven't been able to get a workaround so I figured I'd open an issue so we can track it.

I'm unable to import this package: http://fusejs.io/

Seems like it's causing havoc in the import and errors out with `Uncaught (in promise) Package not found fuse.js` 

@nchanged tried your solution of creating an imports file, that didn't work either. Let me know if I can get you some more diagnostic info. Thanks!

**Comment by calebboyd** [comment]
Interesting, It uses the webpack UMD wrapper...

**Comment by mattoni** [comment]
I think it's the `.js` part causing it to mess up, since I've not had this kind of issue with any other package.

**Comment by TombolaShepless** [comment]
@mattoni could you provide a small demo repository? It would be a huge help for us to try and find out what is causing the problems.

**Comment by devmondo** [comment]
what is funny is that i cant install it with `npm i fuse.js` as there is already file `fuse.js` in my project!

**Comment by devmondo** [comment]
after installing with `npm i git+https://git@github.com/krisk/Fuse.git` and importing using `import * as fuse from "fuse.js";` there is no error, but lib is undefined

**Comment by devmondo** [comment]
ok i confirm, i renamed the `fuse.js` folder in `node_modules` to `fuse` and imported it as `import * as fuse from "fuse";` and now i can console log it and see it

**Comment by mattoni** [comment]
problem is i can't do that if i want the typescript definitions from definitely typed :/ let me know when there is some progress on this :)

**Comment by nchanged** [comment]
### FuseBox v4 Major Upgrade

As of today, the latest major version of FuseBox `v4` is available in `fuse-box@next`. FuseBox has undergone a full re-write from scratch, learning from its mistakes in the previous versions.

There are a lot of improvements, speed and config wise.

Get started [here](https://github.com/fuse-box/fuse-box/blob/master/docs/getting-started/get-started.md)

We are still working on the documentation and polishing before the major release. We are getting very close. And we need help testing.

```bash
npm install fuse-box@next
```

Most of the issues that I am closing have been resolved, however, if you find that your issue is still relevant in `v4` don't hesitate to re-open or (better) create a new one with `v4` configuration.
