### ISSUE TITLE
CSSPlugin optimization : bundle CSS by media query

### ISSUE THREAD

**Issue by jsamr** [fuse-box/fuse-box#843]
``` html
<link href="style-all.css" rel="stylesheet" media="all">
<link href="style-print.css" rel="stylesheet" media="print">
<link href="style-portrait.css" rel="stylesheet" media="orientation:portrait">
<link href="style-mobile.css" rel="stylesheet" media="(max-width: 320px)">
<link href="style-tablet.css" rel="stylesheet" media="(min-width: 320px) and (max-width: 740px)">
<link href="style-wide.css" rel="stylesheet" media="(min-width: 740px)">
```

An option `bundleByMQ` or `groupByMQ` would chunk CSS into **n +1** files where **n** is the number of media query selectors in the whole CSS (the latest targets all media).
This optimization is suggested by [developers.google.com](https://developers.google.com/web/fundamentals/performance/critical-rendering-path/render-blocking-css) website to minimize the critical rendering path.

**Comment by nchanged** [comment]
And how one would define that option?

**Comment by sveinburne** [comment]
> And how one would define that option?

I have to say I don't really know ; it's kind of an API design flavour^^
What about : 
``` javascript
plugins: [
  CSSPlugin({
    group: "style-$mediaQuery.css"
  })
]
```
?

**Comment by sveinburne** [comment]
He could also define alias to have sensible names:
``` javascript
plugins: [
  CSSPlugin({
    group: "style-$mediaQuery.css",
    mediaQueryAliases: {
      portrait: 'orientation:portrait',
      mobile: '(max-width: 320px)',
      tablet: '(min-width: 320px) and (max-width: 740px)',
      wide: '(min-width: 740px)'
    }
  })
]
```

**Comment by nchanged** [comment]
### FuseBox v4 Major Upgrade

As of today, the latest major version of FuseBox `v4` is available in `fuse-box@next`. FuseBox has undergone a full re-write from scratch, learning from its mistakes in the previous versions.

There are a lot of improvements, speed and config wise.

Get started [here](https://github.com/fuse-box/fuse-box/blob/master/docs/getting-started/get-started.md)

We are still working on the documentation and polishing before the major release. We are getting very close. And we need help testing.

```bash
npm install fuse-box@next
```

Most of the issues that I am closing have been resolved, however, if you find that your issue is still relevant in `v4` don't hesitate to re-open or (better) create a new one with `v4` configuration.
