### ISSUE TITLE
NodeJs "stream" lib in browser

### ISSUE THREAD

**Issue by Janaka-Steph** [fuse-box/fuse-box#847]
Hello,

I have troubles importing / using this lib `https://github.com/DigixGlobal/truffle-lightwallet-provider` in the custom modules folder. 
More precisely, customModules/protocol/truffle.js, line 4
I use Typescript in `src` but need to use Javascript in `customModules`.  

In fuse.js, I specify `polyfillNonStandardDefaultUsage: true` and `useJsNext: true`. 

Error is: `Uncaught TypeError: Cannot read property 'prototype' of undefined`

The compiled code causing the issue is 
```
FuseBox.pkg("inherits", {}, function(___scope___){
___scope___.file("inherits_browser.js", function(exports, require, module, __filename, __dirname){

if (typeof Object.create === 'function') {
  // implementation from standard node.js 'util' module
  module.exports = function inherits(ctor, superCtor) {
    ctor.super_ = superCtor
    ctor.prototype = Object.create(superCtor.prototype, {
      constructor: {
        value: ctor,
        enumerable: false,
        writable: true,
        configurable: true
      }
    });
  };
```

Step to reproduce:
`git clone https://github.com/Janaka-Steph/dapp-boilerplate.git`
`git checkout update`
`npm i`
`npm run dev`

fusebox: ^2.3.1
node: 8.6.0

Thank you for any help

**Comment by nchanged** [comment]
Ok, it's because of that line
```
var Transform = require('stream').Transform
```
We don't a polyfill for that lib

**Comment by dynasource** [comment]
this issue can be solved filling the customModules with the following node packages:
-  https://github.com/nodejs/readable-stream (-> /customModules/stream)
- https://www.npmjs.com/package/util  (-> /customModules/util)

important note: in case of an error 'Package Util can not be found', you have to import the Util package somewhere in your App (import util = require("util")), as it is required by the readable stream package and not automatically loaded.

**Comment by nchanged** [comment]
### FuseBox v4 Major Upgrade

As of today, the latest major version of FuseBox `v4` is available in `fuse-box@next`. FuseBox has undergone a full re-write from scratch, learning from its mistakes in the previous versions.

There are a lot of improvements, speed and config wise.

Get started [here](https://github.com/fuse-box/fuse-box/blob/master/docs/getting-started/get-started.md)

We are still working on the documentation and polishing before the major release. We are getting very close. And we need help testing.

```bash
npm install fuse-box@next
```

Most of the issues that I am closing have been resolved, however, if you find that your issue is still relevant in `v4` don't hesitate to re-open or (better) create a new one with `v4` configuration.
