### ISSUE TITLE
Source maps are not generated for the vendor bundle

### ISSUE THREAD

**Issue by eyamenko** [fuse-box/fuse-box#849]
Hi there,

I'm using the latest Fuse Box (v2.3.3).

Here is my simple fuse.js:

```
const {FuseBox, QuantumPlugin, CSSPlugin} = require("fuse-box");

const production = process.env.NODE_ENV === "production";

const fuse = FuseBox.init({
    target: "browser",
    homeDir: "Client",
    output: "wwwroot/$name.js",
    cache: !production,
    sourceMaps: !production,
    plugins: [
        CSSPlugin(),
        production && QuantumPlugin({
            uglify: true,
            treeshake: true,
            bakeApiIntoBundle: "vendor"
        })
    ]
});

if (!production)
    fuse.dev();

const vendor = fuse.bundle("vendor", "~ index.tsx");

if (!production)
    vendor.hmr();

const app = fuse.bundle("app", "!> [index.tsx]");

if (!production)
    app.hmr().watch();

fuse.run();
```

After running the producer, source maps for app bundle are generated fine, but there are no source maps for vendor bundle.

**Comment by nchanged** [comment]
http://fuse-box.org/page/configuration#sourcemaps
It may take up to 1 minute to generate sourcemaps.

**Comment by sveinburne** [comment]
![image](https://user-images.githubusercontent.com/3646758/31344768-a0c0d2cc-ace1-11e7-8cee-e2c80d4a9650.png)

As a side note, even though `vendor: false` option is provided, a reference is provided in the `vendor.js`, triggering this warning (v2.3.3).

![image](https://user-images.githubusercontent.com/3646758/31344608-252324ee-ace1-11e7-9dda-0a35d7b32b56.png)

**Comment by nchanged** [comment]
@sveinburne i guess you need to clear the cache folder, does it help?

**Comment by sveinburne** [comment]
@nchanged it doesn't unfortunately !

**Comment by nchanged** [comment]
### FuseBox v4 Major Upgrade

As of today, the latest major version of FuseBox `v4` is available in `fuse-box@next`. FuseBox has undergone a full re-write from scratch, learning from its mistakes in the previous versions.

There are a lot of improvements, speed and config wise.

Get started [here](https://github.com/fuse-box/fuse-box/blob/master/docs/getting-started/get-started.md)

We are still working on the documentation and polishing before the major release. We are getting very close. And we need help testing.

```bash
npm install fuse-box@next
```

Most of the issues that I am closing have been resolved, however, if you find that your issue is still relevant in `v4` don't hesitate to re-open or (better) create a new one with `v4` configuration.
