### ISSUE TITLE
Support multiple tasks through args

### ISSUE THREAD

**Issue by freehuntx** [fuse-box/fuse-box#874]
If i see it correctly, currently you can just run one task with sparky using the arguments. (e.g: node fuse build:all)
Wouldn't it be usefull to allow define multiple tasks just like in Sparky itself?

e.g: 
node fuse clean:api test:api build:api
or
node fuse &clean:api &clean:client test:all build:all

In my opinion, the more features a bundler offers, the better :)
What you guys think about?

**Comment by nchanged** [comment]
@freehuntx i think it can done, however i don't see how one would really benefit from it ;-)

**Comment by freehuntx** [comment]
Well i think we should let decide the users if they benefit from it :)
I just have the feeling, giving users freedom to choose how they want to use something, is not a bad thing :D 
(Thats actually why i love JavaScript so much! So many ways to archieve your thing)

For me, there is no reason to not allow it :o 
It wont break something and its not hard to do ^^

But if you say you dont like it, im ok with it tho :P

**Comment by nchanged** [comment]
### FuseBox v4 Major Upgrade

As of today, the latest major version of FuseBox `v4` is available in `fuse-box@next`. FuseBox has undergone a full re-write from scratch, learning from its mistakes in the previous versions.

There are a lot of improvements, speed and config wise.

Get started [here](https://github.com/fuse-box/fuse-box/blob/master/docs/getting-started/get-started.md)

We are still working on the documentation and polishing before the major release. We are getting very close. And we need help testing.

```bash
npm install fuse-box@next
```

Most of the issues that I am closing have been resolved, however, if you find that your issue is still relevant in `v4` don't hesitate to re-open or (better) create a new one with `v4` configuration.
