### ISSUE TITLE
Incorrect resolving paths (Angular)

### ISSUE THREAD

**Issue by unlight** [fuse-box/fuse-box#88]
Version: 1.3.51
```
import { TestBed } from '@angular/core/testing';
```
Actual: `node_modules\@angular\core\testing\index.js`
Expected: `node_modules\@angular\core\bundles\core-testing.umd.js`
Because contents of `node_modules\@angular\core\testing\package.json`
```
{"main": "../bundles/core-testing.umd.js"} 
```

**Comment by nchanged** [comment]
Hm.. so you are saying that any folder can contain a package.json that should be treated as well?

**Comment by unlight** [comment]
I suppose yes.
https://github.com/substack/node-resolve/blob/master/lib/sync.js#L54

**Comment by nchanged** [comment]
Fair enough, will be fixed

**Comment by nchanged** [comment]
That's a big issue... I must admit, requires a lot of thinking there. =(

**Comment by unlight** [comment]
Maybe create some kind of `Remap plugin` as stop gap solution?
```
{
 '@angular/platform-browser/testing': '@angular/platform-browser/bundles/platform-browser-testing.umd.js'
}
```
Can you point me to the right direction where to start, if it is possible?

**Comment by nchanged** [comment]
You want to try to fix it? 

I actually have a branch there issue88, where i solved the issue at bundle time. But the front end still does not understand that instead of pointing to index.js it has to point to a different file. That's the problem. We have this [stuff](http://fuse-box.org/#custom-modules-folder)

I was thinking of making it in the config as well like you suggested, but the loader is still a problem. 
In order for you to proceed, you can just point to the actual file in that package.json. 

Let's think about it... I am working on different approaches still.

**Comment by nchanged** [comment]
https://github.com/fuse-box/fuse-box/issues/324

**Comment by devmondo** [comment]
this is solved now, please reopen otherwise :)
