### ISSUE TITLE
Old local styles coming from cache when importing styles from node_modules

### ISSUE THREAD

**Issue by ttamminen** [fuse-box/fuse-box#893]
I have created reproduce steps to [this repository](https://github.com/ttamminen/fusebox-sass-bug/tree/master)

## Overview

The problem is that when I make changes to the sass-file the changes are not in the bundle when I run the build process again.

## Possible cause

I have a TSX entry file that imports styles

```
require('es6-promise').polyfill()
require('babel-polyfill')

import * as React from 'react'

require('./styles/index.scss')
import 'leaflet/dist/leaflet.css'
```

If I make changes to the index.scss file and re-build everything. I get old styles.

Everything works correctly if I remove the last line `import 'leaflet/dist/leaflet.css'`.

**Comment by nchanged** [comment]
@ttamminen I investigated the issue. It turns out there is no way for SassPlugin to pick up the changes unless it's actually watched `.watch()`  as it gives the latest changed file. When launching `fuse.js` with `cache : true` there is this issue, indeed. When creating a build, you can just disable cache and everything will work as expected. Moreover, it's working with HMR without any problems.

**Comment by nchanged** [comment]
### FuseBox v4 Major Upgrade

As of today, the latest major version of FuseBox `v4` is available in `fuse-box@next`. FuseBox has undergone a full re-write from scratch, learning from its mistakes in the previous versions.

There are a lot of improvements, speed and config wise.

Get started [here](https://github.com/fuse-box/fuse-box/blob/master/docs/getting-started/get-started.md)

We are still working on the documentation and polishing before the major release. We are getting very close. And we need help testing.

```bash
npm install fuse-box@next
```

Most of the issues that I am closing have been resolved, however, if you find that your issue is still relevant in `v4` don't hesitate to re-open or (better) create a new one with `v4` configuration.
