### ISSUE TITLE
[Discussion] Using dynamic imports for code splitting

### ISSUE THREAD

**Issue by traverse** [fuse-box/fuse-box#895]
@nchanged , @devmondo and I had a discussion about `import()` on gitter pertaining to my specific use case. 

With `webpack` you can use the dynamic import statement to do code splitting for you and it's something that I miss with `fuse-box`. 

For example the project I'm working on consists of several layers of lazily loaded React components. Doing a `.split()` for every lazily loaded component or doing a dynamic import and just copying them over to the dist folder isn't maintainable in my opinion.

@nchanged had the following example of what it **could** be like `import('./filename', {copy : true})`.

For me it's mainly about `import()` enabling you to do code splitting in an easy way.

If people have ideas or input you're welcome to chime in.

**Comment by nchanged** [comment]
I Would suggest a breaking change in FuseBox 3.0 on which we start working right after the upcoming release.
* Remove `.split` entirely from fuse config
* Make an automatic/smart splitting

Let's say we have 2 components
* `FooComponent.ts` uses Utils.ts that is located somewhere in `./utils/` folder
* `BarComponents.ts` uses the same Utils.ts, and `moment` library that is referenced ONLY in that bundle and related dependencies

```ts
import("./components/FooComponent")
import("./components/BarComponent")
```

In the example above FuseBox would leave `Utils.ts` in the master bundle as it's a shared file but bundle `moment` into the second one as it's the only place where that lib is referenced. Both bundles would have a name based on their entry point file name (hashed) so `48ek87.js` and `3kj9dj.js`

FuseBox would enable the splitting mode if `./components/FooComponent` resolves to a javascript file, otherwise, it will try to load a file asynchronously (if a file is in the dist folder, CSS e.t.c) Long story short, code splitting config will be created automatically and the structure will be written into `manifest.json` by Quantum.

Physical code splitting will happen when using Quantum, development mode would preserve all files in the main bundle keeping the source maps intact.

**Comment by leon-andria** [comment]
Personnaly, i would not do like that. The splitting is good and import is standard. So we should not change the current working state.
However, we should think more about strategy abstraction that we can instrument import, this allows to anyone to have his own convention by inplementation a strategy.
If we make the pipeline with a great open API, we dont break anything.

**Comment by nchanged** [comment]
@leon-andria well technically the setup above wouldn't break anything, one should just remove `.split` from the config is all. Everything else should come naturally

**Comment by leon-andria** [comment]
Having a named split is really important. Putting extra param on import will be a mess.

**Comment by leon-andria** [comment]
My advice is to make abstraction.

**Comment by nchanged** [comment]
@leon-andria did you see any extra params in my proposal? Zero

**Comment by leon-andria** [comment]
No, i mention for the first proposal with the import.
Doing automatic split without controlling it is really hell. How are you going to distinguish a basic import versus bundles? And how to guve control to the developpers to manage its bundles regarding his application architecture?
Sometimes it's good to have magic things but having a better control of what being bundled is preferred. This is my opinion but cant be for others.
The moment you do import as you suggest, everyone will do import dynamically because everything is in a separate file everytime and the concept of bundle is dead.
Like nowadays, http2 is the trend, requesting many files is not an issues...
Take time to think about it and define a well roadmap.

**Comment by traverse** [comment]
@leon-andria Basically a bundle would consist of packages you imported using `import package from 'package'` since those are required to run the code in the module anyway. Packages imported using `import('package')` means they aren't required instantly by the module and thus split off into a separate bundle. In my opinion this feels like a sane way to do bundling.

**Comment by mattoni** [comment]
Im interested in this as well, and maybe getting a complex demo set up where we can somehow split off states and routes until the file is requested. 

Just to show how messy this can get, here's what I'm doing in my main project:

![image](https://user-images.githubusercontent.com/5110855/31907722-7c6ee0d6-b7e9-11e7-87df-2938296f3673.png)

and then in my fuse config:
![image](https://user-images.githubusercontent.com/5110855/31907746-93ca7e16-b7e9-11e7-9367-49142ef00524.png)

It "works", but as my app has grown this has gotten more and more complex. There are no other easy solutions with fuse unfortunately. My routes are generated dynamically off the defined bundles, but it's monolithic now.

I understand your concerns @leon-andria, because it is important to know what splits are occurring. Fusebox does the manifest, but what might be cool is for it to generate a typescript definition file with the string names of the imports it generates, so that you can have typed bundle names to be used throughout your application. 

That way in your app you can do a regular `await import('index.ts')`  and split an entire bundle, but also have that list of names + full paths generated in case you want them.

My issue with how webpack does it is they use those custom comments that relies on essentially meta information to do what should be done in code imo. 

Anyway looking forward to this. I'd be happy to help test in my redux seed example.

**Comment by mattoni** [comment]
Another fun thing you could do with your proposal @nchanged is locale files. For example if I'm building a multi-lingual site, I can dynamically load in the correct language file simply by doing something like:

```
```

**Comment by mattoni** [comment]
@nchanged true, might fit better with a .json file or something. still, I'd love to figure out how we can simplify all this :)

**Comment by traverse** [comment]
@mattoni your locales example actually works with webpack which is very neat. Webpack only allows this up to a certain point though, it doesn't support fully dynamic paths.

**Comment by leon-andria** [comment]
@mattoni @traverse I understand the use-cases you have guys, and it makes sense you think in this way. And the first attempt answer from @nchanged is not a bad idea to make a smart split. I'm concerned because not having the control of what to be in the bundle other in the all application is scared.
Let's take the example of @mattoni or @traverse with huge application as it is splited in many bundles.
As @nchanged said in his example, utils will go to the master. Imagine that some bundles have Deps on same modules but they not often used like going to billing or whatever section of you application.
Does it make sense that these modules go directly to the master bundle ? So, your master bundle will hit all the payload of modules that are only used 1 time per month ? And we will have, why my master bundle is so big? At this stage, Fusebox doesn't have the luxury to have bundle analyzer like Webpack :-)
I don't want to be the bad guy but I try to find out the limit where is the Pros & Cons.
What i'm asking to @nchanged is to have a fine grained control of what to be in my bundle. The first time we talk about code splitting, i wrote a document how i hope it should be.

You develop your application by using "import" without worrying about it. And FuseBox will bundle like what @nchanged suggested above BUT without to be smart, i mean utils should stay on both components. You may say now, hey, many redundant modules, true. However, FuseBox should provide a built-in analyzer Map for all bundles. But this is not enough, the analyzer with UI will help to optimize your bundle strategy overall your application and this optimize is what the develop decide where a module goes, in a master or another bundle and so on. The optimization will generate manifest that serve as reference for futur optimization that preparing releases.
I think, you notice how i'm insisting on the Analyzer, it's the key and also, having ability to drive where the modules go into the bundle.
That's it, hope you understand how i see it to be.

**Comment by mattoni** [comment]
@leon-andria might be smart to allow overrides. Do what @nchanged said by default, and allow the OPTION to force it out of master bundle and clone it into each split bundle, since I feel that case will be rare.

@traverse @nchanged maybe down the road we can do like webpack and have partial evaluation on the route (until it gets dynamic) to see if that folder exists at least, and if it does just throw those files into the master bundle and assume the user knows what they are doing.

**Comment by leon-andria** [comment]
@mattoni You understand me but it's not rare, trust me, we did that a lot. To talk about overrides, we should think it like a "redirect", @nchanged I think you can start with that by having a manifest for redirection so that in each process, you can try to match the rule of redirect.
After, a UI Analyzer :-) Sooner it's Christmas

**Comment by nchanged** [comment]
@traverse I don't think it will work, what will work with webpack is
```js
var foo = "foo"
import(foo + ".js")
```
where a question pops out: why would anyone use it this way

**Comment by traverse** [comment]
@nchanged doing the following actually works:
```javascript
const translationFile = await import(`./locales/${locale}.json`)
```
Since you're partially specifying a static path webpack can actually figure it out.

**Comment by nchanged** [comment]
@traverse but then it will bundle all locales within the reach, i am talking about what's actually is required by user

**Comment by mattoni** [comment]
Here's how I'm defining my routes for my big application:
![image](https://user-images.githubusercontent.com/5110855/32138761-bb65eaca-bbed-11e7-84f1-993d6c9e673e.png)
where asyncBundle/additionalBundles are the names of my pre-defined split bundles above.

I'm imaging a scenario where I can do like... 
`asyncBundle: async () => import("../containers/ContainerConfig.tsx")` and when the route is loaded, run that function and get my bundle, but have it split automatically simply for being defined.

This allows me to see IMMEDIATELY what file it's importing, avoid a massive config, and keep the same functionality as before while utilizing modern TS features.

**Comment by zeniroy** [comment]
It is amazing feature that i really need. At this time, split is not valuable. I must define all the libraries that are bundled by myself for shrink bundle size. It means whenever i change my source with dependency, i have to change my fuse-box configuration. 

There can be some options based on smart splitting for @leon-andria comments. I want to choice to use split automatically or manually.

**Comment by nchanged** [comment]
https://github.com/fuse-box/fuse-box/issues/926
