### ISSUE TITLE
Feature Request: CLI Commands during dev server.

### ISSUE THREAD

**Issue by TheGrimSilence** [fuse-box/fuse-box#898]
So one of the smaller but kind of repetitive things during development is altering the bundler configuration. 

With Fusebox, you have to completely stop and start the build again and again. A cool feature would be if the terminal runs the script and while running the server or HMR, etc, it was actually waiting for commands. 

For example, instead of having to press CTRL+C, verify you want to stop the script (even though it stops anyway because... Windows), and restart, Fusebox actually waited for commands such as **X** | **C** to stop, **R** to restart the build, etc.

**Comment by nchanged** [comment]
### FuseBox v4 Major Upgrade

As of today, the latest major version of FuseBox `v4` is available in `fuse-box@next`. FuseBox has undergone a full re-write from scratch, learning from its mistakes in the previous versions.

There are a lot of improvements, speed and config wise.

Get started [here](https://github.com/fuse-box/fuse-box/blob/master/docs/getting-started/get-started.md)

We are still working on the documentation and polishing before the major release. We are getting very close. And we need help testing.

```bash
npm install fuse-box@next
```

Most of the issues that I am closing have been resolved, however, if you find that your issue is still relevant in `v4` don't hesitate to re-open or (better) create a new one with `v4` configuration.
