### ISSUE TITLE
Missing modules silently return null instead of throwing

### ISSUE THREAD

**Issue by calebboyd** [fuse-box/fuse-box#902]
When bundling a project like https://github.com/theturtle32/WebSocket-Node

Fusebox will break the control flow of modules like: 
https://github.com/theturtle32/WebSocket-Node/blob/master/lib/BufferUtil.js

If fusebox isn't able to resolve a dependency a warning is issued but null is still returned for a particular missing require.

This will cause a null reference exception here: https://github.com/theturtle32/WebSocket-Node/blob/d941f975e8ef6b55eafc0ef45996f4198013832c/lib/WebSocketFrame.js#L17

I would propose that if a file fails to resolve, then at runtime the module loader throw an error when that file is requested.

This would match the behavior of SystemJS, Webpack, and commonjs (node).

**Comment by nchanged** [comment]
👍

**Comment by nchanged** [comment]
### FuseBox v4 Major Upgrade

As of today, the latest major version of FuseBox `v4` is available in `fuse-box@next`. FuseBox has undergone a full re-write from scratch, learning from its mistakes in the previous versions.

There are a lot of improvements, speed and config wise.

Get started [here](https://github.com/fuse-box/fuse-box/blob/master/docs/getting-started/get-started.md)

We are still working on the documentation and polishing before the major release. We are getting very close. And we need help testing.

```bash
npm install fuse-box@next
```

Most of the issues that I am closing have been resolved, however, if you find that your issue is still relevant in `v4` don't hesitate to re-open or (better) create a new one with `v4` configuration.
