### ISSUE TITLE
Fusebox not loading JSON within a node module

### ISSUE THREAD

**Issue by calebboyd** [fuse-box/fuse-box#904]
JSON files within a module don't seem to resolve...
Instead of throwing (#902) the value is `null`

See example repo:
https://github.com/calebboyd/fusebox-json

**Comment by calebboyd** [comment]
This is clearly a bug.

**Comment by phamtm** [comment]
@calebboyd shouldn't you require `test-module` using `var test = require("./test-module")`, notice the `./` there? 

I think without specifying the relative path then `fusebox` may think it is a third party module. Refers to https://nodejs.org/api/modules.html#modules_loading_from_node_modules_folders . So the problem should be that `fusebox` does not throws an error/warning when some module is not found.

**Comment by nchanged** [comment]
@phamtm you are right
@calebboyd you either use `aliases` or `modulesFolder`

**Comment by calebboyd** [comment]
@phamtm yeah, typo, corrected the issue still persists, Looks like the latest (2.5.0-beta.1) also introduces #791 again.

Its probably time to add typescript as a peer dependency... /cc @devmondo

**Comment by calebboyd** [comment]
@phamtm Actually it wasn't a typo...(just back from holiday -- forgot how It was setup) 

Its copied into node_modules - see https://github.com/calebboyd/fusebox-json/blob/master/package.json#L6

I did that to illustrate it with behavior with a node module. But it looks like its present as a non-node module as well.

**Comment by dattanchu** [comment]
I am running into the same problem. Fuse will not resolve .json files shipped in a package installed.

The fix for the equivalent problem in Webpack is to add .json to resolve.extensions

```
{
  resolve: {
    extensions: [".js", ".json", ...]
  }
}
```

**Comment by soanaphikeste** [comment]
The solution/workaround seems to be the JSONPlugin: https://fuse-box.org/page/json-plugin#usage

When I include it in my config, everything works as expected.

**Comment by grossbart** [comment]
Node modules `require`ing JSON config files no longer break with the JSONPlugin, however it breaks my requirement of loading JSON asynchronously using the CopyPlugin. At the moment it doesn't seem possible to have both because JSONPlugin doesn't support any options to include/exclude files and folders.

**Comment by nchanged** [comment]
You can a specific path matching your files, first argument in the chain

**Comment by grossbart** [comment]
I see, thank you for the hint @nchanged. Something like this is what I'm using now:

```
plugins: [
    [ "node_modules/**.json", JSONPlugin() ],
    CopyPlugin(…),
    …
]
```

**Comment by nchanged** [comment]
### FuseBox v4 Major Upgrade

As of today, the latest major version of FuseBox `v4` is available in `fuse-box@next`. FuseBox has undergone a full re-write from scratch, learning from its mistakes in the previous versions.

There are a lot of improvements, speed and config wise.

Get started [here](https://github.com/fuse-box/fuse-box/blob/master/docs/getting-started/get-started.md)

We are still working on the documentation and polishing before the major release. We are getting very close. And we need help testing.

```bash
npm install fuse-box@next
```

Most of the issues that I am closing have been resolved, however, if you find that your issue is still relevant in `v4` don't hesitate to re-open or (better) create a new one with `v4` configuration.
