### ISSUE TITLE
Importing vue doesn't work

### ISSUE THREAD

**Issue by matteodem** [fuse-box/fuse-box#907]
nodejs version: `v.6.11.1`

reproduction repository https://github.com/matteodem/vue-import-fuse-box

Right now I get an error that `Vue` equals `undefined`. Changing L1 on src/index.js fixes it, but it's incorrect and HMR fails after code change.

```js
import * as Vue from 'vue'
```

It'd be really awesome to use fuse-box for my upcoming project!

**Comment by devmondo** [comment]
try `import * as Vue from 'vue/dist/vue.common.js'`

check the comparison of builds https://vuejs.org/v2/guide/installation.html#Explanation-of-Different-Builds

**Comment by matteodem** [comment]
What's the technical answer as to why it works with webpack and not with fuse-box?

**Comment by nchanged** [comment]
@matteodem the official plugin is tied up to webpack, we are doing our best to port it to fusebox.

**Comment by matteodem** [comment]
It'd be awesome to get it to work by writing

```js
import Vue from 'vue'
```

**Comment by devmondo** [comment]
@matteodem  you could use fuse alias feature to do that
```
FuseBox.init({
    alias: {
        "vue": "vue/dist/vue.common.js",
    },
})
```

**Comment by nchanged** [comment]
### FuseBox v4 Major Upgrade

As of today, the latest major version of FuseBox `v4` is available in `fuse-box@next`. FuseBox has undergone a full re-write from scratch, learning from its mistakes in the previous versions.

There are a lot of improvements, speed and config wise.

Get started [here](https://github.com/fuse-box/fuse-box/blob/master/docs/getting-started/get-started.md)

We are still working on the documentation and polishing before the major release. We are getting very close. And we need help testing.

```bash
npm install fuse-box@next
```

Most of the issues that I am closing have been resolved, however, if you find that your issue is still relevant in `v4` don't hesitate to re-open or (better) create a new one with `v4` configuration.
