### ISSUE TITLE
Ability to completely remove specified function from bundled code

### ISSUE THREAD

**Issue by mattoni** [fuse-box/fuse-box#908]
I'm proposing adding the ability to remove a specified function call completely from the bundled output.

My use case is, say I want to add a logger to my browser application:

```
function log(level="warn", message) {
console.log(message ...);
}
```

Great, but now all over my application, I'll have 
`log ("warn", "this is a warning");`

What'd be great is if in FB I can say, "remove all calls AND the definition for the log function"

That way, the overhead is removed completely for prod builds.

**Comment by mattoni** [comment]
Maybe do something like (this)[https://github.com/4Catalyzer/babel-plugin-dev-expression]

**Comment by nchanged** [comment]
### FuseBox v4 Major Upgrade

As of today, the latest major version of FuseBox `v4` is available in `fuse-box@next`. FuseBox has undergone a full re-write from scratch, learning from its mistakes in the previous versions.

There are a lot of improvements, speed and config wise.

Get started [here](https://github.com/fuse-box/fuse-box/blob/master/docs/getting-started/get-started.md)

We are still working on the documentation and polishing before the major release. We are getting very close. And we need help testing.

```bash
npm install fuse-box@next
```

Most of the issues that I am closing have been resolved, however, if you find that your issue is still relevant in `v4` don't hesitate to re-open or (better) create a new one with `v4` configuration.
