### ISSUE TITLE
Make FuseBox use some tsconfig settings

### ISSUE THREAD

**Issue by freehuntx** [fuse-box/fuse-box#910]
Some features of typescript are directly usable in fusebox.
It would be cool if fusebox uses them, if they are not explicitly set in fusebox itself.

For example:
- Setting paths in tsconfig, sets alias in fusebox
- Hash from tsconfig, sets hash from fusebox
- Sourcemap from tsconfig, sets sourcemap from fusebox
- Setting base/rooturl sets homedir from fusebox (?) // This one may be not good
- Outdir sets output from fusebox

Disabling this "resolving feature" could be possible through an option.
E.g: disableTSconfigResolving

And of course setting things in fusebox, has always highest priority

**Comment by nchanged** [comment]
@freehuntx great idea for FuseBox 3.0!

**Comment by xdave** [comment]
Interesting, I was just wondering if fuse-box supported the same thing as https://www.npmjs.com/package/tsconfig-paths

Would be super useful.  Right now I'm generating a list of aliases manually, but I wish I could do it automatically.

**Comment by nchanged** [comment]
### FuseBox v4 Major Upgrade

As of today, the latest major version of FuseBox `v4` is available in `fuse-box@next`. FuseBox has undergone a full re-write from scratch, learning from its mistakes in the previous versions.

There are a lot of improvements, speed and config wise.

Get started [here](https://github.com/fuse-box/fuse-box/blob/master/docs/getting-started/get-started.md)

We are still working on the documentation and polishing before the major release. We are getting very close. And we need help testing.

```bash
npm install fuse-box@next
```

Most of the issues that I am closing have been resolved, however, if you find that your issue is still relevant in `v4` don't hesitate to re-open or (better) create a new one with `v4` configuration.
