### ISSUE TITLE
Allow auto-importing an aliased package or module

### ISSUE THREAD

**Issue by matthiasak** [fuse-box/fuse-box#932]
so, I have a work library im trying to build through fusebox, and I've got some aliases like so:

```js
const alias = {
    'X.models.Collection': '~/models/Collection',
    'X.models.DataSource': '~/models/DataSource',
    'X.models.Query': '~/models/Query',
    'X.models.OrderBy': '~/models/OrderBy',
    'X.models.User': '~/models/User',
    'X.models.Template': '~/models/Template',
    'X.models.CommandResult': '~/models/CommandResult',
    'X.models.ResourceDescription': '~/models/ResourceDescription',
    'X.models.Settings': '~/models/Settings',
}

const autoImport = {
    'Query': 'X.modules.Query'
}

FuseBox.init({
    alias,
    autoImport
})
```

if I write a file and just use `Query` somewhere I get the error that `X.modules.Query is not installed`.

Can we have the auto-importing feature include aliased packages/modules?

**Comment by nchanged** [comment]
### FuseBox v4 Major Upgrade

As of today, the latest major version of FuseBox `v4` is available in `fuse-box@next`. FuseBox has undergone a full re-write from scratch, learning from its mistakes in the previous versions.

There are a lot of improvements, speed and config wise.

Get started [here](https://github.com/fuse-box/fuse-box/blob/master/docs/getting-started/get-started.md)

We are still working on the documentation and polishing before the major release. We are getting very close. And we need help testing.

```bash
npm install fuse-box@next
```

Most of the issues that I am closing have been resolved, however, if you find that your issue is still relevant in `v4` don't hesitate to re-open or (better) create a new one with `v4` configuration.
