### ISSUE TITLE
resolve.modules in fuse-box

### ISSUE THREAD

**Issue by misantronic** [fuse-box/fuse-box#940]
Just like webpack offers multiple modules-folders with [resolve.modules](https://webpack.js.org/configuration/resolve/#resolve-modules), is there a way to achieve this with fuse-box?

I need something like that:

`modules: ['.', 'node_modules', './src/my-module']`

**Comment by nchanged** [comment]
currently, we have `customModules` folder which accepts only 1 folder, but we can tweak it to accept multiple

**Comment by misantronic** [comment]
is `customModules` compatible with v.2.4.0. I can't find it in the docs.

**Comment by nchanged** [comment]
@misantronic sorry ;-) http://fuse-box.org/page/configuration#custom-modules-folder
modulesFolder

**Comment by devmondo** [comment]
yep multi-folders is really really important.

**Comment by freehuntx** [comment]
I really like this!
Typescript has something like this.
Its called "paths" where you can define some kind of mather for it.
It would then be possible to adopt that option from the typescript config. (Parsing its path option)

**Comment by nchanged** [comment]
We have plans on automatic aliasing based on tsconfig

**Comment by scarletsky** [comment]
@nchanged I want this feature too. I'm from webpack, and it's common to write the following code after you set `resolve.modules`.

```
import xxx from 'components/xxx';
```

I am also using decorators too, and I have the same issue with https://github.com/fuse-box/fuse-box/issues/991 after setting `modulesFolder`...

I have no idea how to solve it... 😭

**Comment by nchanged** [comment]
### FuseBox v4 Major Upgrade

As of today, the latest major version of FuseBox `v4` is available in `fuse-box@next`. FuseBox has undergone a full re-write from scratch, learning from its mistakes in the previous versions.

There are a lot of improvements, speed and config wise.

Get started [here](https://github.com/fuse-box/fuse-box/blob/master/docs/getting-started/get-started.md)

We are still working on the documentation and polishing before the major release. We are getting very close. And we need help testing.

```bash
npm install fuse-box@next
```

Most of the issues that I am closing have been resolved, however, if you find that your issue is still relevant in `v4` don't hesitate to re-open or (better) create a new one with `v4` configuration.
