### ISSUE TITLE
ScssPlugin fails to resolve imports from nested node_modules

### ISSUE THREAD

**Issue by jsamr** [fuse-box/fuse-box#945]
As per the definition of the [recursive node module resolution algorithm](https://nodejs.org/api/modules.html#modules_loading_from_node_modules_folders), modules should be resolved recursively. It means that any build tool should search for `node_modules` from source directory upwards.

This is working fine with `javascript` modules, but it fails with `scss` modules.

Here is a [minimal working example](https://github.com/sveinburne/fuse-box-scss-import-bug) with instructions to reproduce.

**suggestion**: perhaps `ScssPlugin` should use a shared higher-level library for resolving node modules ? Such a refactoring would avoid duplication of import logic and reduce the risks for bugs and regressions.

**Comment by Devgaze** [comment]
I think you are missing `importer: true` as described here [http://fuse-box.org/plugins/sass-plugin#macros](http://fuse-box.org/plugins/sass-plugin#macros)

**Comment by nchanged** [comment]
@sveinburne actually @Devgaze is right, you can implement any kind of module resolution there.

**Comment by sveinburne** [comment]
@Devgaze @nchanged This was an error when I worked on MWE, I forgot to add this option. But after I did, I could still reproduce. Have committed the change to the repo if you want to give it a try :-)

**Comment by nchanged** [comment]
@sveinburne i think you add `paths` option to the SassPlugin pointed to `packages`

**Comment by sveinburne** [comment]
@nchanged That would mean I need to change `@imports` inside my local npm modules (replacing `~` with `$myPath`)? I don't think making my npm modules coupled to a specific bundler syntax is an acceptable workaround 🙁.
I _found_ a workaround for my specific setup (using `yarn workspaces` link all `node_modules` to project root) but I believe my feature request is still valid at this point 🙂

**Comment by nchanged** [comment]
@sveinburne `importer` option enables macros replacement (we just replacing strings), so in fact, it's up to Sass to resolve it, (we don't do it) but we could, technically setup default `~` to respect node resolve. But I will repeat myself, that's how Sass works.

**Comment by sveinburne** [comment]
@nchanged OK
Perhaps you could add an `upstream` tag in this issue to emphasis the "bug" is comming from SASS and I'll submit an issue to node-sass.

**Comment by nchanged** [comment]
We could implement that too, and all preprocessors would benefit from having it ;-)

**Comment by nchanged** [comment]
### FuseBox v4 Major Upgrade

As of today, the latest major version of FuseBox `v4` is available in `fuse-box@next`. FuseBox has undergone a full re-write from scratch, learning from its mistakes in the previous versions.

There are a lot of improvements, speed and config wise.

Get started [here](https://github.com/fuse-box/fuse-box/blob/master/docs/getting-started/get-started.md)

We are still working on the documentation and polishing before the major release. We are getting very close. And we need help testing.

```bash
npm install fuse-box@next
```

Most of the issues that I am closing have been resolved, however, if you find that your issue is still relevant in `v4` don't hesitate to re-open or (better) create a new one with `v4` configuration.
