### ISSUE TITLE
Imported scss file by other scss when changed, Fuse-box not bundling changes

### ISSUE THREAD

**Issue by serkon** [fuse-box/fuse-box#948]
i have **main.ts** and it is import **main.scss**. Main.scss imports my **imports.scss**.

main.ts ####
import '~/main.scss';

main.scss ####
@import 'src/assets/styles/imports';

imports.scss ####
@import "config";  // --> when change something inside this file
@import "mixins";
@import "reset";
@import "font";
@import "grid";
........

when i change something inside config.scss, this change not bundling to project. If i change main.scss it was bundling.

node v9.2.0
"fuse-box": "^3.0.0-next.15"
"node-sass": "^4.7.1"

**Comment by Shepless** [comment]
@serkon do you have a repo available so we can investigate a bit more?

**Comment by serkon** [comment]
@Shepless hi,
I create angular.io project with fuse-box. When you run npm start the project it will redirect to sample page. Then please inspect 'sample text' element. You will see the .text{...} style class in Elements/Styles tab of developer toolbar. Please click to <style>…</style> right top of corner. It will redirect to inline css. 

But it must be redirect you to find-me.scss. I wish i explained it.

**Comment by serkon** [comment]
Another situation, if you change something inside find-me.scss i expect to see on browser when hmr() is completed. But nothing has been changing. It will be change when restart to "npm start" or change something in main.scss

**Comment by nchanged** [comment]
### FuseBox v4 Major Upgrade

As of today, the latest major version of FuseBox `v4` is available in `fuse-box@next`. FuseBox has undergone a full re-write from scratch, learning from its mistakes in the previous versions.

There are a lot of improvements, speed and config wise.

Get started [here](https://github.com/fuse-box/fuse-box/blob/master/docs/getting-started/get-started.md)

We are still working on the documentation and polishing before the major release. We are getting very close. And we need help testing.

```bash
npm install fuse-box@next
```

Most of the issues that I am closing have been resolved, however, if you find that your issue is still relevant in `v4` don't hesitate to re-open or (better) create a new one with `v4` configuration.
