### ISSUE TITLE
QuantumPlugin - Possibility to bundle shims into app bundle

### ISSUE THREAD

**Issue by jezikk** [fuse-box/fuse-box#958]
Actual state:
- Shims.js is always bundled using QuantumPlugin into the separate file.

Required state:
- To have possibility to bundle shims into one main bundle using QuantumPlugin.

For gulp-like projects is must-have:
https://github.com/jezikk/fuse-box-foundation-starter

**Comment by Shepless** [comment]
@nchanged added to v3 milestone as its a new feature request - pls remove if it's not within scope.

**Comment by nchanged** [comment]
@jezikk it should be easy to implement, maybe you could try submitting a PR? I am very busy ATM

**Comment by jezikk** [comment]
After updating to the latest version shims are bundled into one file using Quantum plugin too. Therefore this issue isn't needed anymore.

**Comment by jezikk** [comment]
My mistake, this issue is still valid.

**Comment by nchanged** [comment]
### FuseBox v4 Major Upgrade

As of today, the latest major version of FuseBox `v4` is available in `fuse-box@next`. FuseBox has undergone a full re-write from scratch, learning from its mistakes in the previous versions.

There are a lot of improvements, speed and config wise.

Get started [here](https://github.com/fuse-box/fuse-box/blob/master/docs/getting-started/get-started.md)

We are still working on the documentation and polishing before the major release. We are getting very close. And we need help testing.

```bash
npm install fuse-box@next
```

Most of the issues that I am closing have been resolved, however, if you find that your issue is still relevant in `v4` don't hesitate to re-open or (better) create a new one with `v4` configuration.
