### ISSUE TITLE
New Sparky Proposal 3.0

### ISSUE THREAD

**Issue by nchanged** [fuse-box/fuse-box#962]
It's time to do something about Sparky too.

It's almost 2018 and using `gulp` style doesn't cut anymore. Personally, i find it tedious.
```
Sparky.task("dist", ["config"]() => { 

})
```

I am proposing taking advantage of `async` `await` syntax instead, and completely re-design Sparky to use a single class. I've seen so many configs, and I noticed a tendency - people want to make a better structure, make it more readable. 

```js
class Tasks extends Sparky {
    // just a class member
    config() {
        return FuseBox.init({
            homeDir: "src",
            output: "dist",
            plugins: [
                this.isProduction && QuantumPlugin()
            ]
        });
    }
    async copyResources() {
        await this.src("**/assets/**.css").copy("dist/assets/css")
        await this.src("**/data/**.txt").copy("dist/assets/files")
    }

    // will be triggered on "node fuse dist"
    async onDist() {
        await this.copyResources();

        const fuse = this.config();
        fuse.bundle("app").instructions(">index.ts");

        await fuse.run()
    }
}
Sparky.attach(Tasks);
```

`Sparky` instance will have all the basic functionality e.g `watch` `src` and e.t.c 
So you will be able to do basic operations right from within your task class. 

Tasks will be defined by adding `on` + `name of the task in camel case`

**Comment by leon-andria** [comment]
I really don't like !

**Comment by nchanged** [comment]
@leon-andria you have to explain why, your arguments

**Comment by devmondo** [comment]
we shall not force people into class-based code. Also, we could have something like `Sparky.parallel` etc...

**Comment by nchanged** [comment]
@devmondo `await this.parallel("method1", "method2")`

**Comment by leon-andria** [comment]
First, I would say that the API design of Sparky now is so beautiful because it's unobtrusive. What I mean is that, with a simple friendly name, you have defined an "Full descriptive" task with its internal logic (like when you do an Unit Test). Now, we are so familiar with this and can organize the tasks the way we want. Also, don't forget how other people use it as this way, more easier to take a friendly name inside a build workflow.
Now, imagine we introduce a class that we need to extend and inside, we hide everything. There is a Pros & Cons:
In general, when we have an abstract class, we want to hide complexity of code and have some lifecycle. But executing a task is straightforward, and not only that, let's say that we do a class, how come we can call a named Task outside of the class ?
What I want to say is that, if you design a API and you make it Open buffer, trust me, all crap things come because people do whatever they want and you can scope.
With the design Sparky, you can make composition of tasks like a Hero and can be viewed in one file.
A task is a task, and this pattern is a old school stuff, like having eexcute(), if you want some hook, beforeExecute() and afterExecute(). And ask Sparky to register your tasks if you have from libs.
Imagine a task that publish files to dropbox or Azure blob storage:
```
Sparky.register("AzureBlobStorage", azureStorageTask)
```
At least implement an intefarce.
Voilà, maybe i'm wrong but this is how i would see it.

**Comment by devmondo** [comment]
@nchanged  ya could be like that, but I lean forward to what @leon-andria said too.

**Comment by patrickmichalina** [comment]
We could leverage rxjs and go full observable streams. This is the most robust way of handling async events. async/await isn't nearly as clean.

**Comment by leon-andria** [comment]
I disagree. This is not a competition of libs, it's about designing a API is an efficient way, feature versus techinical engineer.
And the simplicity should be the key factor. Using the tool to the right requirements is the recommended approach.

**Comment by nchanged** [comment]
I personally like class approach, it's clean, you can set variables. Now you have to do 
```
let fuse, isProduction;
```

with classes, you can easily read these values from properties, which is neat.

**Comment by leon-andria** [comment]
@nchanged We call these "Context" and it's something that is missing in Sparky.
I'm a fan of OOP and having class would be natural for me but using a class to represent a task for me doesn't mean anything. Imagine you create a class and what is the name of your class "TaskThatDoAllStuff" where you have config, dist and so on... 
The concept of task lose the definition of unit of work !

**Comment by nchanged** [comment]
@leon-andria you are wrong. Not just a task, a collection of tasks. A class is just a convenience. All tasks will be withing one class

**Comment by mattoni** [comment]
i think it should be up to the user how to implement. I'm using a class based approach for my bundler and I honestly think it would be better as just a series of functions. Simplicity is the whole point of fuse right? Forcing class syntax is kind of the opposite approach in my opinion. 

At the end of the day the task runner needs to say X -> Y(some context from X) -> Z. I think if we could streamline a syntax to pass an (immutable, preferrably) context from task X to task Z it would be simple and easy to use.

**Comment by leon-andria** [comment]
@nchanged A task should be a unit of work and you compose it ! It's what we are doing now.
@mattoni This is what we call composition and I agree with you.

**Comment by mattoni** [comment]
@leon-andria yep huge fan of composition.

**Comment by nchanged** [comment]
@mattoni you are right. It's just I personally feel that class would look and feel better. We might just have both.

Regarding the current implementation, it definitely needs to be revisited thoroughly, as even `async` functions don't work there. `dest()` should return a Promise, but it doesn't.

Regarding the context, guys, do you think you can propose something? How we can easily execute a series of tasks with a shared context. Like toggling production switch for example.

**Comment by leon-andria** [comment]
```javascript
Sparky.use(() => {
   return { isProduction: false, fuse: null };
});
```
And you have this as singleton or transient.

**Comment by mattoni** [comment]
@leon-andria it should utilize async-await heavily imo. Ability to parallelize tasks OR run them in-sync is vital.

**Comment by leon-andria** [comment]
@mattoni transient

**Comment by nchanged** [comment]
```js



Sparky.task("dist", ctx => {
//   ctx.isProduction
})
Sparky.task("default", [() =>  ({ isProduction: false}), "dist"],() => {

});
```

**Comment by nchanged** [comment]
@leon-andria @mattoni the most important part is how to define a task, change the context, execute series of tasks and then execute task itself. Like in the comment above.

**Comment by mattoni** [comment]
Will also be important to consider typings for `ctx` and make sure we can keep the typings in sync down the line.

**Comment by leon-andria** [comment]
And think it as we use it in a Workflow Orchestration.

**Comment by mattoni** [comment]
What are your thoughts on 1 task = 1 function? `[() =>  ({ isProduction: false}), "dist"]` seems convoluted

**Comment by leon-andria** [comment]
ahahah, look on top of my comment:
```javascript
Sparky.register("AzureBlobStorage", azureStorageTask)
```

This is why a task should be consider as unit of work, I mean a definition of task, not about when you start to compose.

**Comment by ccapndave** [comment]
I also dislike the gulp style, but I sort of dislike classes too (or at least I don't want to be forced into using them).  I'm also not too keen on magic like reflecting on `on<name>`.

After working with Elm for a while, nowadays I find myself tending towards using vanilla functions and built in language features where possible.  So, here is Dave's task runner proposal iteration 1.  The style is based around functional programming idioms, and quite a lot of the ideas come from the never to be released Gulp 4!

## Tasks
Tasks are simply functions.

```ts
// With a lambda
task("build", () => ...);

// Or like this
task("build", build);
function build() {
  ...
}
```

## Dependencies
After years of using build configurations that have tasks that list other tasks as dependencies, I have come to the conclusion that this isn't a very nice paradigm.  Once a build file reaches a certain size it becomes tricky to figure out exactly what is going to be run for a particular task, its annoying to insert extra steps into a chain of dependencies and its tricky to deal with concurrency.

Therefore I would propose the system that Gulp 4 uses, which is to explicity build up chains of functions using concurrency combinators `series` and `parallel`.

```ts
// Note that clean, compile and link are all just functions.  If they need to be runnable from the command line you would assign a name to them using `task`.
const build = series([ clean, compile, link ]));
task("build", build);

task("deploy",
  series([
    build,
    parallel([
      deployToServer1,
      deployToServer2
    ])
  ])
);
```

## Implementation of tasks
My current thinking is that everything should be thunks of `Promise` (I think they have to be thunks so they can be scheduled).

```ts
function task(name: string, f: () => Promise<void>): void;

function series(fs: (() => Promise<void>)[]): () => Promise<void>;
function parallel(fs: (() => Promise<void>)[]): () => Promise<void>;
```

## File pipelines
Since everything is just promises, the functions that deal with file manipulation are totally detached from the task runner - they are just functions that return promise thunks.  The syntax that naturally emerges from using promises looks similar to gulp 3 pipes:

```ts
// Direct copy
src("assets/**")
  .then(dest("somewhereelse"));

// Change the versions in some config file
src("configs/config*.json")
  .then(files => files.map(file => updateJsonVersion(file))) // this would probably be implemented in a prettier helper
  .then(dest("somewhereelse"));

// Deploy using rsync
src("build/**")
  .then(rsync({
    hostname: "deploy@blah.blop.com",
    destination: "/ebs/staging",
    exclude: ["config.json"]
  });
```

This gives lots of power, and makes it super easy to add pretty much any operation that uses promises (or can be lifted into a promise) into the pipeline.

## Watching
There is a slight problem with this in that promises can only resolve/reject once, so implementing watching isn't possible.  Originally I thought that functions could return Rx observables instead of promises, but actually I am now thinking that it would be neater if the watching was moved into the task runner section.  This means that individual functions don't need to care about whether we are in production or development mode.

```ts
const copyAssets = () => src("assets/**").then(dest("build/"));
task("dev", watch("assets/**", copyAssets));
```

In this case `watch` would have to return some kind of stream, but the only thing that needs to deal with that is `task`, and we only allow `watch` at the top level of a task (which I think it ok, as I think that's the only place you'd want to use it).

Also I should point out that having the watcher in the task instead of the function doesn't mean you are forced to repeat globs (as in the example above), or having global variables.  For example:

```
// You can use partial application for DRY code (there are lots of other ways to do this too)
const copyAssets = ({ glob }) =>
  () => src(glob).then(dest("build/"));

task("dev", {
  const assetsGlob = "assets/**";
  return watch(glob, copyAssets({ glob: assetsGlob })));
});
```

## Proposed API
```ts
// Define a task
function task(name: string, f: () => Promise<void>|Observable<void>): void;

// Combinators
function watch(f: () => Promise<void>): () => Observable<void>;
function series(fs: (() => Promise<void>)[]): () => Promise<void>;
function parallel(fs: (() => Promise<void>)[]): () => Promise<void>;

// Files (I'm not exactly sure what `File` is; its not necessarily the nodejs's File)
function src(glob: string): () => Promise<File[]>;
function dest(path: string): (files: File[]) => Promise<void>
```

## Things to think about

 - Since functions that make up tasks don't necessarily have a name the output might not be very nice to read.  I have some ideas about how to deal with this, but none of them are very elegant.

 - The syntax of having lots of `.then(...)`s chained together might not appeal to everyone.  I don't think this is too big a deal as it would be easy to build any kind of syntax on top of this.

 - Since everything is a promise, can we use async/await to do anything nice?

P.S. I haven't actually tested any of the code here is anything, so its very possible that the types don't quite match up :)

**Comment by nchanged** [comment]
@ccapndave awesome! I do, however, have a few things here.
I don't really pipelines `something().pipe(something().pipe(something()))` doesn't look much better than the other solutions. That's the gulp way. We really need something different here, I like `rxjs` idea, but just the idea. (Don't like the lib itself)

We should start avoiding `then` IMHO

```js

const {context, task} = require("fuse-box/sparky");
// define the context 
context({ isProduction : false})

// or a class
context(class {})
// or a function
context(() => { 
	return {isProduction : false}
})

task("default", context({ isProduction : false}), "copy". "dist");

// or 
task("default", context({ isProduction : false}), series("copy". "dist"));

task("copy", context => {

})
task("dist", context => {
	
})
```

**Comment by ccapndave** [comment]
I'm not really sure what Rx (or any streaming library, or generators or whatever) would bring to the table; tasks just run once so Promises seem like the correct fit to me.

From my perspective I think there is a difference between using `.then` with normal promises compared to the mystical `.pipe` from gulp which was sort of half streams, half events, didn't work with some libraries, etc, etc.

In an ideal world, how would you like it to look?

P.S. good call with the `context` :)

**Comment by nchanged** [comment]
@ccapndave I kind of like how it is right now. We have a chain, and if you want that chain to be executed you call `exec()` which will return a Promise, therefore can be used with async await
```
src(glob).files(file => { /*each file*/ }).exec()
```
Whereas file is an object with convenient API (e.g file.copy(), file.remove(), file.move() )
```
src(glob).files(file => file.remove() ).exec()
src(glob).files(file => file.load().setJSON({version : 1}).save() ).exec()
src(glob).files(file => file.load().setJSON({version : 1}).save() ).dest("dist/").exec()
```

**Comment by ccapndave** [comment]
So, that's fine, except that then the implementation is hidden inside `SparkyFlow` or whatever.  For example, I wanted to `rename` a file and had to actually go and fiddle with the Fusebox code because I couldn't just stick a function that returns a Promise into the chain.

I wonder if its possible to implement this chaining style in terms of then `.then`able API, so its just a nicer syntax on top of the real `.then`s?

I don't know if you know any Haskell, but they also think that chaining monads (which is what all the `.then`s are) doesn't look good, so there is a built in `do` notation for making it prettier.

```haskell
-- >>= is equivalent to then
src glob
  >>= doSomeStuff
  >>= dest "dist/"
```

can be rewritten as

```haskell
do
  src glob
  doSomeStuff
  dest "dist/"
```

My point being that maybe we can make it look nicer without losing the power of the underlying representation.

**Comment by ccapndave** [comment]
Here is an example of how you could have the nice chaining API described above implemented as a wrapper on top of normal functions (untested!):

```ts
function src(glob: string): Promise<File[]> {
    // ... get the files
    return Promise.resolve([ /* some files, whatever they are */ ]);
}

function dest(files: File[]): Promise<void> {
    // ... write all the files
    return Promise.resolve();
}

type Bind = (param: any) => Promise<any>;

class Spark {

    private binds: Bind[];

    constructor(bind: any) {
        this.binds = [ bind ];
    }

    public static src(glob: string) {
        return new Spark(() => src(glob));
    }

    public dest(path: string) {
        this.binds.push(dest);
    }

    public exec(): Promise<void> {
        return this.binds.reduce((acc, bind) => acc.then(bind), Promise.resolve());
    }

}
```

**Comment by ccapndave** [comment]
Here is an example of having the nice chaining syntax built on top of a functional `.then` base:

```ts
function src(glob: string): Promise<File[]> {
    // ... get the files
    return Promise.resolve([ /* some files, whatever they are */ ]);
}

function dest(path: string): (files: File[]) => Promise<void> {
    return (files: File[]) => {
        // ... write all the files to path
        return Promise.resolve();
    }
}

type Bind = (param: any) => Promise<any>;

class Spark {

    private binds: Bind[];

    constructor(bind: any) {
        this.binds = [ bind ];
    }

    public static src(glob: string) {
        return new Spark(() => src(glob));
    }

    public dest(path: string) {
        this.binds.push(dest(path));
    }

    public exec(): Promise<void> {
        return this.binds.reduce((acc, bind) => acc.then(bind), Promise.resolve());
    }

}
```

**Comment by nchanged** [comment]
@ccapndave but that's exactly how `SparkFlow` is done xD

**Comment by ccapndave** [comment]
So it is :)  That's awesome then; we can have both kinds of API

**Comment by patrickmichalina** [comment]
@ccapndave rxjs is just an implementation of a [proposed language feature](https://github.com/tc39/proposal-observable). Not sure why you are hostile to one of the best way to manage async data flows.

**Comment by nchanged** [comment]
Ok, so I have made a few tweaks

1) Shortcuts available for import
```
const { src, task, context } = require("fuse-box/sparky");
```

2) Context is passed to every task

```
task("default", async context => {
    await context.cleanDist()
    await context.execute();
    const fuse = context.getConfig();
    context.createBundle(fuse);
    await fuse.run();
});
```

That was really simple to make. I know some of you are not fond of using classes as context, but as i mentioned earlier you can make it immutable by passing a function

```
context({ isProduction : false})

// or a class
context(class {})
// or a function
context(() => { 
	return {isProduction : false}
})
```

Check out the latest `next`  `fuse-box@3.0.0-next.29` and [this](https://github.com/fuse-box/fuse-box-3-preview/blob/master/sparky/fuse.js) example

**Comment by ccapndave** [comment]
@nchanged That looks awesome!  I'll try it out.  Maybe I'll have a look at implementing the `series` and `parallel` functions if you don't mind?

@patrickmichalina I'm not at all hostile to Rxjs; in fact I use it all the time and think its great.  I was just saying I didn't think it was appropriate for this task runner.  I suppose you could model file processing as a stream where files, or file windows, are sent on the stream but I'm not sure what advantage this would give you over sending an array of files and using promises.  As for race conditions, honestly I can only remember experiencing this once (in Gulp) and that was because I forgot to call the `done()` function; something that can't happen if we are using Promises.

**Comment by nchanged** [comment]
@ccapndave oh yes!! Please help ;-)

**Comment by leon-andria** [comment]
@nchanged I'm not fully agree on the design !
Context is more about data, not for having methods and logic !
The given example, maybe it's me but I don't feel enthusiast about it !
And what is fuck me up is that it's looks like already implemented ! What is the goal of discussion if you implement it on behind. Does this apply to a team work ?
Man, you develop a feature when all parties are agreed on, this is not a race !

**Comment by nchanged** [comment]
@leon-andria you need to cool down. 

1) I have just added a context, I didn't change anything.
2) The API stays intact. No breaking changes
3) Yes, you can add methods there and call them (that's how I like them cooking. It's my personal preference). You like them separately - do it separately
4) Lower your tone.

**Comment by arabsight** [comment]
I like the `class Tasks extends Sparky` style, is it an option?

**Comment by nchanged** [comment]
@arabsight we can have yep, optionally, without extends tho ;-)

**Comment by RPDeshaies** [comment]
I also like the `class Tasks extends Sparky` syntax. 
The async/await operators makes things way more readable and manageable.

I was very surprised when I saw that `gulp` syntax when I first tried Sparky. 
Never was a big fan of it. 
It's also very hard to debug because you can't just do `go to definition` of a string..

I also agree that @leon-andria, you should calm down.
Everyone is in the same boat here : we all want the best for this awesome project.

**Comment by CzBuCHi** [comment]
little late to the party but why use class at all? (asuming it would be static class or singleton - instance dont make much sense here ... ) i would prefer use typescript module:

```ts
// i dont like use import x from "fuse-box/whatever" - fells like hack to me
import { whatever, is, needed } from "fuse-box";

// context variable
let production = false; 

// helper function
async function someFunc() {} 

// default task
export default async function() {}

// task named 'someTask' (or only 'some' - dont like that)
export async function someTask() {}
```

this file would be handled by script, that may look like this:

```js
#!/usr/bin/env node  
// shebang used, so it can be called in client package.json scripts as "fuse task params" 
// and not as "node node_modules/fuse-box/fuse.js task params"
// (package.json needs to have "bin" specified)

// projectRoot should be path where client package.json is
const projectRoot = process.cwd();

// configFile could be changed in client package.json
const configFile = "fuse.ts";

const configFileCompiled = await transpileFileToJs(projectRoot + "/" + configFile);

const tasks = require(configFileCompiled); 

// extract taskName and options from process.argv array
const { taskName, options } = processArgs();
const task = tasks[taskName];
task(options);

function processArgs() {
    // command line: "fuse task -a -bc=d --ef --gh=ij 
    // ->
    // taskName = "task"
    // options: { a: true, b: true, c: "d", ef: true, gh: "ij" }
}

async function transpileFileToJs(source) {
    // calls typescript api to generate js from source ts
    // returns path to transpiled js file
}
```

**Comment by nchanged** [comment]
We can close this one @Kompwu it has been done ;-)
