### ISSUE TITLE
Suggestion: Named Sparky task CLI arguments

### ISSUE THREAD

**Issue by ksandin** [fuse-box/fuse-box#979]
Having Sparky automatically read named CLI arguments and pass them on to the task functions would be very powerful. It could be used for anything of course, but one interaction with fuse-box that I really want is something like this:

```typescript
Sparky.task("build", (props: any) => {
  const {env, ...additionalOptions} = props;
  const fuse = FuseBox.init({
    ...defaultOptions,
    ...getEnvironmentOptions(env),
    ...additionalOptions
  });
  // add fuse operations
});
```
Then you could configure your build, devServer and whatever scripts generally and let the user or environment specific options come from ie. each developer or from the build servers.

Like so:
```
ts-node fuse.ts build --env=production
```

**Comment by nchanged** [comment]
### FuseBox v4 Major Upgrade

As of today, the latest major version of FuseBox `v4` is available in `fuse-box@next`. FuseBox has undergone a full re-write from scratch, learning from its mistakes in the previous versions.

There are a lot of improvements, speed and config wise.

Get started [here](https://github.com/fuse-box/fuse-box/blob/master/docs/getting-started/get-started.md)

We are still working on the documentation and polishing before the major release. We are getting very close. And we need help testing.

```bash
npm install fuse-box@next
```

Most of the issues that I am closing have been resolved, however, if you find that your issue is still relevant in `v4` don't hesitate to re-open or (better) create a new one with `v4` configuration.
