### ISSUE TITLE
Can't exclude socket.io from bundle using bundle arithmetic

### ISSUE THREAD

**Issue by nahuel** [fuse-box/fuse-box#993]
Can't exclude `socket.io` from bundle using bundle arithmetic, but it can be correctly excluded using the `ignoreModules` option. Test project:

```shell
cd /tmp ; mkdir -p tt/src ; cd tt
npm init -y 
npm install -D fuse-box typescript
npm install socket.io ulid
```
```js
// src/entry.js
const s = require('socket.io')
const u = require('ulid')
```
```js
/// fuse.js
const { FuseBox } = require("fuse-box");

const fuse = FuseBox.init({
	    homeDir: "src",         
	     output: "dist/$name.js",
	     target:  "server",
	      cache:  false,
           // ignoreModules : ["socket.io"],
});

fuse.bundle("app")
    .instructions(`>entry.js - socket.io - ulid`); 

fuse.run();
```

If your run `node fuse.js`, the bundle will include the `socket.io` source (wrong) but not the `ulid` one (ok). It seems like `socket.io` can only be excluded by uncommenting the `ignoreModules` option on `fuse.js`

Tested with fuse-box 2.5.0-beta.1 and 3.0.0-next.43

**Comment by nchanged** [comment]
Thanks, that will be improved!

**Comment by nchanged** [comment]
### FuseBox v4 Major Upgrade

As of today, the latest major version of FuseBox `v4` is available in `fuse-box@next`. FuseBox has undergone a full re-write from scratch, learning from its mistakes in the previous versions.

There are a lot of improvements, speed and config wise.

Get started [here](https://github.com/fuse-box/fuse-box/blob/master/docs/getting-started/get-started.md)

We are still working on the documentation and polishing before the major release. We are getting very close. And we need help testing.

```bash
npm install fuse-box@next
```

Most of the issues that I am closing have been resolved, however, if you find that your issue is still relevant in `v4` don't hesitate to re-open or (better) create a new one with `v4` configuration.
