### ISSUE TITLE
Aliases with SCSS `composes` behaves strangely

### ISSUE THREAD

**Issue by Cyberlane** [fuse-box/fuse-box#994]
I have this inside one of my scss files:

```
.red {
  composes: block from 'components/Block.scss';
  background-color: red;
}
```

which causes fuse-box to give me the following error:

```
{ Error: ENOENT: no such file or directory, open '/Users/justinnel/Documents/Projects/Cyberlane/fusebox-test/src/components/components/Block.scss'
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '/Users/justinnel/Documents/Projects/Cyberlane/fusebox-test/src/components/components/Block.scss' }
```

My assumption is that how aliases are working, does not cover the use case of `composes` within SCSS?

A project with the problem can be found here: https://github.com/Cyberlane/fusebox-test

**Comment by nchanged** [comment]
@Cyberlane i don't think that's FuseBox, i think it's sass reporting

**Comment by Cyberlane** [comment]
@nchanged it behaves correctly when compiled with WebPack when using `modulesFolder`. 
Is there an extra param I perhaps need to set which FuseBox feeds to sass?

**Comment by nchanged** [comment]
you can try `importer : true` with macros
https://fuse-box.org/plugins/sass-plugin#macros

**Comment by Cyberlane** [comment]
That doesn't seem to make a difference unfortunately.
I did however stumble across this, so perhaps it's a clue as to where the logic should live?

https://github.com/webpack-contrib/css-loader#importing

**Comment by nchanged** [comment]
It should work with macros, create one that points to any folder, like @ for example, there are examples

**Comment by nchanged** [comment]
### FuseBox v4 Major Upgrade

As of today, the latest major version of FuseBox `v4` is available in `fuse-box@next`. FuseBox has undergone a full re-write from scratch, learning from its mistakes in the previous versions.

There are a lot of improvements, speed and config wise.

Get started [here](https://github.com/fuse-box/fuse-box/blob/master/docs/getting-started/get-started.md)

We are still working on the documentation and polishing before the major release. We are getting very close. And we need help testing.

```bash
npm install fuse-box@next
```

Most of the issues that I am closing have been resolved, however, if you find that your issue is still relevant in `v4` don't hesitate to re-open or (better) create a new one with `v4` configuration.
